; Source class template: UltimateEQAssist_WAR.ini
; Generated: 2026-03-10

[General]
KissAssistVer=12.001

[SpellSet]
LoadSpellSet=2

[DPS]
DPSOn=2
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Elbow Strike|99
DebuffAllOn=0

[Aggro]
AggroOn=1
AggroSize=10
Aggro1=Taunt|100|<
Aggro2=Provoke|75|<

[Heals]
HealsOn=1
HealsSize=5
Heals1=Focused Will Discipline|90|cond1

[Burn]
BurnSize=15
BurnAllNamed=0

[KConditions]
ConOn=1
CondSize=5
Cond1=${Me.CombatState.NotEqual[COMBAT]} && ${Me.PctHPs} < 90
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE
