; Source class template: UltimateEQAssist_BRD.ini
; Generated: 2026-03-10

[General]
KissAssistVer=12.001
TwistOn=1
TwistMed=Mana song gem
TwistWhat=2 1

[SpellSet]
LoadSpellSet=2

[Melee]
MeleeTwistOn=1
MeleeTwistWhat=6 8 1 3 8 5

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=25
MezMaxLevel=45
MezStopHPs=80
MezSpell=Crission's Pixie Strike
MezAESpell=NULL

[Burn]
BurnSize=15
BurnAllNamed=0

[Spells]
Gem1=Niv's Melody of Preservation
Gem2=Selo's Accelerando
Gem3=Psalm of Mystic Shielding
Gem4=Cassindra's Chorus of Clarity
Gem5=McVaxius' berserker Crescendo
Gem6=Tuyen's Chant of Flame
Gem7=Crission's Pixie Strike
Gem8=Selo's Consonant Chain
