; KAHybrid Source: L75 - Work in Progress - 75 Shaman (TLP) | https://www.redguides.com/community/resources/75-shaman-tlp.1301/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_SHM.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Shrink|Cond2
Buffs2=Talisman of the Wrulan|Melee
Buffs3=Talisman of Persistence|Melee
Buffs4=!Talisman of Might|Melee|Cond4
Buffs5=!Talisman of the Tribunal|Con5
Buffs6=Talisman of the Stoic One|Melee
Buffs7=Spirit of Bih`Li|Melee
Buffs8=Worg Saddle|Mount
Buffs9=Ancestral Bargain|Mana|80|50
Buffs10=Cannibalization|mana|90|50
Buffs11=!Talisman of the Dire
Buffs12=Wand of Elemental Transvergence|Mana|30|80
Buffs13=Talisman of Foresight|MA
Buffs14=Talisman of the Panther|Melee
Buffs15=Lassitude|MA
Buffs16=Champion|Melee
Buffs17=Pact of the Wolf|Aura
Buffs18=Wishka's Favor Rk. II|Summon|Wishka's Favor Trinket II|1
Buffs19=Wishka's Favor Trinket II
Buffs20=Second Life Rk. II
RebuffOn=1
CheckBuffsTimer=30
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=10
DPSInterval=2
DPS1=Malis Rk. II|100|Malo|Cond1
DPS2=Balance of Discord|99|debuffall|slow
DPS3=Lingering Sloth|99|MA|cond3
DPS4=Spirit Call|99|Cond1
DPS5=Silent Casting|99|cond1
DPS6=Call of the Ancients|99|Cond1
DPS7=Crafted Talisman of Fates|97|Cond1
DPS8=Breath of Ternsmochin|96|Cond1
DPS9=Vengeance of Ahnkaul|95|Cond1
DPS10=Time's Antithesis|94|debuffall|slow
DPS11=Juju Rk. II|90|Cond1
DPS12=Blood Fire Wand|30|Draught of Ro
DPS13=Command:/stand|100|Cond7
DebuffAllOn=2
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=15
Heals1=Spiritual Serenity|55
Heals2=Ahnkaul's Mending|45
Heals3=Union of Spirits|40|weave
Heals4=Specter of Renewal|99|Cond6
AutoRezOn=0
AutoRezWith=Your Rez Item/AA/Spell
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=1
Cures1=Blood of Nadox|poison
Cures2=Pure Spirit
Cures3=Chant of Napaea Rk. II|Curse
Cures4=Radiant Cure
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Kyrah's Faithful
PetBuffsOn=1
PetBuffsSize=2
PetBuffs1=Spirit Quickening
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=5
BurnAllNamed=0
Burn1=Balance of Discord|99|debuffall|slow
Burn2=Putrid Decay|95|once
Burn3=Blood of Yoppa|85|once
Burn4=Curse of Sisslak|75|once
Burn5=Ice Age|60

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=7
Cond1=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond2=(${Me.Height} > 3.00)
Cond3=!${Target.Buff[Lingering Sloth].ID}
Cond4=!${Target.Buff[Mammoth's Strength].ID} || !${Target.Buff[Rathe's Strength].ID}
Cond5=!${Target.Buff[Protection of Wishka].ID}
Cond6=(${Group.Injured[75]} >= 3)
Cond7=${Me.Feigning}

[Gems]
Gem1=Ahnkaul's Mending
Gem2=Specter of Renewal
Gem3=Balance of Discord
Gem4=Juju
Gem5=Vengeance of Ahnkaul
Gem6=Pure Spirit
Gem7=Breath of Temsmochin
Gem8=Ancestral Bargain
Gem9=Malis
