; KAHybrid Source: L75 - Necro 75 ini w/Con | https://www.redguides.com/community/resources/necro-75-ini-w-con.2173/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_NEC.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Shield of Darkness
Buffs2=Grim Aura
Buffs3=Otherside
Buffs4=Banshee Aura
Buffs5=Wraithskin
Buffs6=Vampiric Embrace
Buffs7=Illusion: |Remove
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=6
DPSInterval=4
DPS1=Severan's Rot|98
DPS2=Ashengate Pyre|98
DPS3=Pyre of the Fallen|98
DPS4=Curse of Mortality|98
DPS5=Kedgefish Venom| 98
DPS6=Coruscating Darkness|98
DPS7=Demand for Blood|90
DPS8=Scent of Twilight|99|Once
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Touch of Death|80
Heals2=Mend Companion|50|pet
Heals3=Harmshield|20
Heals4=Death Peace|10
AutoRezOn=0
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Riza'farr's Shadow
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Sigil of the Unatural
PetBuffs3=Aegis of Calliav
PetRampPullWait=0
PetSuspend=1
PetForceHealOnMed=0

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Silent Casting
Burn2=Encroaching Darkness
Burn3=Swarm of Decay
Burn4=Wake the Dead
Burn5=Life Burn

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=5
Cond1=!${Target.Buff[Severan's Rot].ID} && ${Range.Between[45,98:${Target.PctHPs}]}
Cond2=!${Target.Buff[Ashengate Pyre].ID} && ${Range.Between[45,98:${Target.PctHPs}]}
Cond3=!${Target.Buff[Pyre of the Fallen].ID} && ${Range.Between[45,98:${Target.PctHPs}]}
Cond4=!${Target.Buff[Curse of Mortality].ID} && ${Range.Between[45,98:${Target.PctHPs}]}
Cond5=!${Target.Buff[Kedgefish Venom].ID} && ${Range.Between[45,98:${Target.PctHPs}]}
Cond6=!${Target.Buff[Coruscating Darkness].ID} && ${Range.Between[45,98:${Target.PctHPs}]}

[Spells]
Gem1=Severan's Rot
Gem2=Ashengate Pyre
Gem3=Pyre of the Fallen
Gem4=Curse of Mortality
Gem5=Kedgefish Venom
Gem6=Coruscating Darkness
Gem7=Demand for Blood
Gem8=Scent of Twilight
Gem9=Riza'farr's Shadow
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
