; KAHybrid Source: L75 - Lvl 75 WIZ ini w/o conditions for KA12 | https://www.redguides.com/community/resources/lvl-75-wiz-ini-w-o-conditions-for-ka12.1526/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_WIZ.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=10
Buffs1=Elemental Barrier
Buffs2=Greater Familiar
Buffs3=Patient Harvest|Mana|40
Buffs4=Shield of the Crystalwing
Buffs5=Defense of Calrena|!me
Buffs6=Spellshield
Buffs7=O'Keil's Flickering Flame|ma
Buffs8=Scales of the Crystalwing
Buffs9=Crystalwing Ward
Buffs10=Harvest of Druzzil|Mana|30
Buffs11=Tendrilmist Guard
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Icicle Deluge|3

[DPS]
DPSOn=1
DPSSize=5
DPSSkip=20
DPSInterval=2
DPS1=Ethantis's Burning Blade|98
DPS2=Claw of Selay|80
DPS3=Sothgar's Flame|70
DPS4=Leap of Shocking Bolts|65
DPS5=Atol's Spectral Shackles|45
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=2
Aggro1=Concussion|55|>

[Burn]
BurnSize=8
BurnAllNamed=1
Burn1=Call of Xuzl
Burn2=Ward of Destruction
Burn3=Frenzied Devastation
Burn4=Sothgar's Flame
Burn5=Mind Crash
Burn6=Claw of Selay
Burn7=Concussion
Burn8=Leap of Shocking Bolts

[GoM]
GoMSize=3
GoMSpell1=Leap of Shocking Bolts

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Claw of Selay
Gem2=Sothgar's Flame
Gem3=Concussion
Gem4=Leap of Shocking Bolts
Gem5=Patient Harvest
Gem6=Evacuate
Gem7=Atol's Spectral Shackles
Gem8=Ethantis's Burning Blade
Gem9=Icicle Deluge
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
