; KAHybrid Source: L75 - Work in Progress - 75 Bard (TLP) | https://www.redguides.com/community/resources/75-bard-tlp.1300/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_BRD.ini

[General]
KissAssistVer=12.001
TwistOn=1
TwistMed=0
TwistWhat=9 1 2 3 4 7 1 2 3 4 7 1 2 3 4 7 5
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Aura of the Muse|Me
Buffs2=Songblade of the Eternal|Dual|Symphony of Battle|Me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Melee]
MeleeTwistOn=1
MeleeTwistWhat=Continuous

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Kick|99
DPS2=Puretone Discipline|99|Cond1
DPS3=Deftdance Discipline|99|Cond1
DPS4=Intensity of the Resolute|98|Cond1
DPS5=Boastful Bellow|98|Cond2
DPS6=Symbol of Mezzoforte|95|Cond1
DPS7=Bladed Song|93|Cond1
DPS8=Blade of Vesagran|92|Cond1
DPS9=Singing Energeiac Plate Breastplate|90|Cond1
DPS10=Trumpet of the Dragon Goddess|80|Weave
DPS11=Thousand Blades|60|Cond1
DPS12=Cacophony|60|Cond1
DPS13=Funeral Dirge|60|Cond1
DPS14=Dance of Blades|30|Cond1
DPS15=Song of Stone|50|Cond1
DPS16=Farseeker's Plate Chestguard of Harmony|50|Cond1
DPS17=Speaker of the Scale|45|Weave
DPS18=Command:/stand|100|Cond4
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Hymn of the Last Stand|50

[Heals]
HealsOn=1
HealsSize=5
Heals1=Shield of Notes|40|Tap
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[KConditions]
ConOn=1
CondSize=4
Cond1=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond2=${Target.PctHPs} > 5 && ${Me.PctEndurance} > 20 && ${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]} && ${Target.PctHPs} > 5 && ${Me.PctEndurance} > 20
Cond3=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+1]} && ${SpawnCount[npc radius 50]}>3
Cond4=${Me.Feigning}

[Spells]
Gem1=War March of Muram
Gem2=Aviak's Wondrous Warble Rk. II
Gem3=Psalm of Veeshan
Gem4=Arcane Aria
Gem5=Veshma's Lively Crescendo Rk. III
Gem6=Aura of the Muse
Gem7=Storm Blade
Gem8=Queen Eletyl's Screech Rk. II
Gem9=Selo's Accelerating Chorus
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[/CODE]

[Cures]
CuresOn=0
CuresCOn=0
