; KAHybrid Source: L75 - Lvl 75 ENC ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-75-enc-ini-w-conditions-for-ka11.1132/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_ENC.ini

[General]
KissAssistVer=11.004
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=23
Buffs1=!White Rope Bridle|mount
Buffs2=Hastening of Ellowind|me
Buffs3=Night's Dark Terror|!ma
Buffs4=Voice of Intuition|me
Buffs5=Intellectual Superiority|caster
Buffs6=Guard of Druzzil|me
Buffs7=Reflect
Buffs8=Gather Mana|mana|25
Buffs9=Brimstone Body
Buffs10=Sorcerous Shield
Buffs11=Illusionist's Aura|Aura
Buffs12=Rod of Mystical Transvergence|Mana|30|60
Buffs13=Legion of Alendar|me
Buffs14=Mana Recursion|class|MAG,BST,DRU,WIZ,ENC
Buffs15=Gift of Brilliance|caster
Buffs16=Glamorous Visage|class|MAG,DRU,WIZ,ENC
Buffs17=Wand of Elemental Transvergence|Mana|30|60
Buffs18=Ward of Bewilderment
Buffs19=Azure Mind Crystal
Buffs20=Azure Mind Crystal|Mana|35|55
Buffs21=Sanguine Mind Crystal
Buffs22=Sanguine Mind Crystal|Mana|30|50
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Echo of Tashan|95|debuffall|tash|always
DPS2=Desolate Deeds|90|debuffall|slow|if|howl of tashan
DPS3=Fractured Consciousness|80
DPS4=Mind Phobiate|75
DPS5=Thin Air|70
DPS6=Boggle|65
DPS7=Polychromatic Assault|60
DPS8=Beguiler's Directed Banishment|50
DPS18=Eldritch Rune|45|cond1
DPS19=Mind Over Matter|40|cond2
DPS20=Self Stasis|15
DebuffAllOn=1
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=4
Aggro1=Glamorous Visage|50|>
Aggro2=Silent Casting|60|>
Aggro3=Arcane Whisper|80|>

[Heals]
HealsOn=1
HealsSize=5
Heals1=Friendly Stasis|10|cond3
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Ellowind's Animation
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Night's Dark Terror
PetBuffs2=Companion's Fortification|once
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=65
MezMaxLevel=78
MezStopHPs=80
MezSpell=Bewilderment
MezAESpell=Dreams of Veldyn|3

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Doppelganger
Burn2=Beguiler's Banishment
Burn3=Companion's Fortification
Burn4=Veil of Mindshadow
Burn14=Noctambulate|cond4

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=4
Cond1=${Target.ID} && ${Target.Type.Equal[NPC]} && ${Me.PctHPs} < 80
Cond2=${Target.ID} && ${Target.Type.Equal[NPC]} && ${Me.PctHPs} < 40
Cond3=${Target.ID} && ${Target.Type.Equal[PC]} && ${Spawn[pc ${Target.CleanName}].Class.Name.Equal[Cleric]}
Cond4=${Target.ID} && !${Target.Named}

[MySpells]
Gem1=Mind Phobiate
Gem2=Desolate Deeds
Gem3=Fractured Consciousness Rk. II
Gem4=Echo of Tashan
Gem5=Bewilderment
Gem6=Dreams of Veldyn
Gem7=Night's Dark Terror
Gem8=Polychromatic Assault
Gem9=Thin Air
Gem10=Ward of Bewilderment

[Cures]
CuresOn=0
CuresCOn=0
