; KAHybrid Source: L75 - Lvl 75 SHD ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-75-shd-ini-w-conditions-for-ka11.1135/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_SHD.ini

[General]
KissAssistVer=11.004
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=8
Buffs1=Voice of Thule|MA
Buffs2=Shroud of the Nightborn
Buffs3=Cloak of Corruption
Buffs4=Dark Bargain
Buffs5=Wand of Elemental Transvergence|Mana|30|60
Buffs6=Rod of Mystical Transvergence|Mana|30|60
Buffs7=Remorseless Demeanor
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=3
AERadius=50
AE1=Vilify|3|mob

[DPS]
DPSOn=1
DPSSize=11
DPSSkip=5
DPSInterval=2
DPS1=Bash|99|mash
DPS2=Festering Darkness|95
DPS3=Theft of Agony|90
DPS4=Dark Constriction|80
DPS5=RotRoot Spear|75
DPS6=Blood of the Blacktalon|55
DPS7=Encroaching Darkness|30
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=4
Aggro1=Challenge for Power|85|<

[Heals]
HealsOn=1
HealsSize=5
Heals1=Touch of Severan|95|weave
Heals2=Blacktalon Bite|95|weave
Heals3=Inruku's Bite|95|weave
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=1
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Shambling Minion
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Amplify Death
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=11
BurnAllNamed=1
Burn1=Soul Carapace|cond4
Burn2=Companion's Fortification
Burn3=Chattering Bones
Burn4=Deflection Discipline|cond1
Burn5=Leechcurse Discipline|cond4
Burn6=Unholy Aura|cond4
Burn7=Terror of Vergalid|mob
Burn8=Harmshield|cond3
Burn9=Ichor Guard|cond4

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=7
Cond1=${Me.Inventory[14].Type.Equal[Shield]} && !${Me.ActiveDisc.ID}
Cond2=${Target.Type.Equal[NPC]} && ${Me.PctHPs} < 40
Cond3=${Target.Type.Equal[NPC]} && ${Me.PctHPs} < 20
Cond4=!${Me.ActiveDisc.ID}
Cond5=${Me.CombatState.NotEqual[COMBAT]}

[MySpells]
Gem1=Touch of Severan
Gem2=Blood of the Blacktalon
Gem3=Theft of Agony
Gem4=Dark Constriction
Gem5=Festering Darkness
Gem6=Rotroot Spear
Gem7=Blacktalon Bite
Gem8=Challenge for Power
Gem9=Vilify
Gem10=Inruku's Bite
