; KAHybrid Source: L75 - Lvl 75 DRU ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-75-dru-ini-w-conditions-for-ka11.1131/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_DRU.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Flight of Eagles|ma
Buffs2=Skin of the Reptile|MA
Buffs3=Form of the Hunter|me
Buffs4=Mask of the Stalker|me
Buffs5=Second Life
Buffs6=Vidifloral Shield|ma
Buffs7=Wand of Elemental Transvergence|Mana|30|60
Buffs8=Blessing of Oak|me
Buffs9=Aura of Life|Aura
Buffs10=Rod of Mystical Transvergence|Mana|30|60
Buffs11=Direwood Guard
Buffs12=Wrath of the Wild|ma|cond6
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=11
DPSSkip=10
DPSInterval=2
DPS1=Sunscorch|98
DPS2=Spirit of the Great Wolf|97
DPS3=Spirit of the Wood|96
DPS4=Swarm of Fireants|80|Once
DPS5=Sylvan Fire|75|Once
DPS6=Glitterfrost|70
DPS7=Combat Spellbook|65|Item|cond1
DPS8=Equinox Burn|60
DPS9=Hungry Vines|55
DPS10=Nature's Blazing Wrath|50
DPS11=Entrap|30
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Silent Casting|75|>

[Heals]
HealsOn=1
HealsSize=4
Heals1=Nature's Recovery|50
Heals2=Adrenaline Surge|40
Heals3=Moonshadow|25
Heals4=Convergence of Spirits|15
AutoRezOn=0
AutoRezWith=Your Rez Item/AA/Spell
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Eradicate Disease|disease
Cures2=Eradicate Poison|poison
Cures3=Remove Greater Curse|curse
Cures4=Radiant Cure
Cures5=Cure Corruption
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Nature Walker's Behest
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Savage Spirit
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Nature's Guardian
Burn2=Silent Casting
Burn3=Peaceful Spirit of the Wood|ma|cond5
Burn4=Entrap|cond3
Burn5=Wrath of the Wild|ma
Burn6=Nature's Boon|cond2
Burn7=Spirit of the Wood|ma|cond4

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=6
Cond1=${Target.PctHPs} < 40 && ${Cast.Ready[Combat Spellbook]}
Cond2=${SpawnCount[Call of the Ancients]}<1 && ${SpawnCount[Exquisite Benediction]}<1 && ${SpawnCount[Nature's Boon]}<1
Cond3=${Target.PctHPs} < 30
Cond4=${Spawn[ID ${Group.MainAssist.ID}].PctHPs} < 50
Cond5=${Spawn[ID ${Group.MainAssist.ID}].PctHPs} < 30
Cond6=${Target.CombatState.Equal[COMBAT]}

[MySpells]
Gem1=Hungry Vines
Gem2=Swarm of Fireants
Gem3=Sunscorch
Gem4=Adrenaline Surge
Gem5=Moonshadow
Gem6=Succor
Gem7=Equinox Burn
Gem8=Viridifloral Shield
Gem9=Nature's Blazing Wrath
Gem10=Nature's Recovery
