; Source class template: UltimateEQAssist_L75_RNG.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=9
Buffs1=Briarcoat
Buffs2=Protection of the Minohten
Buffs3=Eyes of the Owl
Buffs4=Snarl of the Predator|MA
Buffs5=Strength of the Forest Stalker|MA
Buffs6=Thundering Blades
Buffs7=Consumed by the Hunt
Buffs8=Spirit of Eagle
Buffs9=Obsidian Skin|Me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Outrider's Evasion|3

[DPS]
DPSOn=1
DPSSize=15
DPSSkip=2
DPSInterval=2
DPS1=Warder's Wrath|99|Cond1
DPS2=Entrap|99|Cond2
DPS3=Aurora, the Heartwood Blade|99
DPS4=Guardian of the Forest|99
DPS5=Outrider's Accuracy|99|Cond4
DPS6=Auspice of the Hunter|99|Cond5
DPS7=Silent Strikes|99|Cond3
DPS8=Wasp Swarm|99|Cond6
DPS9=Ancient: North Wind|99
DPS10=Scorched Earth|99
DPS11=Icefall Chill|99|Cond6
DPS12=Volcanic Ash|99|Cond6
DPS13=Heartshot|99|Cond7
DPS14=Hail of Arrows|99|Cond8
DPS15=Protection of the Spirit Wolf|99|Cond1
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Jolting kicks|90|>

[Cures]
CuresOn=1
CuresSize=5
Cures1=Potamide Salve
CuresCOn=1

[Burn]
BurnSize=5
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=8
Cond1=${Target.Named}
Cond2=!${Target.Snared.ID} && ${Target.PctHPs} < 40
Cond3=${Me.PctAggro} > 96
Cond4=!${Me.Song[Guardian of the Forest].ID}
Cond5=!${Me.Song[Falcon Strike].ID} && !${Me.Song[Auspice of the Hunter].ID}
Cond6=${Me.PctMana} > 49
Cond7=${Target.Body.Name.Equal[Humanoid]} || ${Target.Body.Name.Equal[Animal]}
Cond8=${Me.XTarget} > 3

[MySpells]
Gem1=Wasp Swarm
Gem2=Ancient: North Wind
Gem3=Icefall Chill
Gem4=Scorched Earth
Gem5=Volcanic Ash
Gem6=Hail of Arrows
Gem7=Heartshot
Gem8=Nature's Entropy
Gem9=Vinelash Cascade
Gem10=Potamide Salve
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Heals]
HealsOn=0
HealsCOn=0
