; Source class template: UltimateEQAssist_L75_MAG.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Regal Worg Saddle|Mount
Buffs2=Phantasmal Warden|Me
Buffs3=Circle of Magmaskin|MA
Buffs4=Elemental Symbiosis|Me
Buffs5=Wand of Elemental Transvergence|Mana|30|60
Buffs6=Elemental Barrier
Buffs7=Summon Wintry Paradox|Summon|Summoned: Elemental Ice Fragment|1
Buffs8=Mass Elemental Transvergence|Summon|Wand of Elemental Transvergence|1
Buffs9=Burning Aura|Melee
Buffs10=Summon: Molten Orb|Summon|Molten Orb|1
Buffs11=Staff of Elemental Essence|Elemental Conjunction|Pet|Cond2
RebuffOn=1
CheckBuffsTimer=35
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Malosinise|100|Malo
DPS2=Wrath of the Elements|99|Once|Cond1
DPS3=Heart of Skyfire|99|Weave|Cond1
DPS4=Rampaging Servant|98|Cond1
DPS5=Companion's Fury|99|Cond1
DPS6=Servant of Ro|99|Cond1
DPS7=Host of the Elements|99|Cond1
DPS8=Bolt of Molten Slag|85
DPS9=Shock of Silvered Steel|95
DPS10=Fickle Inferno|95
DPS11=Summoned: Elemental Ice Sliver|91|Weave
DPS12=Dagger of Evil Summons|90|Sun Vortex
DPS13=Molten Orb|97|Weave
DPS14=Command:/stand|100|Cond3
DebuffAllOn=2
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Heart of Froststone|99|Weave|Cond1

[Heals]
HealsOn=1
HealsSize=3
Heals1=Renewal of Aenda|60|Pet
Heals2=Mend Companion|30|Pet
Heals3=Shared Health|45
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Essence of Air
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Burnout VI
PetBuffs2=Aegis of Calliav
PetBuffs3=Rathe's Strength
PetBuffs4=Iceflame Guard
PetToysOn=1
PetToysSize=4
PetToys1=Summon Elemental Armaments|Summoned: Windwoven Dreamcatcher|Summoned: Windwoven Dreamcatcher
PetToys2=Summon Muzzle of Mowcha
PetToys3=Summon Plate of the Elements
PetToysGave=Jasober|Summon Elemental Armaments:Summoned: Windwoven Dreamcatcher1|Summon Elemental Armaments:Summoned: Windwoven Dreamcatcher2|Summon Muzzle of Mowcha:Summoned: Muzzle of Mowcha|Summon Plate of the Elements
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=0
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=3
Cond1=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond2=${Me.Pet.ID} && !${Me.PetBuff[Elemental Conjunction]}
Cond3=${Me.Feigning}

[Spells]
Gem1=Bolt of Molten Slag
Gem2=Shock of Silvered Steel
Gem3=Fickle Inferno
Gem4=Renewal of Aenda
Gem5=Wraith of the Elements
Gem6=Malosinise
Gem7=Annul Magic
Gem8=Aegis of Calliv
Gem9=Rampaging Servant

[Cures]
CuresOn=0
CuresCOn=0
