; Source class template: UltimateEQAssist_L75_BST.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=11.004
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Spiritual Vim|me
Buffs2=Infusion of Spirit|melee
Buffs3=Spiritual Vitality|me
Buffs4=Ruthless Ferocity|melee
Buffs5=Focus of Amilan|melee
Buffs6=Spiritual Ascendance|me
Buffs7=Paragon of Spirit|managroup|80
Buffs8=Rod of Mystical Transvergence|Mana|30|60
Buffs9=Symbol of the Planemasters|dual|Pestilence Shock
Buffs10=Wand of Elemental Transvergence|Mana|30|60
Buffs11=Pact of the Wurine|Dual|Pact of the Wurine I
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=5
DPSInterval=2
DPS1=Growl of the Panther|99|once
DPS2=Bark at the Moon|98|weave
DPS3=Eagle Strike|98|weave
DPS4=Dragon Punch|98|weave
DPS5=Tiger Claw|95
DPS6=Fever Spike|60
DPS7=Diregriffon's Bite|50
DPS8=Chimera Blood|40
DPS9=Bite of the Empress|20
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Roar of Thunder|70|>

[Heals]
HealsOn=1
HealsSize=5
Heals1=Healing of Uluanes|50|pet
Heals2=Promised Mending|35|pet
Heals3=Mend Companion|30|pet
Heals4=Minohten Mending|30
Heals5=Companion's Fortification|25|pet
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Spirit of Uluanes
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Spellbreaker's Guard
PetBuffs2=Spirit of Lairn
PetBuffs3=Mammoth-Hide Guard
PetBuffs4=Ruthless Ferocity
PetBuffs5=Unparalleled Voracity
PetBuffs6=Steeltrap Jaws
PetBuffs7=Taste of Blood|once
PetRampPullWait=0
PetSuspend=1
PetForceHealOnMed=1

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Companion's Fortification
Burn2=Frenzy of Spirit
Burn3=Bestial Alignment
Burn4=Bestial Empathy
Burn5=Bestial Fury Discipline|cond2
Burn6=Protective Spirit Discipline|cond1
Burn7=Bite of the Empress
Burn8=Diregriffon's Bite
Burn9=Roar of Thunder

[GoM]
GoMSize=3
GoMSpell1=Ancient: Savage Ice

[KConditions]
ConOn=1
CondSize=5
Cond1=${Me.CombatAbilityReady[Protective Spirit Discipline]} && !${If[${Me.ActiveDisc.ID},TRUE,FALSE]}
Cond2=${Me.CombatAbilityReady[Bestial Fury Discipline]} && !${If[${Me.ActiveDisc.ID},TRUE,FALSE]}
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[MySpells]
Gem1=Minohten Mending
Gem2=Healing of Uluanes
Gem3=Growl of the Panther
Gem4=Fever Spike
Gem5=Diregriffon's Bite
Gem6=Bite of the Empress
Gem7=Bestial Empathy
Gem8=Sha's Legacy
Gem9=Promised Mending
