; KAHybrid Source: L65 - 65 Paladin - Retribution EQ | https://www.redguides.com/community/resources/65-paladin-retribution-eq.2958/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_PAL.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Ward of Nife|Me
Buffs2=Brell's Stalwart Shield|Group
Buffs4=Symbol of Marzin|Group
Buffs5=Bulwark of Faith|Group
Buffs6=Apocryphal Flawless Steel Mask|dual|Sympathetic Healing Burst V|Me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Beacon of the Righteous|2|mob

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Deny Undead|90|Cond1
DPS2=Disarm|97|Mash
DPS3=Quellious' Word of Tranquility|75
DPS4=Quellious' Word of Serenity|75
DPS5=Bash|98
DPS6=Force of Akilae|95
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=10
Aggro1=Taunt|100|<
Aggro2=Quellious' Word of Tranquility|75|<<
Aggro3=Divine Stun|90|<
Aggro4=Beacon of the Righteous|50|<<
Aggro5=Quellious' Word of Serenity|75|<<

[Heals]
HealsOn=1
HealsSize=15
Heals1=Wave of Trushar|70|!MA
Heals2=Healing Wave of Prexus|60|!MA
Heals3=Light of Order|15|ME
Heals4=Lay On Hands|30|CLASS|PAL,CLR,SHM,DRU
Heals5=Resurrection|0|rezooc
Heals6=Wave of Marr|70|!MA
Heals7=Light of Order|40|CLASS|CLR,SHM,DRU
Heals8=Light of Nife|40|CLASS|CLR,SHM,DRU
Heals9=Light of Nife|15|ME
AutoRezOn=2
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Crusader's Touch|Disease
Cures2=Crusader's Touch|Curse
Cures3=Crusader's Touch|Poison
CuresCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=10
Cond1=${Target.Body.Name.Equal[Undead]}
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE
Cond6=TRUE
Cond7=TRUE
Cond8=TRUE
Cond9=${Me.Inventory[14].Type.Equal[Shield]}
Cond10=TRUE

[Spells]
Gem1=Deny Undead
Gem2=Quellious' Word of Serenity
Gem3=Quellious' Word of Tranquility
Gem4=Force of Akilae
Gem5=Crusader's Touch
Gem6=Wave of Marr
Gem7=Wave of Trushar
Gem8=Healing Wave of Prexus
Gem9=Supernal Cleansing
Gem10=Light of Order
Gem11=Light of Nife
Gem12=Blessed Aura
