; KAHybrid Source: L70 - Lvl 70 WAR ini w/o conditions for KA11 - FTP | https://www.redguides.com/community/resources/lvl-70-war-ini-w-o-conditions-for-ka11-ftp.1369/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_WAR.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=3
Buffs1=Champion's Aura|Aura
Buffs2=Commanding Voice|me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=4
AERadius=50
AE1=Aura of Runes Discipline|3
AE2=Area Taunt|3
AE3=Cyclone Blade|4

[DPS]
DPSOn=1
DPSSize=1
DPSSkip=1
DPSInterval=2
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=3
Aggro1=Bazu Bellow|94|<
Aggro2=Mock|85|<

[Heals]
HealsOn=1
HealsSize=3
Heals1=Healing Will Discipline|60
Heals2=Furious Discipline|19|cond1
HealsCOn=1

[Burn]
BurnSize=11
BurnAllNamed=1
Burn1=Stonewall Discipline
Burn2=Shocking Defense Discipline
Burn3=Aura of Runes Discipline
Burn4=Charge Discipline
Burn5=Mighty Strike Discipline
Burn6=Furious Discipline
Burn7=Precision Discipline
Burn8=Fellstrike Discipline
Burn9=Fortitude Discipline
Burn10=Aggressive Discipline

[KConditions]
ConOn=1
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[/CODE]

[Cures]
CuresOn=1
CuresCOn=1
