; Source class template: UltimateEQAssist_L50_CLR.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=9
Buffs1=Frenzied Strength|Melee
Buffs2=Shield of Words|Melee
Buffs3=Resolution|Melee
Buffs4=Symbol of Naltron|Melee
Buffs5=Resist Poison|MA
Buffs6=Resist Fire|MA
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=5
DPSSkip=20
DPSInterval=2
DPS1=Sound of Force|50|cond1
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=10
Heals1=Healing Light|70|MA
Heals2=Healing Light|69|Class|SHD,WAR,PAL
Heals3=Superior Healing|60|Class|CLR,ENC,WIZ,DRU,SHM,BST,RNG,MNK,ROG,MAG,NEC,BRD
Heals4=Word of Healing|60|Group
Heals5=Divine Barrier|20|cond2
Heals6=Resurrection|0|rezooc
AutoRezOn=0
AutoRezWith=Resurrection
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=5
Cond1=${Me.PctMana} > 80 && ${Target.Level} < 56 && ${Raid.Members} = 0
Cond2=${Me.CurrentMana} > 100 && ${Me.PctMana} < 10
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Complete Healing
Gem2=Healing Light
Gem3=Superior Healing
Gem4=Word of Healing
Gem5=Divine Barrier
Gem6=Sound of Force
Gem7=Frenzied Strength
Gem8=Symbol of Naltron
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
