; Source class template: UltimateEQAssist_L50_BRD.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=12.001
TwistOn=1
TwistMed=Mana song gem
TwistWhat=2 1
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Melee]
MeleeTwistOn=1
MeleeTwistWhat=6 8 1 3 8 5

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=25
MezMaxLevel=45
MezStopHPs=80
MezSpell=Crission's Pixie Strike
MezAESpell=NULL

[Burn]
BurnSize=15
BurnAllNamed=0

[Spells]
Gem1=Niv's Melody of Preservation
Gem2=Selo's Accelerando
Gem3=Psalm of Mystic Shielding
Gem4=Cassindra's Chorus of Clarity
Gem5=McVaxius' berserker Crescendo
Gem6=Tuyen's Chant of Flame
Gem7=Crission's Pixie Strike
Gem8=Selo's Consonant Chain

[DPS]
DPSOn=0
DPSCOn=0

[Buffs]
BuffsOn=0
BuffsCOn=0

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
