; Source class template: UltimateEQAssist_L50_MNK.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=10.2.3
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Golden Star Slippers|Dual|Shadow of Firefist
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Hundred Fists Discipline|3
AE3=Thunderkick Discipline|2

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=0
DPSInterval=1
DPS1=Flying Kick|99
DPS2=Dragon Punch|99
DebuffAllOn=0
DPSCOn=1

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Hundred Fists Discipline

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
