; Source class template: UltimateEQAssist_L50_ROG.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=12.002
CharInfo=Rogue|50|FREE
Role=Assist
CampRadius=35
CampRadiusExceed=400
ReturnToCamp=1
ChaseAssist=0
ChaseDistance=25
CampfireOn=0
MedOn=1
MedStart=30
MedStop=100
MedCombat=0
RezAcceptOn=1|50
AcceptInvitesOn=1
GroupWatchOn=0
GroupWatchCheck=FALSE
CorpseRecoveryOn=1
EQBCOn=0
DanNetOn=1
ScatterOn=1
LOSBeforeCombat=1
BuffWhileChasing=1
CastRetries=3
ReturnToCampAccuracy=10

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=NULL
Buffs2=command:/useitem Worn Totem|Dual|Blessing of Swiftness|Cond6
Buffs3=command:/notify AlertWnd ALW_Dismiss_Button leftmouseup
Buffs4=Bite of the Shissar VIII|Dual|Bite of the Shissar Poison IV|Cond7
Buffs5=Focused Will Discipline|Cond8
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Melee]
AssistAt=98
MeleeOn=1
FaceMobOn=2
MeleeDistance=60
StickHow=snaproll rear 17
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
AutoHide=1

[DPS]
DPSOn=1
DPSSize=1
DPSSkip=1
DPSInterval=1
DPS1=Resistant Discipline|Me|Cond4
DebuffAllOn=0
DPSCOn=1

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=3
Burn1=Intensity of the Resolute
Burn2=Armor of Experience
Burn3=Resistant Discipline

[KConditions]
ConOn=1
CondSize=8
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.ConColor.Equal[White]} || ${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]}
Cond4=${Target.Named} && (${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]})
Cond5=${Me.GroupAssistTarget.Named}
Cond6=!${Me.Buff[Blessing of Swiftness].ID} && ${Spell[Blessing of Swiftness].Stacks} && ${Me.FreeBuffSlots} > 0
Cond7=${FindItemCount[Bite of the Shissar VIII]} > 0
Cond8=${Me.PctHPs} < 80

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
