; Source class template: UltimateEQAssist_L25_PAL.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Center
Buffs2=Holy Armor
Buffs3=Symbol of Transal
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=5
DPSSkip=20
DPSInterval=2
DPS1=Yaulp|98
DPS2=Reckless Strength|95
DPS3=Desist|80
DPS4=Breath of Keikolin|50
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Taunt|98|<|Mob

[Heals]
HealsOn=1
HealsSize=5
Heals1=Light Healing|75
AutoRezOn=0
AutoRezWith=Your Rez Item/AA/Spell
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Cure Poison|Poison
Cures2=Cure Disease|Disease
CuresCOn=1

[Burn]
BurnSize=5
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Light Healing
Gem2=Center
Gem3=Holy Armor
Gem4=Yaulp
Gem5=Reckless Strength
Gem6=Desist
Gem7=Cure Disease
Gem8=Cure Poison
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL
