; Source class template: UltimateEQAssist_L25_WAR.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=0

[Buffs]
BuffsOn=1
BuffsSize=2
Buffs1=Focused Will Discipline|60|cond1
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
BuffsCOn=1

[Burn]
BurnSize=2
BurnAllNamed=0

[Aggro]
AggroOn=1
AggroSize=3
Aggro1=Taunt|100|<
Aggro2=Provoke|75|<

[Heals]
HealsOn=1
HealsSize=2
Heals1=NULL
HealsCOn=1

[KConditions]
ConOn=1
CondSize=2
Cond1=${Me.CombatState.NotEqual[COMBAT]} && ${Me.PctHPs} < 90
Cond2=TRUE

[DPS]
DPSOn=1
DPSCOn=1

[Cures]
CuresOn=1
CuresCOn=1
