; KAHybrid Source: L25 - Lvl 25 WIZ ini w/o conditions for KA11 | https://www.redguides.com/community/resources/lvl-25-wiz-ini-w-o-conditions-for-ka11.935/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_WIZ.ini

[General]
KissAssistVer=11.000
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Major Shielding
Buffs2=Leatherskin
Buffs3=Minor Familiar
Buffs4=O`Keil's Levity
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=3
AERadius=50
AE1=Cast Force|2|mob
AE2=Column of Lightning|3|mob

[DPS]
DPSOn=1
DPSSize=5
DPSSkip=20
DPSInterval=2
DPS1=Frost Shock|90
DebuffAllOn=0
DPSCOn=1

[Burn]
BurnSize=3
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[MySpells]
Gem1=Frost Shock
Gem2=Fire Bolt
Gem3=Cast Force
Gem4=Column of Lightning
Gem5=Major Shielding
Gem6=Lesser Evacuate
Gem7=Gate

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
