; KAHybrid Source: L25 - Lvl 25 SHM ini w/o conditions for KA11 | https://www.redguides.com/community/resources/lvl-25-shm-ini-w-o-conditions-for-ka11.998/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_SHM.ini

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=11
Buffs1=Cannibalize|mana|90|20
Buffs2=Spirit Strength
Buffs3=Rising Dexterity|ma
Buffs4=Spirit of Cat|ma
Buffs5=Protect
Buffs6=Spirit of Wolf
Buffs7=Spirit of Ox|ma
Buffs8=Regeneration
Buffs9=Form of the Bear
Buffs10=Frenzy
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=6
DPSSkip=20
DPSInterval=2
DPS1=Drowsy|95
DPS2=Walking Sleep|90
DPS3=Affliction|85
DPS4=Envenomed Breath|80
DPS5=Frost Strike|20
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=2
Heals1=Healing|55
AutoRezOn=0
AutoRezWith=Your Primary Rez Item/AA/Spell
HealsCOn=1

[Burn]
BurnSize=3
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[MySpells]
Gem1=Healing
Gem2=Malaise
Gem3=Drowsy
Gem4=Envenomed Breath
Gem5=Cannibalize
Gem6=Walking Sleep
Gem7=Affliction
Gem8=Frost Strike

[Cures]
CuresOn=0
CuresCOn=0
