; KAHybrid Source: L25 - Lvl 25 BRD ini w/o conditions | https://www.redguides.com/community/resources/lvl-25-brd-ini-w-o-conditions.1543/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_BRD.ini

[General]
KissAssistVer=12.001
TwistOn=1
TwistMed=8
TwistWhat=3 7
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Melee]
MeleeTwistOn=1
MeleeTwistWhat=1 5

[DPS]
DPSOn=1
DPSSize=5
DPSSkip=20
DPSInterval=2
DPS1=Brusco's Boastful Bellow|90
DPS2=Selo's Consonant Chain|85
DebuffAllOn=0
DPSCOn=1

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=5
MezMaxLevel=30
MezStopHPs=80
MezSpell=Kelin's Lucid Lullaby
MezAESpell=Your AE Mez Spell|0

[Burn]
BurnSize=5
BurnAllNamed=0

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Chant of Battle
Gem2=Brusco's Boastful Bellow
Gem3=Selo's Accelerando
Gem4=Selo's Consonant Chain
Gem5=Anthem de Arms
Gem6=Kelin's Lucid Lullaby
Gem7=Hymn of Restoration
Gem8=Cassindra's Chant of Clarity
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Buffs]
BuffsOn=0
BuffsCOn=0

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
