; KAHybrid Source: L25 - Lvl 25 ENC ini - TLP | https://www.redguides.com/community/resources/lvl-25-enc-ini-tlp.1827/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_ENC.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Major Shielding
Buffs2=Strengthen
Buffs3=Cloud|ma
Buffs4=Rune II
Buffs5=Alacrity|melee
Buffs6=Breeze|caster
Buffs7=Berserker Strength|melee
Buffs8=Feedback|melee
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Color Shift|4

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Ebbing Strength|98
DPS2=Tashina|96
DPS3=Listless Power|94
DPS4=Languid Pace|92
DPS5=Choke|92
DPS6=Whirl Till you Hurl|90
DPS7=Sanity Warp|88
DebuffAllOn=0
DPSCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Sisna's Animation
PetBuffsOn=0
PetBuffsSize=8
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=10
MezMaxLevel=55
MezStopHPs=80
MezSpell=Enthrall
MezAESpell=Mesmerization|3

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Choke
Gem2=Tashani
Gem3=Whirl Till You Hurl
Gem4=Sanity Warp
Gem5=Listless Power
Gem6=Enthrall
Gem7=Mesmerization
Gem8=Languid Pace

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
