; KAHybrid Source: L25 - Lvl 25 RNG ini - TLP | https://www.redguides.com/community/resources/lvl-25-rng-ini-tlp.1845/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_RNG.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Skin Like Rock
Buffs2=Feet Like Cat
Buffs3=Thistlecoat
Buffs4=Firefist
Buffs5=Shield of Thistles
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Invoke Lightning|4

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Ignite|98
DPS2=Stinging Swarm|97
DPS20=Snare|30
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Minor Healing|50
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Cure Poison|Poison
Cures2=Cure Disease|Disease
CuresCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Minor Healing
Gem2=Invoke Lightning
Gem3=Snare
Gem4=Skin like Wood
Gem5=Stinging Swarm
Gem6=Burst of Fire
Gem7=Thistlecoat
Gem8=Shield of Thistles
