; KAHybrid Source: L75 - Work in Progress - Level 75 Monk Mainly solo/molo oriented | https://www.redguides.com/community/resources/level-75-monk-mainly-solo-molo-oriented.2575/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_MNK.ini

[General]
KissAssistVer=12.002
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=4
Buffs1=Master's Aura|Aura
Buffs2=Gifilnos' Prized Hunting Bag|dual|Shadow of Endurance|Me
Buffs3=Familiar of the Girplan Guardian|dual|Summon Familiar: Girplan|Me
Buffs4=Moment of Calm|End|50
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Impenetrable Discipline|3
AE2=Hundred Fists Discipline|3
AE3=Ashenhand Discipline|3
AE4=Armor of Experience|3
AE5=Speed Focus Discipline|3
AE6=Counterforce Discipline|3
AE7=Heel of Kanji|3

[DPS]
DPSOn=1
DPSSize=23
DPSSkip=0
DPSInterval=2
DPS1=Fists of Wu|99|Cond9
DPS2=Dragon Fang|99|Mash
DPS3=Flying Kick|99|Mash
DPS4=Elbow Strike|99|Mash
DPS5=Tail Rake|99|Mash
DPS6=Eagle Strike|99|Mash
DPS7=Tiger Claw|99|Mash
DPS8=Disarm|99|Mash
DPS9=Round Kick|99|Mash
DPS10=Kick|99|Mash
DPS11=Leopard Claw|99|Mash
DPS12=Speed Focus Discipline|99|cond4
DPS13=Impenetrable Discipline|99|cond4
DPS14=Counterforce Discipline|99|cond4
DPS15=Heel of Kanji|99|cond4
DPS18=Hundred Fists Discipline|99|cond4
DPS19=Ashenhand Discipline|99|cond4
DPS20=feign death|99|cond2
DPS21=feign death|99|cond5
DPS22=Silentfist Discipline|99|cond4
DPS23=Armor of Experience|99|cond4
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Mend|40|tap
Heals2=Focused Will Discipline|30|Me|Cond6
Heals3=Healing Will Discipline|20|Me|Cond7
Heals4=Staunch Recovery|10|tap
Heals5=Imitate Death|8
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=1
Cures1=Purify Body
CuresCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[KConditions]
ConOn=1
CondSize=9
Cond1=${Me.XTarget} >= 3 && ${Me.PctHPs} <= 30
Cond2=${Me.PctHPs} <= 30 && ${Target.PctHPs} >= ${Me.PctHPs}
Cond3=${Me.XTarget} == 0 && ${Me.PctHPs} <= 99 && !${Me.Sitting}
Cond4=${Math.Calc[(${Spawn[${Me.XTarget[1]}].Level}+${Spawn[${Me.XTarget[2]}].Level}+${Spawn[${Me.XTarget[3]}].Level}+${Spawn[${Me.XTarget[4]}].Level}+${Spawn[${Me.XTarget[5]}].Level}+${Spawn[${Me.XTarget[6]}].Level}) / ${Me.XTarget}]} >= (${Math.Calc[(${Me.Level}+${Group.Member[1].Level}+${Group.Member[2].Level}+${Group.Member[3].Level}+${Group.Member[4].Level}+${Group.Member[5].Level}) / (${Group.Members}+1)]})
Cond5=${Math.Calc[(${Me.Level}+${Group.Member[1].Level}+${Group.Member[2].Level}+${Group.Member[3].Level}+${Group.Member[4].Level}+${Group.Member[5].Level}) * 2.1]}<=(${Math.Calc[(${Spawn[${Me.XTarget[1]}].Level}+${Spawn[${Me.XTarget[2]}].Level}+${Spawn[${Me.XTarget[3]}].Level}+${Spawn[${Me.XTarget[4]}].Level}+${Spawn[${Me.XTarget[5]}].Level}+${Spawn[${Me.XTarget[6]}].Level})]})
Cond6=${Me.XTarget} == 0 && ${Me.PctHPs} <= 30 && ${Me.Sitting} && ${Me.CombatAbilityReady[Focused Will Discipline]}
Cond7=${Me.XTarget} == 0 && ${Me.PctHPs} <= 20 && ${Me.Sitting} && ${Me.CombatAbilityReady[Healing Will Discipline]}
Cond8=${Me.XTarget} != 0
Cond9=!${Me.Song[Fists of Wu].ID}
