; KAHybrid Source: L25 - Lvl 25 DRU ini w/o conditions for KA11 | https://www.redguides.com/community/resources/lvl-25-dru-ini-w-o-conditions-for-ka11.1348/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_DRU.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=7
Buffs1=Skin like Steel
Buffs2=Firefist
Buffs3=Shield of Barbs
Buffs4=Spirit of Wolf
Buffs5=Barbcoat
Buffs6=Wolf Form
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Pogonip|4

[DPS]
DPSOn=1
DPSSize=4
DPSSkip=5
DPSInterval=2
DPS1=Careless Lightning|95|Once
DPS2=Creeping Crud|85
DPS3=Snare|30
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=2
Heals1=Healing|50
AutoRezOn=0
HealsCOn=1

[Burn]
BurnSize=1
BurnAllNamed=0

[GoM]
GoMSize=1

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Careless Lightning
Gem2=Healing
Gem3=Creeping Crud
Gem4=Barbcoat
Gem5=Pogonip
Gem6=Shield of Barbs
Gem7=Snare
Gem8=Skin like Steel
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
