; KAHybrid Source: L75 - Work in Progress - 75 Warrior (TLP) | https://www.redguides.com/community/resources/75-warrior-tlp.1299/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L75_WAR.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Champion's Aura|Aura|Cond15
Buffs2=Second Wind|End|40
RebuffOn=1
CheckBuffsTimer=30
BuffsCOn=1

[AE]
AEOn=1
AESize=25
AERadius=50
AE1=Vortex Blade Rk. II|90|Cond14
AE2=Area Taunt|99|Cond5

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=1
DPSInterval=2
DPS1=Final Stand Discipline Rk. II|100|Cond1
DPS2=Fortitude Discipline|20|Me|Cond2
DPS3=Disarm|99|Mash
DPS4=Brutal Onslaught Discipline|95|Cond3
DPS5=Taunt|100|Cond4
DPS6=Command:/stand|100|Cond16
DPS7=Bazu Bellow|98|Cond6
DPS8=Mock|97|Cond7
DPS9=Fellstrike Discipline|80|Cond8
DPS10=Aura of Draconic Runes Rk. II|60|Cond9
DPS11=Shocking Defense Discipline|85|Cond10
DPS12=Incite|95|Cond11
DPS13=Commanding Voice|75|Cond12
DPS14=Call of Challenge|35|Cond13
DPS15=Champion's Sword of Eternal Power|50|Cond17
DPS16=Throat Jab RK. II|90|Mash
DPS17=Scowl Rk. II|99|Cond18
DPS18=Battle Leap|92|cond19
DPS19=Bash|99|mash
DPS20=Grappling Strike|99|Cond20
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Warlord's Tenacity|15|Me
Heals2=Mark of the Mage Hunter|30
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[KConditions]
ConOn=1
CondSize=20
Cond1=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]} || ${Me.Combat} && ${Me.PctHPs}<20
Cond2=${Me.Combat} && ${Me.PctHPs}<20
Cond3=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond4=${Me.Combat} && !${Me.TargetOfTarget.CleanName.Equal[${Me.CleanName}]} && ${Me.AbilityReady[Taunt]}
Cond5=${Me.Combat} && !${Me.TargetOfTarget.CleanName.Equal[${Me.CleanName}]} && ${SpawnCount[npc radius 50]}>5
Cond6=${Me.Combat} && !${Me.TargetOfTarget.CleanName.Equal[${Me.CleanName}]} && ${Me.CombatAbilityReady[Bazu Bellow]} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]}
Cond7=${Me.Combat} && !${Me.TargetOfTarget.CleanName.Equal[${Me.CleanName}]} && ${Me.CombatAbilityReady[Mock]} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]}
Cond8=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond9=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond10=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond11=${Me.Combat} && !${Me.TargetOfTarget.CleanName.Equal[${Me.CleanName}]} && ${Me.AbilityReady[Incite]} && ${Me.XTarget[1].Level}<${Math.Calc[${Me.Level}-4]}
Cond12=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond13=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond14=${Me.Combat} && !${Me.TargetOfTarget.CleanName.Equal[${Me.CleanName}]} && ${SpawnCount[npc radius 50]}>3
Cond15=!${Me.Song[Champion's Aura].ID}
Cond16=${Me.Feigning}
Cond17=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond18=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond19=!${Me.Song[Battle Leap].ID} && ${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || !${Me.Song[Battle Leap].ID} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond20=${Target.Distance} > 15 && ${Target.Distance} < 25

[Cures]
CuresOn=1
CuresCOn=1
