; KAHybrid Source: L25 - Lvl 25 WAR ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-25-war-ini-w-conditions-for-ka11.1070/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_WAR.ini

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=0

[Buffs]
BuffsOn=1
BuffsSize=2
Buffs1=Focused Will Discipline|60|cond1
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
BuffsCOn=1

[Burn]
BurnSize=2
BurnAllNamed=0

[Aggro]
AggroOn=1
AggroSize=3
Aggro1=Taunt|100|<
Aggro2=Provoke|75|<

[Heals]
HealsOn=1
HealsSize=2
Heals1=NULL
HealsCOn=1

[KConditions]
ConOn=1
CondSize=2
Cond1=${Me.CombatState.NotEqual[COMBAT]} && ${Me.PctHPs} < 90
Cond2=TRUE

[DPS]
DPSOn=1
DPSCOn=1

[Cures]
CuresOn=1
CuresCOn=1
