; KAHybrid Source: L25 - Beastlord - Level 25 - Maximum effort! | https://www.redguides.com/community/resources/beastlord-level-25-maximum-effort.2720/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L25_BST.ini

[General]
KissAssistVer=12.002
CharInfo=Beastlord|25|FREE
Role=Assist
CampRadius=35
CampRadiusExceed=400
ReturnToCamp=1
ChaseAssist=0
ChaseDistance=25
CampfireOn=0
MedOn=1
MedStart=30
MedStop=100
MedCombat=0
RezAcceptOn=1|0
AcceptInvitesOn=1
GroupWatchOn=0
GroupWatchCheck=FALSE
CorpseRecoveryOn=0
EQBCOn=0
DanNetOn=1
ScatterOn=1
LOSBeforeCombat=1
BuffWhileChasing=1
CastRetries=3
ReturnToCampAccuracy=10

[Buffs]
BuffsOn=1
BuffsSize=13
Buffs1=NULL
Buffs2=command:/useitem Worn Totem|Dual|Blessing of Swiftness|Cond17
Buffs3=command:/notify AlertWnd ALW_Dismiss_Button leftmouseup
Buffs4=Scale Skin|Cond6
Buffs5=Inner Fire|Cond7
Buffs6=Strengthen|Cond8
Buffs7=Spirit of Bear|Cond9
Buffs8=Endure Cold|Cond10
Buffs9=Endure Fire|Cond11
Buffs10=Endure Poison|Cond12
Buffs11=Endure Disease|Cond13
Buffs12=Spirit of Wolf|Cond15
Buffs13=Shrink|Cond16
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=4
DPSSkip=20
DPSInterval=2
DPS1=Kick|97|Mash
DPS2=Fleeting Fury|98|ME|Cond14
DPS3=Tainted Breath|95
DPS4=Blast of Frost|80
DebuffAllOn=0
DPSCOn=1

[Melee]
AssistAt=98
MeleeOn=1
FaceMobOn=2
MeleeDistance=60
StickHow=!front delaystrafe loose uw
AutoFireOn=0
UseMQ2Melee=0
TargetSwitchingOn=0
PetTauntOverride=0

[Heals]
HealsOn=1
HealsSize=2
Heals1=Keshuval's Rejuvenation|70|Pet
Heals2=Light Healing|40
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=2
Cures1=Cure Disease|Disease
Cures2=Cure Poison|Poison
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Spirit of Keshuval
PetShrinkOn=1
PetShrinkSpell=Tiny Companion
PetBuffsOn=1
PetBuffsSize=5
PetBuffs1=Spirit of the Blizzard
PetBuffs2=Scale Skin|Cond6
PetBuffs3=Inner Fire|Cond7
PetBuffs4=Strengthen|Cond8
PetBuffs5=Spirit of Bear|Cond9
PetAssistAt=95
PetAttackDistance=115
PetRampPullWait=1
PetSuspend=1
MoveWhenHit=1
PetForceHealOnMed=1

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=1
Burn1=Intensity of the Resolute

[KConditions]
ConOn=1
CondSize=17
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.ConColor.Equal[White]} || ${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]}
Cond4=${Target.Named} && (${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]})
Cond5=${Me.GroupAssistTarget.Named}
Cond6=!(${Target.Buff[Scale Skin].ID} || ${Target.Buff[Holy Armor].ID}) && ${Spell[Scale Skin].StacksTarget}
Cond7=!${Target.Buff[Inner Fire].ID} && ${Spell[Inner Fire].StacksTarget}
Cond8=!(${Target.Buff[Strengthen].ID} || ${Target.Buff[Talisman of the Beast].ID}) && ${Spell[Strengthen].StacksTarget}
Cond9=!${Target.Buff[Spirit of Bear].ID} && ${Spell[Spirit of Bear].StacksTarget}
Cond10=!${Target.Buff[Endure Cold].ID} && ${Spell[Endure Cold].StacksTarget}
Cond11=!${Target.Buff[Endure Fire].ID} && ${Spell[Endure Fire].StacksTarget}
Cond12=!${Target.Buff[Endure Poison].ID} && ${Spell[Endure Poison].StacksTarget}
Cond13=!${Target.Buff[Endure Disease].ID} && ${Spell[Endure Disease].StacksTarget}
Cond14=!${Target.Buff[Fleeting Fury].ID} && ${Spell[Fleeting Fury].StacksTarget}
Cond15=!${Target.Buff[Spirit of Wolf].ID} && ${Spell[Spirit of Wolf].StacksTarget}
Cond16=${Target.Height} > 1.91
Cond17=!${Me.Buff[Blessing of Swiftness].ID} && ${Spell[Blessing of Swiftness].Stacks}

[SpellSet]
LoadSpellSet=2

[Spells]
Gem1=Tainted Breath
Gem2=Blast of Frost
Gem3=Cure Disease
Gem4=Cure Poison
Gem5=Fleeting Fury
Gem6=Keshuval's Rejuvenation
Gem7=Light Healing
Gem8=Spirit of Keshuval
