; Source class template: UltimateEQAssist_DRU.ini
; Generated: 2026-03-10

[General]
KissAssistVer=11.005

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=7
Buffs1=Skin like Steel
Buffs2=Firefist
Buffs3=Shield of Barbs
Buffs4=Spirit of Wolf
Buffs5=Barbcoat
Buffs6=Wolf Form
RebuffOn=1
CheckBuffsTimer=10

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Pogonip|4

[DPS]
DPSOn=1
DPSSize=4
DPSSkip=5
DPSInterval=2
DPS1=Careless Lightning|95|Once
DPS2=Creeping Crud|85
DPS3=Snare|30
DebuffAllOn=0

[Heals]
HealsOn=1
HealsSize=2
Heals1=Healing|50
AutoRezOn=0

[Burn]
BurnSize=1
BurnAllNamed=0

[GoM]
GoMSize=1

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Careless Lightning
Gem2=Healing
Gem3=Creeping Crud
Gem4=Barbcoat
Gem5=Pogonip
Gem6=Shield of Barbs
Gem7=Snare
Gem8=Skin like Steel
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL
