; Source class template: UltimateEQAssist_WAR.ini
; Generated: 2026-03-10

[General]
KissAssistVer=11.001

[SpellSet]
LoadSpellSet=0

[Buffs]
BuffsOn=1
BuffsSize=2
Buffs1=Focused Will Discipline|60|cond1
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

[Burn]
BurnSize=2
BurnAllNamed=0

[Aggro]
AggroOn=1
AggroSize=3
Aggro1=Taunt|100|<
Aggro2=Provoke|75|<

[Heals]
HealsOn=0
HealsSize=2
Heals1=NULL

[KConditions]
ConOn=1
CondSize=2
Cond1=${Me.CombatState.NotEqual[COMBAT]} && ${Me.PctHPs} < 90
Cond2=TRUE
