; Source class template: UltimateEQAssist_L80_MNK.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Monk|80|GOLD
ChaseAssist=1
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=3|60|PAL,ENC,SHM,CLR
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=0
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=0
SwitchWithMA=0
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0

[SpellSet]
LoadSpellSet=0
SpellSetName=MuleAssist

[Buffs]
# Note item, AA, spell, or disc information
# Order should be permanent > instant > longest to shortest duration
# Order tiebreakers by shorted to longest cooldown if needed
# Explain conditions
BegHelp=Spellname|alias1,alias 2,alias 3 etc
BegPermissionHelp=Valid options are |raid |guild |fellowship |all |tell |group
BuffsOn=1
BegOn=0
BuffsCOn=1
RebuffOn=0
CheckBuffsTimer=10
PowerSource=NULL
BuffCacheingDelay=300
BegPermission=NULL
BuffsSize=1
BegSize=0

# Discipline | permanent
Buffs1=Master's Aura|aura
BuffsCond1=TRUE

[Melee]
MeleeOn=1
MeleeTwistOn=0
FaceMobOn=1
AutoFireOn=0
AssistAt=100
MeleeDistance=75
StickHow=behind 10
UseMQ2Melee=0
DismountDuringFights=0
BeforeCombat=Cast Before Melee Disc
TankAllMobs=FALSE
MeleeTwistWhat=DPS twist order here

[GMail]
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0
GMailSize=0

[AE]
AEOn=0
AERadius=50
AESize=0

[DPS]
DPSOn=1
DPSCOn=1
DebuffAllOn=0
DPSSkip=0
DPSInterval=0
StayAwayToCast=0

DPSSize=13

# Item
DPS1=Fiercehand Shroud of the Focused|100
DPSCond1=${Target.Buff.Beneficial}

# Item
# Only use if target has beneficial buffs and Fiercehand Shroud of the Focused is not ready
DPS2=Mist-Blessed Leather Tunic|99
DPSCond2=${Target.Buff.Beneficial} && !${Me.ItemReady[Fiercehand Shroud of the Focused]}

# Skill
DPS3=Tiger Claw|98|mash
DPSCond3=TRUE

# Skill
DPS4=Flying Kick|97|mash
DPSCond4=TRUE

# Combat Ability
DPS5=Fists of Wu|96|mash
DPSCond5=${Me.PctEndurance} > ${Target.PctHPs}

# Combat Ability
DPS6=Wheel of Fists Rk. II|95|mash
DPSCond6=${Me.PctEndurance} > ${Target.PctHPs}

# Only use if fighting a named | 1min duration/30min recast
DPS7=Scaledfist Discipline Rk. II|94
DPSCond7=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 30sec duration/3min recast
DPS8=Transcended Fistwraps of Immortality|93|mash
DPSCond8=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 30sec duration/15 min recast
DPS9=Rapid Kick Discipline|92
DPSCond9=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 30sec duration/22min recast
DPS10=Speed Focus Discipline|91
DPSCond10=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 30sec duration/22min recast
DPS11=Crystalpalm Discipline Rk. II|90
DPSCond11=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if Crystalpalm Discipline active | 30sec duration/60min recast
DPS12=Focused Destructive Force|89
DPSCond12=${Me.ActiveDisc.Name.Equal[Crystalpalm]}

DPS13=Purified Chromahide Tunic|88
DPSCond13=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierPull=Blunt
BandolierSize=2
Bandolier1=Blunt
BandolierCond1=!${Target.Named} || !${Me.CombatAbilityReady[Innerflame Discipline]}
Bandolier2=Epic
BandolierCond2=${Target.Named} && ${Me.CombatAbilityReady[Innerflame Discipline]}

[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=9

# Only use if health under 50% | 3min refresh
OhShit1=Imitate Death|
OhShitCond1=${Me.PctHPs} < 35

# Only use if health under 50%
OhShit2=Feign Death|
OhShitCond2=${Me.PctHPs} < 40

# Only use if health under 50% | 12sec duration / 4min reuse
OhShit3=Impenetrable Discipline|
OhShitCond3=${Me.PctHPs} < 45

# Only use if health under 50% | 30sec duration / 10min reuse
OhShit4=Delay Death|
OhShitCond4=${Me.PctHPs} < 50

# Only use if health under 50% | 1min duration / 15min reuse
OhShit5=Counterforce Discipline|
OhShitCond5=${Me.PctHPs} < 55

# Only use if health under 50%
OhShit6=Mend|
OhShitCond6=${Me.PctHPs} < 60

# Only use if I'm feigning and my health is over 75%
OhShit7=command:/stand on|
OhShitCond7=${Me.Feigning} && (${Me.PctHPs} > 75)

# Only use if endurance under 50% | 12sec duration / 20min reuse
OhShit8=Moment of Tranquility|
OhShitCond8=${Me.PctEndurance} < 45

# Only use if endurance under 50% | 2min duration / 36min reuse
OhShit9=Third Wind Rk. II|
OhShitCond9=${Me.PctEndurance} < 50

[Aggro]
AggroOn=0
AggroCOn=0
AggroSize=0


[Pull]
PullTwistOn=0
PullMeleeStick=0
MaxRadius=400
MaxZRange=50
CheckForMemblurredMobsInCamp=1
PullWait=6
PullCond=TRUE
PrePullCond=TRUE
PullRoleToggle=0
ChainPull=0
ChainPullHP=20
ChainPullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullNamedsFirst=0
ActNatural=1
UseCalm=0

CalmRadius=50
GrabDeadGroupMembers=1
UseWayPointZ=0

PullWith=Fiercehand Shroud of the Focused
CalmWith=NULL

[Heals]
# Note item, AA, spell, or disc information
# Ordered by lowest health to highest health
# Explain conditions
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=0
HealsCOn=0
HealGroupPetsOn=0
InterruptHeals=100
XTarHeal=0
HealsSize=0

[Cures]
CuresOn=1
CuresSize=1
# Only use if in combat
Cures1=Purify Body
CuresCond1=${Me.CombatState.Equal[Combat]}

CuresCOn=1
[Pet]
PetOn=0
PetBehind=TRUE
PetBuffsSize=0

[Burn]
BurnCOn=0
BurnText=Burn this
BurnAllNamed=0
UseTribute=0
BurnSize=0

[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0

[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92

