; Source class template: UltimateEQAssist_L80_ENC.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=35
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Enchanter|80|GOLD
ChaseAssist=0
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=0
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=1
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=6
SwitchWithMA=FALSE
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0

[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist

[Buffs]
# Note item, AA, spell, or disc information
# Order should be permanent > instant > longest to shortest duration
# Order tiebreakers by shorted to longest cooldown if needed
# Explain conditions
BuffsOn=1
BuffsCOn=1
RebuffOn=1
BuffCacheingDelay=300
CheckBuffsTimer=10
PowerSource=NULL
BegOn=1
BegSize=0
BegPermissionHelp=Valid options are |raid |guild |fellowship |all |tell |group
BegPermission=|raid|guild|tell|group
BegHelp=Spellname|alias1,alias 2,alias 3 etc

BuffsSize=14

# Auras > Combat Innates | permanent
Buffs1=Mana Resurgence Aura Rk. II|aura
BuffsCond1=TRUE

# Class AA | instant (5min refresh)
# Only use if I don't have a Sanguine Mind Crystal
Buffs2=Sanguine Mind Crystal
BuffsCond2=!${FindItemCount[Sanguine Mind Crystal]}

# Class AA | instant (5min refresh)
# Only use if I don't have an Azure Mind Crystal
Buffs3=Azure Mind Crystal
BuffsCond3=!${FindItemCount[Azure Mind Crystal]}

# https://everquest.allakhazam.com/db/item.html?item=66218 | instant (5min recast)
Buffs4=Azure Mind Crystal I|mana|60
BuffsCond4=TRUE

# Class AA | instant (100min refresh)
Buffs5=Gather Mana|mana|10
BuffsCond5=TRUE

# Utility Beneficial > Rune | 110min duration
Buffs6=Opalescent Rune Rk. II
BuffsCond6=TRUE

# HP Buffs > Shielding | 90min duration
Buffs7=Spellbound Shield Rk. II
BuffsCond7=TRUE

# Regen > Mana | 80min duration
Buffs8=Seer's of Cognizance Rk. II|caster
BuffsCond8=TRUE

# Utility Beneficial > Rune | 42min duration
Buffs9=Multichromatic Rune Rk. II
BuffsCond9=TRUE

# Utility Beneficial > Haste | 42min duration
Buffs10=Hastening of Erradien|melee
BuffsCond10=TRUE

# Class AA | 36min duration
Buffs11=Veil of Mindshadow
BuffsCond11=TRUE

# https://everquest.allakhazam.com/db/item.html?item=6802 | 15min duration
Buffs12=Earring of Blazing Energy
BuffsCond12=TRUE

# Utility Beneficial > Combat Innates | 10min duration
Buffs13=Ward of Mystifying Rk. II
BuffsCond13=TRUE

# Utility Beneficial > Rune | 7min duration
Buffs14=Brimstone Tenement Rk. II
BuffsCond14=TRUE

[Melee]
MeleeOn=0
AssistAt=100
FaceMobOn=1
MeleeDistance=75
StickHow=behind 10
AutoFireOn=0
UseMQ2Melee=0
DismountDuringFights=0
BeforeCombat=Cast Before Melee Disc
TankAllMobs=FALSE

[GoM]
GoMOn=1
GoMCOn=0
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMSize=0

[GMail]
GMailOn=0
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailSize=0

[AE]
AEOn=0
AESize=0
AERadius=50

[DPS]
DPSOn=1
DPSCOn=1
DPSSkip=0
DPSInterval=0
DebuffAllOn=2
StayAwayToCast=FALSE
DPSSize=5

DPS1=Din of Tashan Rk|100|debuffall|tash
DPSCond1=TRUE

DPS2=Desolate Deeds|99|slow
DPSCond2=TRUE

DPS3=Shattered Consciousness|98
DPSCond3=TRUE

DPS4=Dreamer's Kaleidosilk Robe|97
DPSCond4=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if mana level is higher that target's health level
DPS5=Multichromatic Assault|96
DPSCond5=${Me.PctMana} > ${Target.PctHPs}

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierSize=0
BandolierPull=Blunt

[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=10

## Alternate Abilities

# Only use if my health is under 50% and I'm not buffed with Draconic Rune
OhShit1=Eldritch Rune|
OhShitCond1=${Me.PctHPs} < 50 && !${Me.Buff[Opalescent Rune Rk. II].ID}

# Only use if my health is under 50% and my target is targeting me
OhShit2=Doppelganger|Mob
OhShitCond2=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Only use if my health is under 50%
OhShit3=Mind Over Matter|
OhShitCond3=${Me.PctHPs} < 50

# Only use if my health is under 50%
OhShit4=Dimensional Shield|
OhShitCond4=${Me.PctHPs} < 50

# Only use if my health is under 50% and my target is targeting me
OhShit5=Arcane Whisper|Mob
OhShitCond5=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Only use if my health is under 50% and my target is targeting me
OhShit6=Beguiler's Directed Banishment|Mob
OhShitCond6=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Only use if my health is under 50%
OhShit7=Beguiler's Banishment|
OhShitCond7=${Me.PctHPs} < 50

# Only use if my health is under 50% and my target is targeting me
OhShit8=Noctambulate|Mob
OhShitCond8=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Only use if my health is under 50%
OhShit9=Silent Casting|
OhShitCond9=${Me.PctHPs} < 50

## Items

# Only use if my health is under 50%
OhShit10=Sanguine Mind Crystal I|
OhShitCond10=${Me.PctHPs} < 50

[Aggro]
AggroOn=0
AggroCOn=0
AggroSize=0

[Pull]
PullWith=Echo of Tashan
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
CheckForMemblurredMobsInCamp=0
PullWait=5
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
ChainPullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullNamedsFirst=0
ActNatural=1
UseCalm=0
CalmWith=Harmony
GrabDeadGroupMembers=1
PullCond=TRUE
PrePullCond=TRUE
CalmRadius=50

[Heals]
# Note item, AA, spell, or disc information
# Ordered by lowest health to highest health
# Explain conditions
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=0
HealsCOn=0
HealGroupPetsOn=0
InterruptHeals=100
HealsSize=0
XTarHeal=0

[Cures]
CuresOn=0
CuresSize=0

CuresCOn=0
[Pet]
PetOn=1
PetShrinkOn=1
PetBuffsOn=1
PetCombatOn=1
PetHoldOn=1
PetBuffsSize=0
PetAssistAt=95
PetToysSize=6
PetBreakMezSpell=NULL
PetRampPullWait=0
PetSuspend=0
MoveWhenHit=0
PetForceHealOnMed=0

PetToysGave=
PetBehind=TRUE

PetSpell=Erradien's Animation
PetShrinkSpell=Tiny Companion

[Mez]
MezOn=1
MezRadius=100
MezMinLevel=1
MezMaxLevel=83
MezStopHPs=1

MezSpell=Mystify
MezAESpell=Quelling Wave Rk. II|2

[Burn]
BurnCOn=0
BurnText=Burn this
BurnAllNamed=0
UseTribute=0
BurnSize=0

[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0

[Merc]
MercOn=0
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercAssistAt=92

