; KAHybrid Source: L70 - Lvl 70 NEC ini w/conditions | https://www.redguides.com/community/resources/lvl-70-nec-ini-w-conditions.1570/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_NEC.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Shadow Guard
Buffs2=Grim Aura
Buffs3=Grave Pact
Buffs4=Banshee Aura
Buffs5=Dull Pain
Buffs6=Vampiric Embrace
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Scent of Midnight|95
DPS2=Chill Bones|90
DPS3=Call for Blood|85
DPS4=Desolate Undead|80
DPS5=Dread Pyre|75
DPS6=Fang of Death|70
DPS7=Soulspike|65
DPS8=Crippling Claudication|60
DPS9=Mind Flay|60
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Touch of Death|80
Heals2=Mend Companion|50|pet
Heals3=Harmshield|20
Heals4=Death Peace|10
AutoRezOn=0
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Child of Bertoxxulous
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Rune of Death
PetBuffs2=Form of Mottled Bone
PetBuffs3=Protection of Calliav
PetRampPullWait=0
PetSuspend=1
PetForceHealOnMed=0

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Silent Casting
Burn2=Encroaching Darkness
Burn3=Swarm of Decay
Burn4=Wake the Dead
Burn5=Life Burn

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=5
Cond1=${Target.Body.Name.Equal[Undead]} && ${Me.XTarget}>4
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Chill Bones
Gem2=Call for Blood
Gem3=Desolate Undead
Gem4=Dread Pyre
Gem5=Fang of Death
Gem6=Soulspike
Gem7=Mind Flay
Gem8=Crippling Claudication
Gem9=Scent of Midnight
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
