; KAHybrid Source: L70 - Lvl 70 SHD ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-70-shd-ini-w-conditions-for-ka11.895/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_SHD.ini

[General]
KissAssistVer=11.010 Beta
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=8
Buffs1=Voice of Thule|MA
Buffs2=Shroud of Discord
Buffs3=Cloak of Discord
Buffs4=Grim Aura
Buffs5=Rod of Mystical Transvergence|Mana|30|60
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=3
AERadius=50

[DPS]
DPSOn=1
DPSSize=11
DPSSkip=20
DPSInterval=2
DPS1=Festering Darkness|95
DPS2=Aura of Hate|90
DPS3=Terror of Thule|85
DPS4=Dark Constriction|80
DPS5=Spear of Muram|75
DPS6=Ignite Blood|70
DPS7=Blood of Inruku|55
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=4
Aggro1=Terror of Discord
Aggro2=Dread Gaze

[Heals]
HealsOn=1
HealsSize=5
Heals1=Touch of Draygun|80|weave
Heals2=Touch of the Devourer|80|weave
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=1
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Son of Decay
PetBuffsOn=1
PetBuffsSize=2
PetBuffs1=Rune of Decay
PetRampPullWait=0
PetSuspend=1
PetForceHealOnMed=0

[Burn]
BurnSize=9
BurnAllNamed=1
Burn1=Deflection Discipline|mob|cond1
Burn2=Soul Guard|mob|cond5
Burn3=Leechcurse Discipline|mob|cond4
Burn4=Leech Touch|mob|cond2
Burn5=Terror of Discord|mob
Burn6=Harmshield|mob|cond3
Burn7=Soul Shield|mob|cond6
Burn8=Ichor Guard|mob|cond8

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=7
Cond1=${Me.CombatAbilityReady[Deflection Discipline]} && ${Me.Inventory[14].Type.Equal[Shield]} && !${Me.ActiveDisc.ID}
Cond2=${Me.AltAbilityReady[Leech Touch]} && ${Target.Type.Equal[NPC]} && ${Me.PctHPs} < 40
Cond3=${Me.AltAbilityReady[Harmshield]} && ${Target.Type.Equal[NPC]} && ${Me.PctHPs} < 20
Cond4=${Me.CombatAbilityReady[Leechcurse Discipline]} && !${Me.ActiveDisc.ID}
Cond5=${Me.CombatAbilityReady[Soul Guard]}  && !${Me.ActiveDisc.ID}
Cond6=${Me.CombatAbilityReady[Soul Shield]} && !${Me.ActiveDisc.ID}
Cond7=${Me.CombatAbilityReady[Ichor Guard]} && !${Me.ActiveDisc.ID}
Cond8=TRUE

[MySpells]
Gem1=Touch of Draygun
Gem2=Blood of Inruku
Gem3=Ignite Blood
Gem4=Dark Constriction
Gem5=Festering Darkness
Gem6=Spear of Muram
Gem7=Aura of Hate
Gem8=Terror of Discord
Gem9=Dread Gaze
