; KAHybrid Source: L70 - Lvl 70 DRU ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-70-dru-ini-w-conditions-for-ka11.905/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_DRU.ini

[General]
KissAssistVer=11.010 Beta
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=12
Buffs1=Flight of Eagles|!me
Buffs2=Skin of the Reptile|MA
Buffs3=Form of the Hunter|me
Buffs4=Mask of the Stalker|me
Buffs5=Aura of Life|Aura
Buffs6=Lion's Strength
Buffs7=Rod of Mystical Transvergence|Mana|30|60
Buffs8=Blessing of Oak|me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=10
DPSSkip=20
DPSInterval=2
DPS1=Vengeance of the Sun|90
DPS2=Wasp Swarm|85
DPS3=Sylvan Fire|80|Once
DPS4=Glitterfrost|75
DPS5=Combat Spellbook|40|Item|cond1
DPS6=Stormwatch|50
DPS7=Serpent Vines|20
DPS8=Dawnstrike|15
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Nature's Recovery|55
Heals2=Chlorotrope|40
Heals3=Moonshadow|20
AutoRezOn=0
AutoRezWith=Your Rez Item/AA/Spell
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Eradicate Disease|Disease
Cures2=Eradicate Poison|Poison
Cures3=Remove Greater Curse|Curse
Cures4=Radiant Cure
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Nature Walker's Behest
PetBuffsOn=1
PetBuffsSize=3
PetBuffs1=Savage Spirit
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=10
BurnAllNamed=1
Burn1=Nature's Guardian|mob
Burn2=Silent Casting
Burn3=Peaceful Spirit of the Wood|ma|cond5
Burn4=Entrap|mob|cond3
Burn5=Wrath of the Wild|ma
Burn6=Nature's Boon|cond2
Burn7=Spirit of the Wood|ma|cond4

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=6
Cond1=${Target.PctHPs} < 40 && ${Cast.Ready[Combat Spellbook]}
Cond2=${Me.AltAbilityReady[Nature's Boon]} && ${SpawnCount[Call of the Ancients]}<1 && ${SpawnCount[Exquisite Benediction]}<1 && ${SpawnCount[Nature's Boon]}<1
Cond3=${Target.PctHPs} < 30
Cond4=${Me.AltAbilityReady[Spirit of the Wood]} && ${Spawn[ID ${Group.MainAssist.ID}].PctHPs} < 50
Cond5=${Me.AltAbilityReady[Spirit of the Wood]} && ${Spawn[ID ${Group.MainAssist.ID}].PctHPs} < 30
Cond6=TRUE

[MySpells]
Gem1=Mire Thorns
Gem2=Swarming Death
Gem3=Vengeance of Tunare
Gem4=Karana's Renewal
Gem5=Immolation of Ro
Gem6=Shield of Bracken
Gem7=Lesser Succor
Gem8=Form of the Hunter
Gem9=Summer's Flame
