; KAHybrid Source: L70 - 70 FTP Bard no conditions KA12 | https://www.redguides.com/community/resources/70-ftp-bard-no-conditions-ka12.2064/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_BRD.ini

[General]
KissAssistVer=12.001
TwistOn=1
TwistMed=3
TwistWhat=1 2 3
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Aura of the Muse|aura
Buffs3=NULL
Buffs4=NULL
Buffs5=NULL
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Melee]
MeleeTwistOn=1
MeleeTwistWhat=1 3 4 5 6 7 8

[AE]
AEOn=0
AESize=3
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=NULL
DPS2=NULL
DPS3=NULL
DPS4=NULL
DPS5=NULL
DPS6=NULL
DPS7=NULL
DPS8=NULL
DPS9=NULL
DPS10=NULL
DPS11=NULL
DPS12=NULL
DPS13=NULL
DPS14=NULL
DPS15=NULL
DPS16=NULL
DPS17=NULL
DPS19=NULL
DPS20=NULL
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=0
AggroSize=3
Aggro1=NULL
Aggro2=NULL
Aggro3=NULL

[Cures]
CuresOn=1
CuresSize=2
Cures1=NULL
Cures2=NULL
CuresCOn=1

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=35
MezMaxLevel=73
MezStopHPs=80
MezSpell=Vulka's Lullaby
MezAESpell=Your AE Mez Spell|0

[Burn]
BurnSize=5
BurnAllNamed=0
Burn1=NULL
Burn2=NULL
Burn3=NULL
Burn4=NULL
Burn5=NULL

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=War March of Muram
Gem2=Selo's Accelerating Chorus
Gem3=Verse of Vesagran
Gem4=Psalm of Veeshan
Gem5=Chorus of Life
Gem6=Eriki's Psalm of Power
Gem7=Storm Blade
Gem8=Selo's Assonant Strain
Gem9=Vulka's Lullaby
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Heals]
HealsOn=0
HealsCOn=0
