; KAHybrid Source: L70 - Lvl 70 SHM ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-70-shm-ini-w-conditions-for-ka11.1366/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L70_SHM.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=18
Buffs1=Pained Memory|mana|90|20
Buffs2=Talisman of Wunshi|me
Buffs3=Infusion of Spirit|me
Buffs4=Talisman of Perseverance|me
Buffs5=Talisman of Sense|me
Buffs6=Ancestral Guard
Buffs7=Champion|me
Buffs8=Talisman of the Raptor|me
Buffs9=Form of the Great Bear
Buffs10=Talisman of the Tribunal|me
Buffs11=Cannibalization|mana|60|60
Buffs12=Talisman of Fortitude|me
Buffs13=Talisman of Might|me
Buffs14=Talisman of Celerity|me
Buffs15=Spirit of Bih`Li|me
Buffs16=Acumen of Dar Khura|me
Buffs17=Spiritual Channeling|mana|40|20
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=8
DPSSkip=20
DPSInterval=2
DPS1=Spirit of the Panther|99|ma
DPS2=Putrid Decay|95
DPS3=Crippling Spasm|90
DPS4=Hungry Plague|80
DPS5=Breath of Wunshi|75
DPS6=Blood of Yoppa|70
DPS7=Ice Age|30
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=6
Heals1=Incarnate Anew|0|rezooc|cond3
Heals2=Call of the Wild|0|rezooc|cond3
Heals3=Ancestral Aid|75
Heals4=Daluda's Mending|35
Heals5=Call of the Ancients|30|cond5
AutoRezOn=1
AutoRezWith=Your Primary Rez Item/AA/Spell
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=4
Cures1=Radiant Cure|disease
Cures2=Radiant Cure|poison
Cures3=Radiant Cure|curse
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=True Spirit
PetBuffsOn=1
PetBuffsSize=1
PetRampPullWait=0
PetSuspend=1
PetForceHealOnMed=0

[Burn]
BurnSize=7
BurnAllNamed=1
Burn1=Ancestral Guard
Burn2=Dampen Resistance
Burn3=Rabid Bear
Burn4=Virulent Paralysis
Burn5=Call of the Ancients|Cond5
Burn6=Spirit Call

[GoM]
GoMSize=1

[KConditions]
ConOn=1
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=${Me.CombatState.NotEqual[ACTIVE]}
Cond4=TRUE
Cond5=${SpawnCount[Call of the Ancients]}<1 && ${SpawnCount[Nature's Boon]}<1 && ${SpawnCount[Exquisite Benediction]}<1
Cond6=TRUE

[Spells]
Gem1=Daluda's Mending
Gem2=Blood of Yoppa
Gem3=Breath of Wunshi
Gem4=Crippling Spasm
Gem5=Pained Memory
Gem6=Ice Age
Gem7=Hungry Plague
Gem8=Putrid Decay
Gem9=Spirit of the Panther
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL
