return {
	['Buttons'] = {
		['Button_82'] = {
			['Cmd'] = '/btninstances create raid podragons',
			['Label'] = 'POD',
		},
		['Button_119'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild veeshan',
			['Label'] = 'VEESH',
			['labelMidX'] = 5,
			['CachedToggleLocked'] = false,
		},
		['Button_39'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid veeshanspeak',
			['Label'] = 'Veeshan Peak',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_16'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/say instance list',
			['Label'] = 'List-Instances',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_20'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 12,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.2019999997,
			['Cmd'] = '/btninstances quick raid potime',
			['Label'] = 'Plane Time',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_133'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid convorteum',
			['Label'] = 'CNVR',
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
		},
		['Button_118'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid veeshan',
			['Label'] = 'VEESH',
			['labelMidX'] = 5,
			['CachedToggleLocked'] = false,
		},
		['Button_112'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid sunderock',
			['Label'] = 'SUNDR',
			['labelMidX'] = 4,
			['CachedToggleLocked'] = false,
		},
		['Button_38'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid sleeperstomb',
			['Label'] = 'Sleepers Tomb',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_134'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild convorteum',
			['Label'] = 'CNVR',
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
		},
		['Button_76'] = {
			['Cmd'] = '/btninstances create raid cazicthule',
			['Label'] = 'CAZIC',
		},
		['Button_124'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid blightfire',
			['Label'] = 'BLGHT',
			['labelMidX'] = 4,
			['CachedToggleLocked'] = false,
		},
		['Button_59'] = {
			['Cmd'] = '/btninstances create guild stonehive',
			['Label'] = 'STONE',
		},
		['Button_37'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid sunderocksprings',
			['Label'] = 'Sunderock',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 24,
		},
		['Button_65'] = {
			['Cmd'] = '/btninstances create guild ldon',
			['Label'] = 'LDON',
		},
		['Button_36'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid oldcommons',
			['Label'] = 'Old Commons',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_117'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo veeshan',
			['Label'] = 'VEESH',
			['labelMidX'] = 8,
			['CachedToggleLocked'] = false,
		},
		['Button_18'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.2019999997,
			['Cmd'] = '/btninstances quick raid qrg',
			['Label'] = 'QRG Nexus',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_50'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/say instance list guild',
			['Label'] = 'List-Guild',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_6'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances inviteauto raid here',
			['Label'] = 'InviteAuto-Raid',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_7'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances quick raid here',
			['Label'] = 'Quick-Raid',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_123'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo blightfire',
			['Label'] = 'BLGHT',
			['labelMidX'] = 7,
			['CachedToggleLocked'] = false,
		},
		['Button_91'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create raid abyss',
			['Label'] = 'ABYSS',
			['labelMidX'] = 10,
			['CachedToggleLocked'] = false,
		},
		['Button_31'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 2,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964108.1499999998,
			['Cmd'] = '/btninstances quick raid anguish',
			['Label'] = 'Anguish T6',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_92'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create guild abyss',
			['Label'] = 'ABYSS',
			['labelMidX'] = 10,
			['CachedToggleLocked'] = false,
		},
		['Button_102'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9339999999,
			['Cmd'] = '/btninstances create solo oldblackburrow',
			['Label'] = 'OBB',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_100'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create raid templeveeshan',
			['Label'] = 'TOV',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_114'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo sleeper',
			['Label'] = 'SLEEP',
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
		},
		['Button_103'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create raid oldblackburrow',
			['Label'] = 'OBB',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_34'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964108.1499999998,
			['Cmd'] = '/btninstances quick raid oldblackburrow',
			['Label'] = 'Old Blackburrow',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_101'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create guild templeveeshan',
			['Label'] = 'TOV',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_94'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create raid anguish',
			['Label'] = 'ANGUISH',
			['labelMidX'] = 1,
			['CachedToggleLocked'] = false,
		},
		['Button_138'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[SOLO]',
			['ShowLabel'] = true,
		},
		['Button_125'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild blightfire',
			['Label'] = 'BLGHT',
			['labelMidX'] = 4,
			['CachedToggleLocked'] = false,
		},
		['Button_140'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[GUILD]',
			['ShowLabel'] = true,
		},
		['Button_95'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create guild anguish',
			['Label'] = 'ANGUISH',
			['labelMidX'] = 1,
			['CachedToggleLocked'] = false,
		},
		['Button_142'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[RAID]',
			['ShowLabel'] = true,
		},
		['Button_106'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create raid bloodmoon',
			['Label'] = 'BMOON',
			['labelMidX'] = 6,
			['CachedToggleLocked'] = false,
		},
		['Button_144'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[SOLO]',
			['ShowLabel'] = true,
		},
		['Button_27'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 1,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.6849999996,
			['Cmd'] = '/btninstances quick raid podragons',
			['Label'] = 'Plane Dragons',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_33'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964108.1499999998,
			['Cmd'] = '/btninstances quick raid templeveeshan',
			['Label'] = 'Temple Veeshan',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_146'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[GUILD]',
			['ShowLabel'] = true,
		},
		['Button_45'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances quick solo here',
			['Label'] = 'Quick-Solo',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_93'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9339999999,
			['Cmd'] = '/btninstances create solo anguish',
			['Label'] = 'ANGUISH',
			['labelMidX'] = 1,
			['CachedToggleLocked'] = false,
		},
		['Button_11'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances enter guild me here',
			['Label'] = 'EnterMy-Guild',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_126'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo direwind',
			['Label'] = 'DIRE',
			['labelMidX'] = 15,
			['CachedToggleLocked'] = false,
		},
		['Button_41'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid blightfire',
			['Label'] = 'Blightfire Moors',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_115'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid sleeper',
			['Label'] = 'SLEEP',
			['labelMidX'] = 6,
			['CachedToggleLocked'] = false,
		},
		['Button_12'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964106.3369999996,
			['Cmd'] = '/btninstances repop guild here',
			['Label'] = 'Repop Guild Here',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 3,
		},
		['Button_72'] = {
			['Cmd'] = '/btninstances create solo qvic',
			['Label'] = 'QVIC',
		},
		['Button_57'] = {
			['Cmd'] = '/btninstances create solo stonehive',
			['Label'] = 'STONE',
		},
		['Button_89'] = {
			['Cmd'] = '/btninstances create guild poair',
			['Label'] = 'POAIR',
		},
		['Button_79'] = {
			['Cmd'] = '/btninstances create raid arthicrex',
			['Label'] = 'ARTHIC',
		},
		['Button_83'] = {
			['Cmd'] = '/btninstances create guild podragons',
			['Label'] = 'POD',
		},
		['Button_120'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo kael',
			['Label'] = 'KAEL',
			['labelMidX'] = 13,
			['CachedToggleLocked'] = false,
		},
		['Button_96'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9339999999,
			['Cmd'] = '/btninstances create solo lopingplains',
			['Label'] = 'LOPING',
			['labelMidX'] = 7,
			['CachedToggleLocked'] = false,
		},
		['Button_108'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo oldcommons',
			['Label'] = 'OC',
			['labelMidX'] = 20,
			['CachedToggleLocked'] = false,
		},
		['Button_69'] = {
			['Cmd'] = '/btninstances create solo hushed',
			['Label'] = 'HUSHED',
		},
		['Button_131'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild dranikcatacombs',
			['Label'] = 'DRNK',
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
		},
		['Button_145'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[RAID]',
			['ShowLabel'] = true,
		},
		['Button_88'] = {
			['Cmd'] = '/btninstances create raid poair',
			['Label'] = 'POAIR',
		},
		['Button_42'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid direwind',
			['Label'] = 'Direwind Cliffs',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_87'] = {
			['Cmd'] = '/btninstances create solo poair',
			['Label'] = 'POAIR',
		},
		['Button_86'] = {
			['Cmd'] = '/btninstances create guild hohonora',
			['Label'] = 'HOH',
		},
		['Button_17'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances help',
			['Label'] = 'Instance-Help',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_14'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances enter solo me here',
			['Label'] = 'EnterMy-Solo',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_44'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid convorteum',
			['Label'] = 'Convorteum',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 24,
		},
		['Button_78'] = {
			['Cmd'] = '/btninstances create solo arthicrex',
			['Label'] = 'ARTHIC',
		},
		['Button_5'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances create raid here',
			['Label'] = 'Create-Raid',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_32'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 8,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964108.1499999998,
			['Cmd'] = '/btninstances quick raid lopingplains',
			['Label'] = 'Loping Plains',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_10'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances create guild here',
			['Label'] = 'Create-Guild',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_107'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create guild bloodmoon',
			['Label'] = 'BMOON',
			['labelMidX'] = 6,
			['CachedToggleLocked'] = false,
		},
		['Button_128'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild direwind',
			['Label'] = 'DIRE',
			['labelMidX'] = 13,
			['CachedToggleLocked'] = false,
		},
		['Button_132'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo convorteum',
			['Label'] = 'CNVR',
			['labelMidX'] = 11,
			['CachedToggleLocked'] = false,
		},
		['Button_75'] = {
			['Cmd'] = '/btninstances create solo cazicthule',
			['Label'] = 'CAZIC',
		},
		['Button_116'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild sleeper',
			['Label'] = 'SLEEP',
			['labelMidX'] = 6,
			['CachedToggleLocked'] = false,
		},
		['Button_129'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo dranikcatacombs',
			['Label'] = 'DRNK',
			['labelMidX'] = 11,
			['CachedToggleLocked'] = false,
		},
		['Button_54'] = {
			['Cmd'] = '/btninstances create solo qrg',
			['Label'] = 'QRG',
		},
		['Button_98'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create guild lopingplains',
			['Label'] = 'LOPING',
			['labelMidX'] = 7,
			['CachedToggleLocked'] = false,
		},
		['Button_64'] = {
			['Cmd'] = '/btninstances create raid ldon',
			['Label'] = 'LDON',
		},
		['Button_60'] = {
			['Cmd'] = '/btninstances create solo potimeb',
			['Label'] = 'POTIME',
		},
		['Button_46'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances quick guild here',
			['Label'] = 'Quick-Guild',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_105'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create solo bloodmoon',
			['Label'] = 'BMOON',
			['labelMidX'] = 6,
			['CachedToggleLocked'] = false,
		},
		['Button_23'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 1,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.2019999997,
			['Cmd'] = '/btninstances quick raid hushedbanquet',
			['Label'] = 'Hushed Banquet',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_56'] = {
			['Cmd'] = '/btninstances create guild qrg',
			['Label'] = 'QRG',
		},
		['Button_49'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances repop',
			['Label'] = 'Repop-Instance',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_99'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9339999999,
			['Cmd'] = '/btninstances create solo templeveeshan',
			['Label'] = 'TOV',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_122'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild kael',
			['Label'] = 'KAEL',
			['labelMidX'] = 11,
			['CachedToggleLocked'] = false,
		},
		['Button_127'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid direwind',
			['Label'] = 'DIRE',
			['labelMidX'] = 13,
			['CachedToggleLocked'] = false,
		},
		['Button_84'] = {
			['Cmd'] = '/btninstances create solo hohonora',
			['Label'] = 'HOH',
		},
		['Button_121'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid kael',
			['Label'] = 'KAEL',
			['labelMidX'] = 11,
			['CachedToggleLocked'] = false,
		},
		['Button_80'] = {
			['Cmd'] = '/btninstances create guild arthicrex',
			['Label'] = 'ARTHIC',
		},
		['Button_109'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid oldcommons',
			['Label'] = 'OC',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_55'] = {
			['Cmd'] = '/btninstances create raid qrg',
			['Label'] = 'QRG',
		},
		['Button_13'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.272,
			['Cmd'] = '/btninstances create solo here',
			['Label'] = 'Create-Solo',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_97'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create raid lopingplains',
			['Label'] = 'LOPING',
			['labelMidX'] = 7,
			['CachedToggleLocked'] = false,
		},
		['Button_15'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964106.3369999996,
			['Cmd'] = '/btninstances repop solo here',
			['Label'] = 'Repop Solo Here',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 3,
		},
		['Button_62'] = {
			['Cmd'] = '/btninstances create guild potimeb',
			['Label'] = 'POTIME',
		},
		['Button_61'] = {
			['Cmd'] = '/btninstances create raid potimeb',
			['Label'] = 'POTIME',
		},
		['Button_52'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/say create double instance',
			['Label'] = 'Create-Double',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_111'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 22,
			['CachedLastRan'] = 170656.54299999998,
			['Cmd'] = '/btninstances create solo sunderock',
			['Label'] = 'SUNDR',
			['labelMidX'] = 7,
			['CachedToggleLocked'] = false,
		},
		['Button_63'] = {
			['Cmd'] = '/btninstances create solo ldon',
			['Label'] = 'LDON',
		},
		['Button_81'] = {
			['Cmd'] = '/btninstances create solo podragons',
			['Label'] = 'POD',
		},
		['Button_104'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9349999998,
			['Cmd'] = '/btninstances create guild oldblackburrow',
			['Label'] = 'OBB',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_24'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 18,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.6849999996,
			['Cmd'] = '/btninstances quick raid qvic',
			['Label'] = 'Qvic P1',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_70'] = {
			['Cmd'] = '/btninstances create raid hushed',
			['Label'] = 'HUSHED',
		},
		['Button_73'] = {
			['Cmd'] = '/btninstances create raid qvic',
			['Label'] = 'QVIC',
		},
		['Button_77'] = {
			['Cmd'] = '/btninstances create guild cazicthule',
			['Label'] = 'CAZIC',
		},
		['Button_51'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/say instance delete allinstances',
			['Label'] = 'Delete-All',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_71'] = {
			['Cmd'] = '/btninstances create guild hushed',
			['Label'] = 'HUSHED',
		},
		['Button_19'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.2019999997,
			['Cmd'] = '/btninstances quick raid stonehive',
			['Label'] = 'Stonehive',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 24,
		},
		['Button_47'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances inviteauto solo here',
			['Label'] = 'InviteAuto-Solo',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_1'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 15,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 963717.7579999998,
			['Cmd'] = '/bcaa //burn\n/timed 500 /bcaa //burn',
			['Label'] = 'Burn (all)',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_2'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 10,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 963717.7579999998,
			['Cmd'] = '/bcaa //multi ; /twist off ; /mqp on',
			['Label'] = 'Pause (all)',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_3'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 2,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 963717.7579999998,
			['Cmd'] = '/bcaa //mqp off',
			['Label'] = 'Unpause (all)',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_113'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild sunderock',
			['Label'] = 'SUNDR',
			['labelMidX'] = 4,
			['CachedToggleLocked'] = false,
		},
		['Button_4'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 141960.077,
			['Cmd'] = '/bca //nav id ${Target.ID}',
			['Label'] = 'Nav Target (bca)',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 6,
		},
		['Button_25'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 12,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.6849999996,
			['Cmd'] = '/btninstances quick raid cazicthule',
			['Label'] = 'Cazic Thule',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_85'] = {
			['Cmd'] = '/btninstances create raid hohonora',
			['Label'] = 'HOH',
		},
		['Button_26'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.6849999996,
			['Cmd'] = '/btninstances quick raid arthicrex',
			['Label'] = 'Arthicrex',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 24,
		},
		['Button_9'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964106.3369999996,
			['Cmd'] = '/btninstances repop raid here',
			['Label'] = 'Repop Raid Here',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 3,
		},
		['Button_35'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964108.1499999998,
			['Cmd'] = '/btninstances quick raid bloodmoontemple',
			['Label'] = 'Bloodmoon Temple',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_48'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances inviteauto guild here',
			['Label'] = 'InviteAuto-Guild',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_143'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[GUILD]',
			['ShowLabel'] = true,
		},
		['Button_74'] = {
			['Cmd'] = '/btninstances create guild qvic',
			['Label'] = 'QVIC',
		},
		['Button_139'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[RAID]',
			['ShowLabel'] = true,
		},
		['Button_40'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 5,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid kaeldrakkel',
			['Label'] = 'Kael Drakkel',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_137'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[GUILD]',
			['ShowLabel'] = true,
		},
		['Button_136'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[RAID]',
			['ShowLabel'] = true,
		},
		['Button_141'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[SOLO]',
			['ShowLabel'] = true,
		},
		['Button_135'] = {
			['SectionHeader'] = true,
			['Cmd'] = '',
			['Label'] = '[SOLO]',
			['ShowLabel'] = true,
		},
		['Button_8'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/btninstances enter raid me here',
			['Label'] = 'EnterMy-Raid',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_53'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965571.2729999998,
			['Cmd'] = '/say create triple instance',
			['Label'] = 'Create-Triple',
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
		},
		['Button_58'] = {
			['Cmd'] = '/btninstances create raid stonehive',
			['Label'] = 'STONE',
		},
		['Button_90'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 25,
			['CachedLastRan'] = 965305.9339999999,
			['Cmd'] = '/btninstances create solo abyss',
			['Label'] = 'ABYSS',
			['labelMidX'] = 10,
			['CachedToggleLocked'] = false,
		},
		['Button_130'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create raid dranikcatacombs',
			['Label'] = 'DRNK',
			['labelMidX'] = 9,
			['CachedToggleLocked'] = false,
		},
		['Button_21'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 12,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.2019999997,
			['Cmd'] = '/btninstances quick raid ldon',
			['Label'] = 'LDoN',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 24,
		},
		['Button_30'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 10,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964108.1499999998,
			['Cmd'] = '/btninstances quick raid abyss',
			['Label'] = 'Abyss T5',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_110'] = {
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 20,
			['CachedLastRan'] = 965577.8369999998,
			['Cmd'] = '/btninstances create guild oldcommons',
			['Label'] = 'OC',
			['labelMidX'] = 19,
			['CachedToggleLocked'] = false,
		},
		['Button_28'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 10,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.6849999996,
			['Cmd'] = '/btninstances quick raid hallsofhonor',
			['Label'] = 'Halls Honor',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_66'] = {
			['Cmd'] = '/btninstances create solo misty',
			['Label'] = 'MISTY',
		},
		['Button_68'] = {
			['Cmd'] = '/btninstances create guild misty',
			['Label'] = 'MISTY',
		},
		['Button_22'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 5,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.2019999997,
			['Cmd'] = '/btninstances quick raid mistythicket',
			['Label'] = 'Misty Thicket',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
		['Button_67'] = {
			['Cmd'] = '/btninstances create raid misty',
			['Label'] = 'MISTY',
		},
		['Button_29'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 2,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964107.6849999996,
			['Cmd'] = '/btninstances quick raid airplane',
			['Label'] = 'Airplane',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 24,
		},
		['Button_43'] = {
			['CachedCountDown'] = 0,
			['labelMidX'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 964177.7019999997,
			['Cmd'] = '/btninstances quick raid dranikcatacombs',
			['Label'] = 'Catacombs Dranik',
			['CachedCoolDownTimer'] = 0,
			['labelMidY'] = 14,
		},
	},
	['Sets'] = {
		['EZ Inst - T5 to T8'] = {
			[1] = 'Button_141',
			[2] = 'Button_90',
			[3] = 'Button_93',
			[4] = 'Button_96',
			[5] = 'Button_99',
			[6] = 'Button_102',
			[7] = 'Button_105',
			[8] = 'Button_142',
			[9] = 'Button_91',
			[10] = 'Button_94',
			[11] = 'Button_97',
			[12] = 'Button_100',
			[13] = 'Button_103',
			[14] = 'Button_106',
			[15] = 'Button_143',
			[16] = 'Button_92',
			[17] = 'Button_95',
			[18] = 'Button_98',
			[19] = 'Button_101',
			[20] = 'Button_104',
			[21] = 'Button_107',
		},
		['Movement'] = {
			[1] = 'Button_4',
		},
		['EZ Inst - T1 to T4 Raid'] = {
			[1] = 'Button_73',
			[2] = 'Button_76',
			[3] = 'Button_79',
			[4] = 'Button_82',
			[5] = 'Button_85',
			[6] = 'Button_88',
		},
		['EZ Inst - T9 to T12+ Guild'] = {
			[1] = 'Button_110',
			[2] = 'Button_113',
			[3] = 'Button_116',
			[4] = 'Button_119',
			[5] = 'Button_122',
			[6] = 'Button_125',
			[7] = 'Button_128',
			[8] = 'Button_131',
			[9] = 'Button_134',
		},
		['EZ Inst - T9 to T12+ Solo'] = {
			[1] = 'Button_108',
			[2] = 'Button_111',
			[3] = 'Button_114',
			[4] = 'Button_117',
			[5] = 'Button_120',
			[6] = 'Button_123',
			[7] = 'Button_126',
			[8] = 'Button_129',
			[9] = 'Button_132',
		},
		['EZ Inst - Control'] = {
			[1] = 'Button_13',
			[2] = 'Button_5',
			[3] = 'Button_10',
			[4] = 'Button_45',
			[5] = 'Button_7',
			[6] = 'Button_46',
			[7] = 'Button_6',
			[8] = 'Button_47',
			[9] = 'Button_48',
			[10] = 'Button_8',
			[11] = 'Button_11',
			[12] = 'Button_14',
			[13] = 'Button_49',
			[14] = 'Button_16',
			[15] = 'Button_50',
			[16] = 'Button_51',
			[17] = 'Button_52',
			[18] = 'Button_53',
			[19] = 'Button_17',
		},
		['EZ Inst - Hubs+T70'] = {
			[1] = 'Button_135',
			[2] = 'Button_54',
			[3] = 'Button_57',
			[4] = 'Button_60',
			[5] = 'Button_63',
			[6] = 'Button_66',
			[7] = 'Button_69',
			[8] = 'Button_136',
			[9] = 'Button_55',
			[10] = 'Button_58',
			[11] = 'Button_61',
			[12] = 'Button_64',
			[13] = 'Button_67',
			[14] = 'Button_70',
			[15] = 'Button_137',
			[16] = 'Button_56',
			[17] = 'Button_59',
			[18] = 'Button_62',
			[19] = 'Button_65',
			[20] = 'Button_68',
			[21] = 'Button_71',
		},
		['EZ Inst - T1 to T4'] = {
			[1] = 'Button_138',
			[2] = 'Button_72',
			[3] = 'Button_75',
			[4] = 'Button_78',
			[5] = 'Button_81',
			[6] = 'Button_84',
			[7] = 'Button_87',
			[8] = 'Button_139',
			[9] = 'Button_73',
			[10] = 'Button_76',
			[11] = 'Button_79',
			[12] = 'Button_82',
			[13] = 'Button_85',
			[14] = 'Button_88',
			[15] = 'Button_140',
			[16] = 'Button_74',
			[17] = 'Button_77',
			[18] = 'Button_80',
			[19] = 'Button_83',
			[20] = 'Button_86',
			[21] = 'Button_89',
		},
		['EZ Inst - Hubs+T70 Raid'] = {
			[1] = 'Button_55',
			[2] = 'Button_58',
			[3] = 'Button_61',
			[4] = 'Button_64',
			[5] = 'Button_67',
			[6] = 'Button_70',
		},
		['EZ Inst - T9 to T12+ Raid'] = {
			[1] = 'Button_109',
			[2] = 'Button_112',
			[3] = 'Button_115',
			[4] = 'Button_118',
			[5] = 'Button_121',
			[6] = 'Button_124',
			[7] = 'Button_127',
			[8] = 'Button_130',
			[9] = 'Button_133',
		},
		['EZ Inst - T9 to T12+'] = {
			[1] = 'Button_144',
			[2] = 'Button_108',
			[3] = 'Button_111',
			[4] = 'Button_114',
			[5] = 'Button_117',
			[6] = 'Button_120',
			[7] = 'Button_123',
			[8] = 'Button_126',
			[9] = 'Button_129',
			[10] = 'Button_132',
			[11] = 'Button_145',
			[12] = 'Button_109',
			[13] = 'Button_112',
			[14] = 'Button_115',
			[15] = 'Button_118',
			[16] = 'Button_121',
			[17] = 'Button_124',
			[18] = 'Button_127',
			[19] = 'Button_130',
			[20] = 'Button_133',
			[21] = 'Button_146',
			[22] = 'Button_110',
			[23] = 'Button_113',
			[24] = 'Button_116',
			[25] = 'Button_119',
			[26] = 'Button_122',
			[27] = 'Button_125',
			[28] = 'Button_128',
			[29] = 'Button_131',
			[30] = 'Button_134',
		},
		['Primary'] = {
			[1] = 'Button_1',
			[2] = 'Button_2',
			[3] = 'Button_3',
		},
		['EZ Inst - Hubs+T70 Guild'] = {
			[1] = 'Button_56',
			[2] = 'Button_59',
			[3] = 'Button_62',
			[4] = 'Button_65',
			[5] = 'Button_68',
			[6] = 'Button_71',
		},
		['EZ Inst - T1 to T4 Solo'] = {
			[1] = 'Button_72',
			[2] = 'Button_75',
			[3] = 'Button_78',
			[4] = 'Button_81',
			[5] = 'Button_84',
			[6] = 'Button_87',
		},
		['EZ Inst - T5 to T8 Solo'] = {
			[1] = 'Button_90',
			[2] = 'Button_93',
			[3] = 'Button_96',
			[4] = 'Button_99',
			[5] = 'Button_102',
			[6] = 'Button_105',
		},
		['EZ Inst - T5 to T8 Raid'] = {
			[1] = 'Button_91',
			[2] = 'Button_94',
			[3] = 'Button_97',
			[4] = 'Button_100',
			[5] = 'Button_103',
			[6] = 'Button_106',
		},
		['EZ Inst - T5 to T8 Guild'] = {
			[1] = 'Button_92',
			[2] = 'Button_95',
			[3] = 'Button_98',
			[4] = 'Button_101',
			[5] = 'Button_104',
			[6] = 'Button_107',
		},
		['EZ Inst - Hubs+T70 Solo'] = {
			[1] = 'Button_54',
			[2] = 'Button_57',
			[3] = 'Button_60',
			[4] = 'Button_63',
			[5] = 'Button_66',
			[6] = 'Button_69',
		},
		['EZ Inst - T1 to T4 Guild'] = {
			[1] = 'Button_74',
			[2] = 'Button_77',
			[3] = 'Button_80',
			[4] = 'Button_83',
			[5] = 'Button_86',
			[6] = 'Button_89',
		},
	},
	['Characters'] = {
		['Ultimate EQ [DEV]_Eniine'] = {
			['Windows'] = {
				[1] = {
					['Visible'] = true,
					['Pos'] = {
						['x'] = 10,
						['y'] = 10,
					},
					['FPS'] = 0,
					['Locked'] = false,
					['Sets'] = {},
				},
			},
		},
		['EZ (Linux) x4 Exp_Bounced'] = {
			['Windows'] = {
				[1] = {
					['Visible'] = true,
					['Width'] = 344,
					['Height'] = 377,
					['Pos'] = {
						['x'] = 61,
						['y'] = 60,
					},
					['Locked'] = false,
					['FPS'] = 0,
					['Sets'] = {
						[2] = 'Movement',
						[1] = 'EZ Inst - T9 to T12+ Solo',
					},
				},
			},
		},
		['EZ (Linux) x4 Exp_Diggz'] = {
			['Windows'] = {
				[2] = {
					['Font'] = 12,
					['Height'] = 362,
					['ShowSearch'] = true,
					['HideTitleBar'] = false,
					['Theme'] = 'SpawnWatchNeon',
					['CompactMode'] = false,
					['AdvTooltips'] = true,
					['Visible'] = true,
					['HideScrollbar'] = false,
					['ButtonSize'] = 6,
					['Pos'] = {
						['x'] = 246,
						['y'] = 8,
					},
					['Width'] = 588,
					['Locked'] = false,
					['FPS'] = 10,
					['Sets'] = {
						[1] = 'EZ Inst - Control',
						[2] = 'EZ Inst - Hubs+T70',
						[3] = 'EZ Inst - T1 to T4',
						[4] = 'EZ Inst - T5 to T8',
						[5] = 'EZ Inst - T9 to T12+',
					},
				},
				[1] = {
					['Visible'] = false,
					['Width'] = 344,
					['Height'] = 377,
					['Pos'] = {
						['x'] = 61,
						['y'] = 60,
					},
					['Locked'] = false,
					['FPS'] = 0,
					['Sets'] = {
						[1] = 'Primary',
					},
				},
			},
		},
		['UltEQTest_Eniine'] = {
			['Windows'] = {
				[1] = {
					['Visible'] = false,
					['Width'] = 344,
					['Height'] = 377,
					['Pos'] = {
						['x'] = 61,
						['y'] = 60,
					},
					['Theme'] = 'UltimateEQAssist',
					['Locked'] = false,
					['FPS'] = 0,
					['Sets'] = {
						[1] = 'Movement',
					},
				},
			},
		},
		['E9 Profusion_Enine'] = {
			['Windows'] = {
				[1] = {
					['Width'] = 344,
					['Height'] = 377,
					['Font'] = 10,
					['HideTitleBar'] = false,
					['Locked'] = false,
					['CompactMode'] = false,
					['AdvTooltips'] = true,
					['Visible'] = false,
					['HideScrollbar'] = false,
					['Theme'] = 'UltimateEQAssist',
					['Pos'] = {
						['x'] = 61,
						['y'] = 60,
					},
					['ButtonSize'] = 6,
					['PerCharacterPositioning'] = false,
					['FPS'] = 0,
					['Sets'] = {
						[2] = 'Movement',
						[1] = 'Primary',
					},
				},
			},
		},
	},
	['LastBackup'] = 1775840657,
	['EZInstanceProfile'] = {
		['FontPack'] = 'awesome',
		['Version'] = 5,
		['WindowId'] = 2,
		['ButtonKeys'] = {
			['zone_sunderock_solo'] = 'Button_111',
			['zone_dranik_raid'] = 'Button_130',
			['zone_arthicrex_guild'] = 'Button_80',
			['zone_convorteum_raid'] = 'Button_133',
			['zone_sunderock_raid'] = 'Button_112',
			['zone_convorteum_guild'] = 'Button_134',
			['zone_cazic_raid'] = 'Button_76',
			['zone_stonehive_guild'] = 'Button_59',
			['zone_sleepers_raid'] = 'Button_115',
			['zone_sleepers_guild'] = 'Button_116',
			['zone_sleepers_solo'] = 'Button_114',
			['zone_dranik_solo'] = 'Button_129',
			['zone_blightfire_guild'] = 'Button_125',
			['zone_kael_solo'] = 'Button_120',
			['zone_oldcommons_solo'] = 'Button_108',
			['zone_bloodmoon_solo'] = 'Button_105',
			['zone_blightfire_solo'] = 'Button_123',
			['zone_blackburrow_raid'] = 'Button_103',
			['zone_hoh_raid'] = 'Button_85',
			['zone_potime_guild'] = 'Button_62',
			['zone_qvic_guild'] = 'Button_74',
			['zone_ldon_solo'] = 'Button_63',
			['zone_direwind_raid'] = 'Button_127',
			['zone_ldon_guild'] = 'Button_65',
			['hdr_EZ_Inst___T9_to_T12__raid'] = 'Button_145',
			['zone_hoh_guild'] = 'Button_86',
			['zone_arthicrex_solo'] = 'Button_78',
			['zone_convorteum_solo'] = 'Button_132',
			['zone_stonehive_solo'] = 'Button_57',
			['zone_potime_solo'] = 'Button_60',
			['zone_qrg_guild'] = 'Button_56',
			['zone_kael_guild'] = 'Button_122',
			['zone_kael_raid'] = 'Button_121',
			['zone_qvic_solo'] = 'Button_72',
			['zone_hoh_solo'] = 'Button_84',
			['zone_stonehive_raid'] = 'Button_58',
			['zone_oldcommons_guild'] = 'Button_110',
			['zone_cazic_guild'] = 'Button_77',
			['zone_potime_raid'] = 'Button_61',
			['zone_sunderock_guild'] = 'Button_113',
			['zone_pod_raid'] = 'Button_82',
			['zone_veeshans_guild'] = 'Button_119',
			['zone_cazic_solo'] = 'Button_75',
			['zone_ldon_raid'] = 'Button_64',
			['zone_veeshans_raid'] = 'Button_118',
			['ctrl_repop_solo_here'] = 'Button_15',
			['zone_veeshans_solo'] = 'Button_117',
			['zone_blightfire_raid'] = 'Button_124',
			['ctrl_repop_raid_here'] = 'Button_9',
			['zone_blackburrow_guild'] = 'Button_104',
			['zone_qrg_raid'] = 'Button_55',
			['zone_pod_solo'] = 'Button_81',
			['hdr_EZ_Inst___Hubs_T70_solo'] = 'Button_135',
			['zone_direwind_guild'] = 'Button_128',
			['hdr_EZ_Inst___T1_to_T4_solo'] = 'Button_138',
			['zone_dranik_guild'] = 'Button_131',
			['zone_sunderock'] = 'Button_37',
			['zone_blackburrow'] = 'Button_34',
			['zone_misty_guild'] = 'Button_68',
			['zone_airplane_solo'] = 'Button_87',
			['zone_bloodmoon_raid'] = 'Button_106',
			['zone_airplane_guild'] = 'Button_89',
			['zone_convorteum'] = 'Button_44',
			['zone_abyss_raid'] = 'Button_91',
			['zone_abyss_guild'] = 'Button_92',
			['zone_blackburrow_solo'] = 'Button_102',
			['ctrl_create_solo_here'] = 'Button_13',
			['zone_anguish_raid'] = 'Button_94',
			['zone_anguish_guild'] = 'Button_95',
			['ctrl_create_raid_here'] = 'Button_5',
			['ctrl_create_guild_here'] = 'Button_10',
			['ctrl_quick_solo_here'] = 'Button_45',
			['ctrl_quick_raid_here'] = 'Button_7',
			['ctrl_quick_guild_here'] = 'Button_46',
			['ctrl_invite_auto_raid'] = 'Button_6',
			['ctrl_invite_auto_solo'] = 'Button_47',
			['ctrl_invite_auto_guild'] = 'Button_48',
			['ctrl_enter_my_raid'] = 'Button_8',
			['ctrl_enter_my_guild'] = 'Button_11',
			['ctrl_enter_my_solo'] = 'Button_14',
			['ctrl_repop'] = 'Button_49',
			['ctrl_list'] = 'Button_16',
			['ctrl_list_guild'] = 'Button_50',
			['ctrl_delete_all'] = 'Button_51',
			['ctrl_create_double'] = 'Button_52',
			['ctrl_create_triple'] = 'Button_53',
			['ctrl_help'] = 'Button_17',
			['zone_qrg'] = 'Button_18',
			['zone_stonehive'] = 'Button_19',
			['zone_potime'] = 'Button_20',
			['zone_ldon'] = 'Button_21',
			['zone_misty'] = 'Button_22',
			['zone_hushed'] = 'Button_23',
			['zone_qvic'] = 'Button_24',
			['zone_cazic'] = 'Button_25',
			['zone_arthicrex'] = 'Button_26',
			['zone_misty_solo'] = 'Button_66',
			['zone_pod'] = 'Button_27',
			['zone_misty_raid'] = 'Button_67',
			['zone_hoh'] = 'Button_28',
			['zone_hushed_solo'] = 'Button_69',
			['zone_airplane'] = 'Button_29',
			['zone_hushed_raid'] = 'Button_70',
			['zone_hushed_guild'] = 'Button_71',
			['zone_abyss'] = 'Button_30',
			['zone_qvic_raid'] = 'Button_73',
			['zone_anguish'] = 'Button_31',
			['hdr_EZ_Inst___Hubs_T70_raid'] = 'Button_136',
			['zone_loping'] = 'Button_32',
			['hdr_EZ_Inst___Hubs_T70_guild'] = 'Button_137',
			['zone_tov'] = 'Button_33',
			['hdr_EZ_Inst___T1_to_T4_raid'] = 'Button_139',
			['zone_bloodmoon'] = 'Button_35',
			['hdr_EZ_Inst___T1_to_T4_guild'] = 'Button_140',
			['hdr_EZ_Inst___T5_to_T8_solo'] = 'Button_141',
			['zone_oldcommons'] = 'Button_36',
			['hdr_EZ_Inst___T5_to_T8_raid'] = 'Button_142',
			['hdr_EZ_Inst___T5_to_T8_guild'] = 'Button_143',
			['hdr_EZ_Inst___T9_to_T12__solo'] = 'Button_144',
			['zone_sleepers'] = 'Button_38',
			['hdr_EZ_Inst___T9_to_T12__guild'] = 'Button_146',
			['zone_veeshans'] = 'Button_39',
			['zone_direwind_solo'] = 'Button_126',
			['zone_kael'] = 'Button_40',
			['ctrl_repop_guild_here'] = 'Button_12',
			['zone_blightfire'] = 'Button_41',
			['zone_arthicrex_raid'] = 'Button_79',
			['zone_direwind'] = 'Button_42',
			['zone_pod_guild'] = 'Button_83',
			['zone_dranik'] = 'Button_43',
			['zone_qrg_solo'] = 'Button_54',
			['zone_airplane_raid'] = 'Button_88',
			['zone_abyss_solo'] = 'Button_90',
			['zone_tov_raid'] = 'Button_100',
			['zone_tov_guild'] = 'Button_101',
			['zone_anguish_solo'] = 'Button_93',
			['zone_loping_solo'] = 'Button_96',
			['zone_loping_raid'] = 'Button_97',
			['zone_bloodmoon_guild'] = 'Button_107',
			['zone_loping_guild'] = 'Button_98',
			['zone_tov_solo'] = 'Button_99',
			['zone_oldcommons_raid'] = 'Button_109',
		},
	},
	['Version'] = 7,
}