; Source class template: UltimateEQAssist_L50_DRU.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=15
Buffs1=Protection of Nature
Buffs2=Pack Chloroplast
Buffs3=Share Form of the Great Wolf
Buffs4=Storm Strength|Melee
Buffs5=Legacy of Spikes
Buffs9=Thorncoat|ME
Buffs10=FIREFIST|ME
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=10
DPSSkip=5
DPSInterval=2
DPS1=Fixation of Ro|98
DPS2=Ro's Fiery Sundering|95
DPS3=Vengeance of the Wild|90
DPS4=Drifting Death|85
DPS5=Ice|80
DPS6=Starfire|75
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=4
Heals1=Forest's Renewal|75|MA
Heals2=Superior Healing|60|!MA
AutoRezOn=0
HealsCOn=1

[Burn]
BurnSize=1
BurnAllNamed=0

[GoM]
GoMSize=1

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Fixation of Ro
Gem2=Ro's Fiery Sundering
Gem3=Vengeance of the Wild
Gem4=Drifting Death
Gem5=Ice
Gem6=Starfire
Gem7=Forest's Renewal
Gem8=Superior Healing
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=1
CuresCOn=1
