; Source class template: UltimateEQAssist_L50_BER.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Blunt Axe|Summon|Blunt Axe|100
Buffs2=Bonesplicer Axe|Summon|Bonesplicer Axe|100
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Melee]
BeforeCombat=Cast Before Melee Disc

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=0
DPSInterval=2
DPS1=Elbow Strike|99
DPS2=Kick|99
DPS3=Leg Cut|99
DPS5=Head Pummel|99
DPS6=Battle Cry|99|Cond1
DPS7=Frenzy|99
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Divertive Strike|90|>

[Burn]
BurnSize=15
BurnAllNamed=0

[KConditions]
ConOn=1
CondSize=5
Cond1=!${Me.Song[Battle Cry].ID}
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Heals]
HealsOn=1
HealsCOn=1

[Cures]
CuresOn=1
CuresCOn=1
