; Source class template: UltimateEQAssist_L50_WIZ.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=12.002
CharInfo=Wizard|50|FREE
Role=Assist
CampRadius=35
CampRadiusExceed=400
ReturnToCamp=1
ChaseAssist=0
ChaseDistance=25
CampfireOn=0
GroupEscapeOn=1
MedOn=1
MedStart=30
MedStop=100
MedCombat=0
RezAcceptOn=1|50
AcceptInvitesOn=1
EQBCOn=0
DanNetOn=1
ScatterOn=1
LOSBeforeCombat=1
BuffWhileChasing=1
CastRetries=3
ReturnToCampAccuracy=10

[Buffs]
BuffsOn=1
BuffsSize=12
Buffs1=NULL
Buffs2=command:/useitem Worn Totem|Dual|Blessing of Swiftness|Cond8
Buffs3=command:/notify AlertWnd ALW_Dismiss_Button leftmouseup
Buffs4=Ward of Calrena|Cond7
Buffs5=Lesser Familiar
Buffs6=Arch Shielding|Cond9
Buffs7=Elemental Armor|Cond10
Buffs8=Bounce|Cond11
Buffs9=Diamondskin|Cond12
Buffs10=O`Keil's Levity|Cond13
Buffs11=Harvest|mana|80
Buffs12=Distillate of Clarity VII|Dual|Elixir of Clarity VII|Cond14
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=4
DPSSkip=0
DPSInterval=2
DPS1=Nullify Magic|95|debuffall|strip
DPS2=Force Strike|85|Cond5
DPS3=Conflagration|80
DPS4=Ice Comet|70
DebuffAllOn=1
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=1
Aggro1=Concussion|75|>

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=2
Burn1=Intensity of the Resolute
Burn2=Armor of Experience

[KConditions]
ConOn=1
CondSize=14
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.ConColor.Equal[White]} || ${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]}
Cond4=${Target.Named} && (${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]})
Cond5=${Target.Class.CanCast} && !(${Target.Named})
Cond6=${Me.GroupAssistTarget.Named}
Cond7=!${Target.Buff[Ward of Calrena].ID} && ${Spell[Ward of Calrena].StacksTarget}
Cond8=!${Me.Buff[Blessing of Swiftness].ID} && ${Spell[Blessing of Swiftness].Stacks} && ${Me.FreeBuffSlots} > 0
Cond9=!${Me.Buff[Arch Shielding].ID} && ${Spell[Arch Shielding].Stacks} && ${Me.FreeBuffSlots} > 0
Cond10=!${Me.Buff[Elemental Armor].ID} && ${Spell[Elemental Armor].Stacks} && ${Me.FreeBuffSlots} > 0
Cond11=!${Me.Buff[Bounce].ID} && ${Spell[Bounce].Stacks} && ${Me.FreeBuffSlots} > 0
Cond12=${FindItemCount[Peridot]} > 0 &&  !${Me.Buff[Diamondskin].ID} && ${Spell[Diamondskin].Stacks} && ${Me.FreeBuffSlots} > 0
Cond13=!${Me.Buff[O`Keil's Levity].ID} && ${Spell[O`Keil's Levity].Stacks} && ${Me.FreeBuffSlots} > 0
Cond14=${FindItemCount[=Distillate of Clarity VII]}>0 && ${Me.PctMana} < 95 && !${Me.Buff[Elixir of Clarity VII].ID} && ${Spell[Elixir of Clarity VII].Stacks} && ${Me.FreeBuffSlots} > 0

[SpellSet]
LoadSpellSet=2

[Spells]
Gem1=Force Strike
Gem2=Conflagration
Gem3=Ice Comet
Gem4=Nullify Magic
Gem5=Concussion
Gem6=Harvest
Gem7=Diamondskin
Gem8=Lesser Evacuate

[Heals]
HealsOn=1
HealsCOn=1

[Cures]
CuresOn=1
CuresCOn=1
