; Source class template: UltimateEQAssist_L50_RNG.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
KissAssistVer=11.004
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Call of Sky
Buffs2=Feet like Cat|Melee
Buffs3=Spirit of Wolf
Buffs4=Call of Earth
Buffs5=Nature's Precision
Buffs6=Hawk Eye|Me
Buffs7=Pack Shrew|me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Immolate|95
DPS2=Swarm of Pain|80
DPS3=Call of Flame|60
DPS4=Snare|30
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Jolt|75|>

[Heals]
HealsOn=1
HealsSize=5
Heals1=Greater Healing|40
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[MySpells]
Gem1=Greater Healing
Gem2=Call of Earth
Gem3=Swarm of Pain
Gem4=Snare
Gem5=Immolate
Gem6=Spirit of Wolf
Gem7=Call of Flame
Gem8=Feet like Cat

[Cures]
CuresOn=1
CuresCOn=1
