; Source class template: UltimateEQAssist_L50_SHM.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=12.002
CharInfo=Shaman|50|FREE
Role=Assist
CampRadius=35
CampRadiusExceed=400
ReturnToCamp=1
ChaseAssist=0
ChaseDistance=25
CampfireOn=0
MedOn=1
MedStart=30
MedStop=100
MedCombat=0
RezAcceptOn=1|50
AcceptInvitesOn=1
EQBCOn=0
DanNetOn=1
ScatterOn=1
LOSBeforeCombat=1
BuffWhileChasing=1
CastRetries=3
ReturnToCampAccuracy=10

[Buffs]
BuffsOn=1
BuffsSize=25
Buffs1=NULL
Buffs2=command:/useitem Worn Totem|Dual|Blessing of Swiftness|Cond26
Buffs3=command:/notify AlertWnd ALW_Dismiss_Button leftmouseup
Buffs4=Guardian|Cond6
Buffs5=Inner Fire|Cond7
Buffs6=Infusion of Spirit|Class|ROG,BER,MNK,BST|Cond8
Buffs7=Harnessing of Spirit|CLASS|WAR,SHD,PAL,BRD,CLR,SHM,DRU,ENC,MAG,WIZ
Buffs8=Spirit Quickening|Melee|Cond10
Buffs9=Agility|Melee|Cond11
Buffs10=Stamina|Cond12
Buffs11=Strength|Melee|Cond13
Buffs12=Dexterity|Melee|Cond14
Buffs13=Charisma|Class|BRD|Cond15
Buffs14=Resist Cold|Cond16
Buffs15=Resist Fire|Cond17
Buffs16=Talisman of Jasinth|Cond18
Buffs17=Resist Poison|Cond19
Buffs18=Resist Magic|Cond20
Buffs19=Chloroplast|Cond21
Buffs20=Form of the Bear
Buffs21=Rage|Cond25
Buffs22=Cannibalize II|mana|90|20
Buffs23=Spirit of Bih`Li|Cond22
Buffs24=Shrink|Cond23
Buffs25=Distillate of Clarity VII|Dual|Elixir of Clarity VII|Cond27
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Melee]
AssistAt=98
MeleeOn=1
FaceMobOn=2
MeleeDistance=60
StickHow=!front delaystrafe loose uw
AutoFireOn=0
UseMQ2Melee=0
TargetSwitchingOn=0

[DPS]
DPSOn=1
DPSSize=5
DPSSkip=20
DPSInterval=2
DPS1=Malosi|99|debuffall|malo|always
DPS2=Togor's Insects|98|debuffall|slow|always
DPS3=Incapacitate|97|debuffall|crip
DPS4=Spirit of the Puma|96|MA|Cond24
DPS5=Envenomed Bolt|90
DebuffAllOn=2
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=2
Heals1=Kragg's Salve|65
Heals2=Stoicism|90|Class|SHM,CLR,DRU,ENC,WIZ,MAG,NEC
AutoRezOn=0
HealGroupPetsOn=1
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=1
Cures1=NULL
CuresCOn=1

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=2
Burn1=Intensity of the Resolute
Burn2=Armor of Experience

[Pet]
PetOn=1
PetSpell=Frenzied Spirit
PetBuffsOn=1
PetBuffsSize=9
PetBuffs1=Guardian|Cond6
PetBuffs2=Inner Fire|Cond7
PetBuffs3=Infusion of Spirit|Cond8
PetBuffs4=Spirit Quickening|Cond10
PetBuffs5=Agility|Cond11
PetBuffs6=Stamina|Cond12
PetBuffs7=Strength|Cond13
PetBuffs8=Dexterity|Cond14
PetBuffs9=Chloroplast|Cond21
PetCombatOn=1
PetAssistAt=95
PetAttackDistance=115

[KConditions]
ConOn=1
CondSize=27
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.ConColor.Equal[White]} || ${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]}
Cond4=${Target.Named} && (${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]})
Cond5=${Me.GroupAssistTarget.Named}
Cond6=!${Target.Buff[Guardian].ID} && ${Spell[Guardian].StacksTarget}
Cond7=!${Target.Buff[Inner Fire].ID} && ${Spell[Inner Fire].StacksTarget}
Cond8=!${Target.Buff[Infusion of Spirit].ID} && ${Spell[Infusion of Spirit].StacksTarget}
Cond9=!${Target.Buff[Harnessing of Spirit].ID} && ${Spell[Harnessing of Spirit].StacksTarget}
Cond10=!${Target.Buff[Spirit Quickening].ID} && ${Spell[Spirit Quickening].StacksTarget}
Cond11=!${Target.Buff[Agility].ID} && ${Spell[Agility].StacksTarget}
Cond12=!${Target.Buff[Stamina].ID} && ${Spell[Stamina].StacksTarget}
Cond13=!${Target.Buff[Strength].ID} && ${Spell[Strength].StacksTarget}
Cond14=!${Target.Buff[Dexterity].ID} && ${Spell[Dexterity].StacksTarget}
Cond15=!${Target.Buff[Charisma].ID} && ${Spell[Charisma].StacksTarget}
Cond16=!${Target.Buff[Resist Cold].ID} && ${Spell[Resist Cold].StacksTarget}
Cond17=!${Target.Buff[Resist Fire].ID} && ${Spell[Resist Fire].StacksTarget}
Cond18=!${Target.Buff[Talisman of Jasinth].ID} && ${Spell[Talisman of Jasinth].StacksTarget}
Cond19=!${Target.Buff[Resist Poison].ID} && ${Spell[Resist Poison].StacksTarget}
Cond20=!${Target.Buff[Resist Magic].ID} && ${Spell[Resist Magic].StacksTarget}
Cond21=!${Target.Buff[Chloroplast].ID} && ${Spell[Chloroplast].StacksTarget}
Cond22=!${Target.Buff[Spirit of Bih`Li].ID} && ${Spell[Spirit of Bih`Li].StacksTarget}
Cond23=${Target.Height} > 2.50
Cond24=!${Target.Buff[Spirit of the Puma].ID} && ${Spell[Spirit of the Puma].StacksTarget}
Cond25=!${Me.Buff[Rage].ID} && ${Spell[Rage].Stacks} && ${Me.FreeBuffSlots} > 0
Cond26=!${Me.Buff[Blessing of Swiftness].ID} && ${Spell[Blessing of Swiftness].Stacks} && ${Me.FreeBuffSlots} > 0
Cond27=${FindItemCount[=Distillate of Clarity VII]}>0 && ${Me.PctMana} < 95 && !${Me.Buff[Elixir of Clarity VII].ID} && ${Spell[Elixir of Clarity VII].Stacks} && ${Me.FreeBuffSlots} > 0

[SpellSet]
LoadSpellSet=2

[SpellS]
Gem1=Envenomed Bolt
Gem2=Spirit of the Puma
Gem3=Malosi
Gem4=Togor's Insects
Gem5=Incapacitate
Gem6=Cannibalize II
Gem7=Kragg's Salve
Gem8=Stoicism
