; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=35
CampRadiusExceed=300
ReturnToCamp=1
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=20
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

[Melee]
MeleeOn=0
AssistAt=98
FaceMobOn=1
MeleeDistance=25
StickHow=behindonce
AutoFireOn=0
UseMQ2Melee=0

[Buffs]
BuffsOn=1
BuffsCOn=1
BuffsBuff1=Shield of Restless Ice
BuffsBuffCond1=
BuffsBuff2=
BuffsBuffCond2=
BuffsBuff3=
BuffsBuffCond3=

[Heals]
HealsOn=0
HealsCOn=1
HealsBuff1=
HealsBuffCond1=
HealsBuff2=
HealsBuffCond2=
HealsBuff3=
HealsBuffCond3=

[DPS]
DPSOn=1
DPSCOn=1
DPSBuff1=Ethereal Skyblaze
DPSBuffCond1=
DPSBuff2=Claw of Sontalak
DPSBuffCond2=
DPSBuff3=Chaos Flame
DPSBuffCond3=
DPSBuff4=
DPSBuffCond4=

[Burn]
BurnOn=1
BurnCOn=1
BurnBuff1=Frenzied Devastation
BurnBuffCond1=
BurnBuff2=
BurnBuffCond2=

[AE]
AEOn=1
AECOn=1
AEBuff1=Cloudburst Stormstrike
AEBuffCond1=
AEBuff2=
AEBuffCond2=

[OhShit]
OhShitOn=0
OhShitCOn=1
OhShitBuff1=
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=

[Pet]
PetOn=0
PetCOn=1
PetBuff1=
PetBuffCond1=

[Cures]
CuresOn=1
CuresCOn=1
CuresBuff1=
CuresBuffCond1=

[Aggro]
AggroOn=0
AggroCOn=1
AggroBuff1=
AggroBuffCond1=

[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=

[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=
