; KAHybrid Source: L50 - Paladin - Level 50 - Maximum Effort! | https://www.redguides.com/community/resources/paladin-level-50-maximum-effort.2754/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L50_PAL.ini

[General]
KissAssistVer=12.002
CharInfo=Paladin|50|FREE
Role=Tank
CampRadius=60
CampRadiusExceed=400
ReturnToCamp=0
ChaseAssist=1
ChaseDistance=35
CampfireOn=0
MedOn=1
MedStart=30
MedStop=100
MedCombat=0
RezAcceptOn=1|50
AcceptInvitesOn=1
GroupWatchOn=0
GroupWatchCheck=FALSE
CorpseRecoveryOn=1
EQBCOn=0
DanNetOn=1
ScatterOn=1
LOSBeforeCombat=1
BuffWhileChasing=1
CastRetries=3

[Buffs]
BuffsOn=1
BuffsSize=16
Buffs1=NULL
Buffs2=command:/useitem Worn Totem|Dual|Blessing of Swiftness|Cond23
Buffs3=command:/notify AlertWnd ALW_Dismiss_Button leftmouseup
Buffs4=Command:/bandolier activate Deflection|Cond8
Buffs5=Valor|Cond13
Buffs6=Symbol of Pinzarn|Cond14
Buffs7=Brell's Steadfast Aegis|Cond15
Buffs8=Armor of Faith|Cond16
Buffs9=Endure Poison|Cond17
Buffs10=Endure Magic|Cond18
Buffs11=Resist Disease|Cond19
Buffs12=Divine Might|Cond20
Buffs13=Divine Purpose|Cond21
Buffs14=Valor of Marr|Cond22
Buffs15=Hammer of Striking|Summon|Summoned: Hammer of Striking|1|Cond24
Buffs16=Distillate of Skinspikes VI|Dual|Distillate of Skinspikes|Cond26
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Melee]
AssistAt=95
MeleeOn=1
FaceMobOn=2
MeleeDistance=60
StickHow=moveback 5% loose
AutoFireOn=0
UseMQ2Melee=0
TargetSwitchingOn=1

[DPS]
DPSOn=1
DPSSize=9
DPSSkip=20
DPSInterval=2
DPS1=Command:/bandolier activate 2Hander|100|Cond10
DPS2=Command:/bandolier activate Deflection|100|Cond11
DPS3=Command:/bandolier activate UndeadDeflect|100|Cond3
DPS4=Yaulp II|99|Me|Cond25
DPS5=Bash|98|Cond9
DPS6=Disarm|97|Mash
DPS7=Ethereal Cleansing|90
DPS8=Dismiss Undead|90|Cond3
DPS9=Holy Might|75
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=2
Aggro1=Taunt|100|<
Aggro2=Holy Might|75|<<

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=2
Burn1=Intensity of the Resolute
Burn2=Armor of Experience

[Heals]
HealsOn=1
AutoRezOn=2
HealsSize=5
Heals1=Wave of Life|70|!MA
Heals2=Superior Healing|40|CLASS|CLR,SHM,DRU
Heals3=Superior Healing|15|ME
Heals4=Lay On Hands|30|CLASS|PAL,CLR,SHM,DRU
Heals5=Renewal|0|rezooc
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=2
Cures1=Cure Disease|Disease
Cures2=Remove Curse|Curse
CuresCOn=1

[KConditions]
ConOn=1
CondSize=26
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.Body.Name.Equal[Undead]}
Cond4=${Target.ConColor.Equal[White]} || ${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]}
Cond5=${Target.Named} && (${Target.ConColor.Equal[Yellow]} || ${Target.ConColor.Equal[Red]})
Cond6=${Me.GroupAssistTarget.Named}
Cond7=${Target.Named}
Cond8=!(${Me.Inventory[13].Type.Equal[1H Slashing]} || ${Me.Inventory[13].Type.Equal[1H Blunt]} || ${Me.Inventory[13].Type.Equal[Piercing]})
Cond9=${Me.Inventory[14].Type.Equal[Shield]}
Cond10=!(${Me.Inventory[13].Type.Equal[2H Slashing]} || ${Me.Inventory[13].Type.Equal[2H Blunt]} || ${Me.Inventory[13].Type.Equal[2H Piercing]}) && ${SpawnCount[npc radius 100 zradius 30]} < 3 && ${Me.PctHPs} > 75 && ${Me.XTarget} < 3 && !${Target.ConColor.Equal[Red]}  && !${Me.Buff[Resurrection Sickness].ID} && !${Me.Buff[Revival Sickness].ID} && !${Target.Body.Name.Equal[Undead]}
Cond11=!(${Me.Inventory[13].Type.Equal[1H Slashing]} || ${Me.Inventory[13].Type.Equal[1H Blunt]} || ${Me.Inventory[13].Type.Equal[Piercing]}) && (${SpawnCount[npc radius 100 zradius 30]} > 3 && ${Me.XTarget} > 3) || ${Target.ConColor.Equal[Red]} || ${Me.PctHPs} < 50 || (${Me.Buff[Resurrection Sickness].ID} || ${Me.Buff[Revival Sickness].ID}) && !${Target.Body.Name.Equal[Undead]}
Cond12=${Me.Snared.ID} || ${Group.AnyoneMissing} || ${Me.Buff[Resurrection Sickness].ID} || ${Me.Buff[Revival Sickness].ID}
Cond13=!${Target.Buff[Valor].ID} && ${Spell[Valor].StacksTarget}
Cond14=!${Target.Buff[Symbol of Pinzarn].ID} && ${Spell[Symbol of Pinzarn].StacksTarget}
Cond15=!${Target.Buff[Brell's Steadfast Aegis].ID} && ${Spell[Brell's Steadfast Aegis].StacksTarget}
Cond16=!(${Target.Buff[Armor of Faith].ID} || ${Target.Buff[Protect].ID}) && ${Spell[Armor of Faith].StacksTarget}
Cond17=!${Target.Buff[Endure Poison].ID} && ${Spell[Endure Poison].StacksTarget}
Cond18=!${Target.Buff[Endure Magic].ID} && ${Spell[Endure Magic].StacksTarget}
Cond19=!${Target.Buff[Resist Disease].ID} && ${Spell[Resist Disease].StacksTarget}
Cond20=!${Me.Buff[Divine Might].ID} && ${Spell[Divine Might].Stacks} && ${Me.FreeBuffSlots} > 0
Cond21=${Me.PctMana} > 35 && ${Me.PctHPs} < 95 && ${Me.FreeBuffSlots} > 0
Cond22=!${Me.Buff[Valor of Marr].ID} && ${Spell[Valor of Marr].Stacks} && ${Me.FreeBuffSlots} > 0
Cond23=!${Me.Buff[Blessing of Swiftness].ID} && ${Spell[Blessing of Swiftness].Stacks} && ${Me.FreeBuffSlots} > 0
Cond24=${FindItemCount[=Summoned: Hammer of Striking]}<1
Cond25=!${Me.Sitting} || !${Me.Mount.ID}
Cond26=${FindItemCount[=Distillate of Skinspikes VI]} > 0 && !${Me.Buff[Distillate of Skinspikes].ID} && ${Spell[Distillate of Skinspikes].Stacks} && ${Me.FreeBuffSlots} > 0

[SpellSet]
LoadSpellSet=2

[Spells]
Gem1=Holy Might
Gem2=Dismiss Undead
Gem3=Cure Disease
Gem4=Ethereal Cleansing
Gem5=Yaulp II
Gem6=Wave of Life
Gem7=Superior Healing
Gem8=Remove Curse
