; KAHybrid Source: L50 - Level 50 Beastlord w/o conditions for KA 11.005 | https://www.redguides.com/community/resources/level-50-beastlord-w-o-conditions-for-ka-11-005.1644/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L50_BST.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=10
Buffs1=Protect
Buffs2=Spirit of Ox
Buffs3=Spirit of Monkey
Buffs4=Spiritual Brawn
Buffs5=Pack Shrew|me
Buffs6=Spiritual Light|me
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=10
DPSSkip=10
DPSInterval=2
DPS1=Listless Power|98
DPS2=Sha's Lethargy|95
DPS3=Malaria|85
DPS4=Envenomed Breath|75
DPS5=Frost Shard|30
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Spirit Salve|65
Heals2=Vigor of Zehkes|70|Pet
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Counteract Disease|Disease
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Spirit of Kashek
PetBuffsOn=1
PetBuffsSize=5
PetBuffs1=Spirit of Vermin
PetBuffs2=Yekan's Quickening
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=5
BurnAllNamed=1
Burn1=Frost Shard

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Frost Shard
Gem2=Malaria
Gem3=Envenomed Breath
Gem4=Sha's Lethargy
Gem5=Listless Power
Gem6=Vigor of Zehkes
Gem7=Spirit Salve
Gem8=Spiritual Brawn
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL
