; KAHybrid Source: L40 - Lvl 40 MAG ini w/conditions for KA11 | https://www.redguides.com/community/resources/lvl-40-mag-ini-w-conditions-for-ka11.1360/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L50_MAG.ini

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Greater Shielding
Buffs2=Phantom Chain
Buffs3=Elemental Shield
Buffs4=Barrier of Combustion
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Flame Arc|4

[DPS]
DPSOn=1
DPSSize=4
DPSSkip=10
DPSInterval=2
DPS1=Malaise|95
DPS2=Cinder Bolt|90|Once
DPS3=Expel Summoned|90|cond3
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=2
Heals1=Refresh Summoning|80|Pet
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Lesser Conjuration: Earth
PetBuffsOn=1
PetBuffsSize=3
PetBuffs1=Burnout II
PetBuffs2=Expedience
PetToysOn=1
PetToysSize=3
PetToys1=Dagger of Symbols|Summoned: Dagger of Symbols
PetToys2=Dagger of Symbols|Summoned: Dagger of Symbols
PetToysGave=NULL
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=1
BurnAllNamed=0

[GoM]
GoMSize=1

[KConditions]
ConOn=1
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.Body.Name.Equal[Summoned]}
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Cinder Bolt
Gem2=Greater Shielding
Gem3=Minor Conjuration: Earth
Gem4=Expel Summoned
Gem5=Inferno Shield
Gem6=Malaise
Gem7=Gate
Gem8=Tiny Companion
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
