; KAHybrid Source: L50 - Lvl 50 WAR ini - TLP | https://www.redguides.com/community/resources/lvl-50-war-ini-tlp.1856/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L50_WAR.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Elbow Strike|99
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=10
Aggro1=Taunt|100|<
Aggro2=Provoke|75|<

[Heals]
HealsOn=1
HealsSize=5
Heals1=Focused Will Discipline|90|cond1
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[KConditions]
ConOn=1
CondSize=5
Cond1=${Me.CombatState.NotEqual[COMBAT]} && ${Me.PctHPs} < 90
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Buffs]
BuffsOn=0
BuffsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
