; KAHybrid Source: L50 - Lvl 50 ENC ini w/o conditions for KA11 | https://www.redguides.com/community/resources/lvl-50-enc-ini-w-o-conditions-for-ka11.990/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L50_ENC.ini

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=15
Buffs1=Arch Shielding
Buffs2=Shadow
Buffs3=Intellectual Superiority|caster
Buffs4=Rune IV
Buffs5=Boon of the Clear Mind|me
Buffs6=Swift Like the Wind|melee
Buffs7=Group Resist Magic|me
Buffs8=Feedback|melee
Buffs9=Haunting Visage|ma
Buffs10=Guard of Alendar
Buffs11=Gift of Magic|caster
Buffs12=Brilliance|caster
Buffs13=Boon of the Garou|ma
Buffs14=Bounce
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=3
AERadius=50
AE1=Color Skew|3

[DPS]
DPSOn=1
DPSSize=7
DPSSkip=20
DPSInterval=2
DPS1=Tashania|95
DPS2=Shiftless Deeds|90
DPS3=Incapacitate|85
DPS4=Color Shift|80
DPS5=Dyn's Dizzying Draught|75
DPS6=Gasping Embrace|70
DebuffAllOn=0
DPSCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Kintaz's Animation
PetBuffsOn=1
PetBuffsSize=3
PetBuffs1=Strengthen
PetBuffs2=Swift Like the Wind
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=46
MezMaxLevel=55
MezStopHPs=80
MezSpell=Dazzle
MezAESpell=Entrancing Lights|3

[Burn]
BurnSize=3
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[MySpells]
Gem1=Tashania
Gem2=Incapacitate
Gem3=Dazzle
Gem4=Entrancing Lights
Gem5=Shiftless Deeds
Gem6=Color Skew
Gem7=Dyn's Dizzying Draught
Gem8=Gasping Embrace

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
