; KAHybrid Source: L50 - Work in Progress - 50 Necro | https://www.redguides.com/community/resources/50-necro.2109/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L50_NEC.ini

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Arch Shielding|ME
Buffs2=Spirit Armor|ME, Pet
Buffs3=Grim Aura|ME
Buffs4=Lich
Buffs5=Banshee Aura
Buffs6=Vampiric Embrace
Buffs7=Steelskin
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=10
DPSSkip=20
DPSInterval=2
DPS1=Scent of Darkness|98
DPS2=Ignite Blood|95
DPS3=Bond Of Death|90
DPS4=Envenomed Bolt|85
DPS5=Insidious Retrogression|80
DPS6=Torbas' Poison Blast|75
DPS7=Ignite Bones|70
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Drain Soul|90|Tap
AutoRezOn=0
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Invoke Death
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Augment Death
PetBuffs2=Form of Bleached Bone
PetBuffs3=Warg of Calliav
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=5
Cond1=${Me.PctHPs} < 85
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Scent of Darkness
Gem2=Ignite Blood
Gem3=Envenomed bolt
Gem4=Insidious Retrogression
Gem5=Torbas' Poison Blast
Gem6=Ignite Bones
Gem7=Drain Soul
Gem8=Bond of Death
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
