; KAHybrid Source: 125 Berserker for LS | https://www.redguides.com/community/resources/125-berserker-for-ls.2956/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_BER.ini
; Preset: GROUP
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=99
MeleeOn=1
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
PetTauntOverride=0


[Buffs]
BuffsOn=1
BuffsSize=11
Buffs1=Bloodlust Aura|aura
Buffs2=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs3=Summon Familiar: Striped Badger|Remove
Buffs4=NULL
Buffs5=Axe of the Eviscerator|Summon|Axe of the Eviscerator|300|Cond2
Buffs6=Axe of the Conqueror|Summon|Axe of the Mangler|300|Cond2
;Buffs8=command:/tell ${Group.MainTank} Dude I need to buy axes!|Cond3
Buffs7=Communion of Blood|end|50|Cond4
Buffs8=Cry Carnage|Cond8|MA
;Buffs10=Bloodfury|Cond11
Buffs9=Heightened Frenzy|Cond23
Buffs10=Jann's Veil|dual|Illusion Benefit Greater Jann|Cond24
Buffs11=Illusion: Efreeti|remove
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
Buffs11=NULL
BuffsCOn=1

[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
HealInterval=0
AutoRezOn=0
HealsSize=5
Heals1=NULL
Heals2=NULL
Heals3=NULL
Heals4=NULL
Heals5=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0

HealsCOn=1

[DPS]
DPSOn=1
DPSSize=22
DPSSkip=1
DPSInterval=1
DPS1=NULL
;DPS2=Rampage|99|Cond7
DPS2=Intimidation|99
DPS3=Battle Leap|99|once|Cond5
DPS4=Shared Barbarism|99|Cond6
;DPS6=Vehement Rage|99
DPS5=Cry Carnage|99|Cond8
DPS6=Unthinking Retaliation|99|Cond9
DPS7=Braxi's Howl|99
DPS8=Rolling Rage|99|Cond10
;DPS9=Bloodfury|99|once|Cond11
DPS9=Heightened Frenzy|99|mash|Cond12
DPS10=Conqueror's Coalition|99|Cond13
DPS11=Ecliptic Rage|99
DPS12=Eviscerating Frenzy|99
DPS13=Binding Axe|99
DPS14=Shriveling Strikes|99|mash
DPS15=Eviscerating Volley|99|mash
DPS16=Rending Axe Throw|99|mash
DPS17=Axe of Orrak|99|mash
DPS18=Vicious Vortex|99|mash
;DPS22=Vehement Rage|99
;DPS23=Untamed Rage|99
;DPS22=Savage Spirit|99
DPS19=Shared Barbarism|99|Cond6
DPS20=Velazul's Warmonger Coat|99
;DPS21=Blood Sustenance|99|Cond15
DPS21=Uncanny Resilience|99|Cond16
DPS22=Phantom Assailant|99
;DPS25=Convalesce|90|Cond17
;DPS26=command:/removebuff Convalesce|99|Cond18
;DPS27=Ancient: Cry of Chaos|99|Cond20
DebuffAllOn=0

DPSCOn=1

[Burn]
BurnSize=12
BurnAllNamed=0
Burn1=Reckless Abandon|Mob
Burn2=Savage Spirit|Mob
Burn3=Mangling Discipline|Mob
Burn4=Juggernaut Surge|Mob
Burn5=Blood Pact|Mob
Burn6=Blinding Fury|Mob
Burn7=Silent Strikes|Mob
Burn8=Spire of the Juggernaut|Mob
Burn9=Desperation|Mob
Burn10=Furious Rampage|Mob
Burn11=Brutal Discipline|Mob
Burn12=Cleaving Acrimony Discipline|Mob
UseTribute=0


[AE]
AEOn=0
AESize=10
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL
AE4=NULL
AE5=NULL
AE6=NULL
AE7=NULL
AE8=NULL
AE9=NULL
AE10=NULL


[OhShit]
OhShitOn=1
OhShitCOn=1
OhShitBuff1=Uncanny Resilience
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=0
PetCOn=1
PetBuff1=
PetBuffCond1=


[Cures]
CuresOn=1
CuresSize=5
Cures1=NULL
Cures2=NULL
Cures3=NULL
Cures4=NULL
Cures5=NULL

CuresCOn=1

[Aggro]
AggroOn=0
AggroSize=5
Aggro1=NULL
Aggro2=NULL
Aggro3=NULL
Aggro4=NULL
Aggro5=NULL


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[PullAdvanced]
PullLocsOn=0

[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


