; KAHybrid Source: 125 Cleric for LS | https://www.redguides.com/community/resources/125-cleric-for-ls.2985/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_CLR.ini
; Preset: SOLO
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=35
CampRadiusExceed=300
ReturnToCamp=1
ReturnToCampAccuracy=10
ChaseAssist=0
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=99
MeleeOn=0
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll rear
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
PetTauntOverride=0


[Buffs]
BuffsOn=1
BuffsSize=18
Buffs1=Divine Consequence
Buffs2=Aura of the Persistent|Aura
Buffs3=Bastion of Divinity|Aura
Buffs4=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs5=Summon Familiar: Striped Badger|Remove
Buffs6=Unified Hand of Infallibility|MA|Cond13
Buffs7=Quiet Prayer|Managroup|40
Buffs8=Divine Interference|MA
Buffs9=Saint's Unity|Cond12
Buffs10=Veturika's Perseverance|Mana|65
Buffs11=Rallied Greater Aegis of Vie|MA
Buffs12=Anticipated Interdiction|MA
Buffs13=Shining Steel|MA
Buffs14=Ward of Commitment|MA
Buffs15=null
;Axoeviq's Retort|MA|Cond15
Buffs16=null
;Radiant Hawk Harness|Mount
Buffs17=Divine Guardian|MA
Buffs18=Summoned: Modulation Shard VIII|mana|80
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

BuffsCOn=1

[Heals]
HealsOn=1
HealsSize=34
Heals1=Divine Resurrection|0|rez
Heals2=Blessing of Resurrection|0|rez
Heals3=Avowed Remedy|90|MA
Heals4=Guileless Remedy|90|MA
Heals5=Burst of Life|50
Heals6=Nineteenth Commandment|35|MA
Heals7=Ecliptic Blessing|60|MA
Heals8=Divine Arbitration|35
Heals9=Aegis of Superior Divinity|35|Cond9
Heals10=Celestial Rapidity|99|Cond11
Heals11=Healing Frenzy|99|Cond10
Heals12=Channeling the Divine|99|Cond10
Heals13=Ward of Purity|99|Cond10
Heals14=Exquisite Benediction|99|Cond10
Heals15=Flurry of Life|99|Cond10
Heals16=Spire of the Vicar|99|Cond10
Heals17=${InvSlot[Chest].Item.Name}|99|MA|Cond11
Heals18=Focused Celestial Regeneration|85|MA|Cond11
Heals19=null
;Axoeviq's Retort|99|MA|Once|Cond10
Heals20=Avowed Remedy|90|MA
Heals21=Guileless Remedy|90|MA
Heals22=Promised Remediation|99|MA
Heals23=Beacon of Life|95|Cond6
Heals24=Avowed Intervention|95|MA|Cond14
Heals25=Atoned Intervention|95|MA|Cond14
Heals26=Celestial Regeneration|99|Cond4
Heals27=Aegis of Superior Divinity|70|Cond4
Heals28=Syllable of Acceptance|95|Cond2
Heals29=Word of Greater Vivification|95|Cond3
Heals30=Avowed Remedy|80|!MA
Heals31=Guileless Remedy|80|!MA
Heals32=Promised Remediation|80|!MA
Heals33=Celestial Regeneration|35
Heals34=Summoned: Modulation Shard VIII|100|Cond16
AutoRezOn=1
AutoRezWith=Blessing of Resurrection

; Defaulting this to 0 since kiss will try and heal your auto-hater mobs if you have xtarget healing turned on.
XTarHeal=0
XTarHealList=2,3,4
HealGroupPetsOn=0
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealInterval=0
RezMeLast=0

HealsCOn=1

[DPS]
DPSOn=1
DPSSize=2
DPSSkip=1
DPSInterval=1
DebuffAllOn=0
DPS1=Yaulp|99|Cond7
DPS2=Summoned: Modulation Shard VIII|99|Cond16

DPSCOn=1

[Burn]
BurnSize=1
BurnAllNamed=0
Burn1=NULL
UseTribute=0
BurnText=Decepticons Attack


[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Celestial Regeneration|3
AE2=Sanctuary|3

[OhShit]
OhShitOn=1
OhShitCOn=1
OhShitBuff1=Divine Arbitration
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=0
PetCOn=1
PetBuff1=
PetBuffCond1=


[Cures]
CuresOn=1
CuresSize=6
Cures1=Radiant Cure
Cures2=Ward of Purity
Cures3=Purified Spirits
Cures4=Group Purify Soul
Cures5=Word of Greater Rejuvenation
Cures6=Sanctified Blood

CuresCOn=1

[Aggro]
AggroOn=1
AggroSize=4
Aggro1=Divine Retribution|80|>
Aggro2=Divine Peace|50|>
Aggro3=Sanctuary|30|>
Aggro4=Blessing of Sanctuary|45|>


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[PullAdvanced]
PullLocsOn=0

[Spells]
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
CastingInterruptOn=0
LoadSpellSet=2
SpellSetName=KA
Gem1=Avowed Remedy
Gem2=Guileless Remedy
Gem3=Promised Remediation
Gem4=Avowed Intervention
Gem5=Atoned Intervention
Gem6=Divine Interference
Gem7=Sanctified Blood
Gem8=Word of Greater Vivification
Gem9=Syllable of Acceptance
Gem10=Ecliptic Blessing
Gem11=Nineteenth Commandment
Gem12=Shining Steel
Gem13=Ward of Commitment
CheckStuckGem=1



[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


