; KAHybrid Source: 120 Enchanter ToL | https://www.redguides.com/community/resources/120-enchanter-tol.2371/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L80_ENC.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Enchanter|80|GOLD
ChaseAssist=1
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=0
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=6
SwitchWithMA=FALSE
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0


[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist


[Buffs]
BuffsOn=1
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
BuffsCOn=1
BuffsSize=8
Buffs1=Night's Perpetual Terror Rk. II|melee|OOG:${Me.Pet},${Spawn[Petuser].Pet.CleanName}
Buffs2=Voice of Perception
Buffs3=Hastening of Jharin
Buffs4=Marvel's Unity|Dual|Polyluminous Rune
Buffs5=Orator's Unity|Dual|Ward of the Beguiler
Buffs6=Twincast Aura Rk. II|aura
Buffs7=Mana Radix Aura|aura
Buffs8=Gather Mana|mana|50
BegOn=0
BegSize=1
BegPermissionHelp=Valid options are |raid |guild |fellowship |all |tell |group
BegPermission=NULL
BegHelp=Spellname|alias1,alias 2,alias 3 etc
Beg1=NULL
BuffCacheingDelay=300




[Melee]
MeleeOn=0
AssistAt=99
FaceMobOn=1
MeleeDistance=3
StickHow=snaproll rear5
AutoFireOn=0
UseMQ2Melee=1
DismountDuringFights=0
MeleeTwistOn=0
MeleeTwistWhat=DPS twist order here
TankAllMobs=FALSE
TargetSwitchingOn=0



[GoM]
GoMOn=1
GoMCOn=0
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMSize=0


[GMail]
GMailOn=0
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailSize=0


[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Bite of Tashani|3|Mob
AE2=Enveloping Helix|3|Mob



[DPS]
DPSOn=1
DebuffAllOn=1
DPSSkip=1
DPSInterval=2
DPSSize=9
DPS1=Constraining Coil|99|debuffall|slow|always
DPS2=Eradicate Magic|99|debuffall|strip
DPS3=Mind Vortex|99
DPS4=Perplexing Constriction|99
DPS5=Mindreap|99
DPS6=Psychological Appropriation Rk. II|99
DPS7=Polyluminous Assault|99
DPS8=Summoned: Dazzling Modulation Shard|99
DPS9=Spire of Enchantment|99


DPSCOn=1

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierSize=0
BandolierPull=Blunt


[OhShit]
OhShitOn=1
OhShitCOn=1
OhShitSize=7
OhShit1=Eldritch Rune|
OhShitCond1=${Me.PctHPs} < 40 && ${Me.AltAbilityReady[Eldritch Rune]}
OhShit2=Veil of Mindshadow|
OhShitCond2=${Me.PctHPs} < 40 && ${Me.AltAbilityReady[Veil of Mindshadow]}
OhShit3=Doppelganger|
OhShitCond3=${Me.PctHPs} < 60 && ${Me.AltAbilityReady[Doppelganger]}
OhShit4=Rune of Banishment|
OhShitCond4=${Me.PctHPs} < 70 && ${Me.AltAbilityReady[Rune of Banishment]}
OhShit5=Phantasmal Opponent|
OhShitCond5=${Me.PctHPs} < 50 && ${Me.AltAbilityReady[Phantasmal Opponent]}
OhShit6=Mind Over Matter|
OhShitCond6=${Me.PctHPs} < 40 && ${Me.AltAbilityReady[Mind Over Matter]}
OhShit7=Self Stasis|
OhShitCond7=${Me.PctHPs} < 15 && ${Me.AltAbilityReady[Self Stasis]}



[Aggro]
AggroOn=1
AggroSize=1
Aggro1=Arcane Whisper|100|<




[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=500
MaxZRange=500
CheckForMemblurredMobsInCamp=0
PullWait=5
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullLevel=0|0
PullNamedsFirst=0
ActNatural=1
UseCalm=0
CalmWith=Harmony
GrabDeadGroupMembers=0
PullTwistOn=0
PullArcWidth=0
PullCond=TRUE
PrePullCond=TRUE
CalmRadius=50
UseWayPointZ=0
PullRadiusToUse=90
PullPause=30|2
PullOnReturn=0


[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
XTarHeal=0
HealGroupPetsOn=0
HealsSize=3
InterruptHeals=100
Heals1=Friendly Stasis|10|!MA
Heals2=Glyph Spray|80|!MA
Heals3=Reactive Rune|60|!MA
HealInterval=0
AutoRezOn=0
XTarHealList=Xtar slots here Example: 5|6|7
RezMeLast=0



HealsCOn=1

[Cures]
CuresOn=1
CuresSize=0
CuresCond1=FALSE


CuresCOn=1

[Pet]
PetOn=1
PetBuffsSize=2
PetShrinkOn=0
PetShrinkSpell=Tiny Companion
PetBuffsOn=1
PetCombatOn=1
PetAssistAt=97
PetToysSize=6
PetBreakMezSpell=NULL
PetRampPullWait=0
PetSuspend=1
MoveWhenHit=0
PetHoldOn=1
PetForceHealOnMed=0
PetBehind=TRUE
PetSpell=Constance's Animation Rk. II
PetBuffs1=Invigorated Minion Rk. II
PetToysGave=
PetAttackDistance=35
PetFocus=NULL
PetBuffs2=NULL




[Mez]
MezOn=1
MezRadius=70
MezMinLevel=90
MezMaxLevel=123
MezStopHPs=1
MezSize=5
MezSpell=Addle Rk. II
MezAESpell=Bewildering Wave|3
SlowSpell=Slowing Helix
CrippleSpell=Constraining Coil Rk. II
TashSpell=Edict of Tashan Rk. II
MezDebuffOnResist=1
MezDebuffSpell=Edict of Tashan Rk. II




[Burn]
BurnText=Burn this
BurnAllNamed=1
UseTribute=0
BurnSize=8
Burn1=Mental Contortion
Burn2=Improved Twincast
Burn3=Illusions of Grandeur
Burn4=Chromatic Haze
Burn5=Calculated Insanity
Burn6=Focus of Arcanum
Burn7=Velium Threaded Mindlock Robe
Burn8=Companion's Fortification




[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=95



[PullAdvanced]
PullLocsOn=0



[Spells]
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=0
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1
Gem1=Edict of Tashan Rk. II
Gem2=Addle Rk. II
Gem3=Perilous Neutralization Rk. II
Gem4=Neutralizing Wave Rk. II
Gem5=Night's Perpetual Terror Rk. II
Gem6=Mindreap
Gem7=Psychological Appropriation Rk. II
Gem8=Polyluminous Assault
Gem9=Perplexing Constriction
Gem10=Constraining Coil Rk. II
Gem11=Constance's Animation Rk. II
Gem12=Marvel's Unity
Gem13=Mind Vortex


