; KAHybrid Source: 125 Beastlord for LS | https://www.redguides.com/community/resources/125-beastlord-for-ls.2955/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_BST.ini
; Preset: RAID
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=35
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=95
MeleeOn=1
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
PetTauntOverride=0

[Buffs]
BuffsOn=1
BuffsSize=14
Buffs1=Pact of the Wurine
Buffs2=Consumption of Spirit|Mana|80
Buffs3=Wildfang's Unity|Dual|Spiritual Valiancy
Buffs4=Shared Merciless Ferocity|MA
Buffs5=Jann's Veil|Dual|Illusion Benefit Greater Jann|Me
Buffs6=${InvSlot[Charm].Item.Name}|Me
Buffs7=Protection of the Warder|Cond2
Buffs8=Paragon of Spirit|Managroup|80
Buffs9=Focused Paragon of Spirits|Mana|90|Cond1
Buffs10=Wildfang's Unity|Ma
Buffs11=Summoned: Dazzling Modulation Shard|mana|80
Buffs12=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs13=Jann's Veil|dual|Illusion Benefit Greater Jann|Cond26
Buffs14=Illusion: Efreeti|remove
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
Buffs11=NULL

BuffsCOn=1

[Heals]
HealsOn=1
HealsSize=1
Heals1=Cissela's Melioration|50|pet
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealInterval=0
AutoRezOn=0
Heals1=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0

HealsCOn=1

[DPS]
DPSOn=1
DPSSize=38
DPSSkip=5
DPSInterval=2
;DPS1=Command:/bandolier activate 1h|100
;DPS2=Command:/Bandolier activate 2h|100|Cond4
DPS1=Chameleon Strike|99|weave
DPS2=Eruption of Claws|99|mash|Cond19
DPS3=Maelstrom of Claws|99
DPS4=Clobber|99|Mash
DPS5=Shriek at the Moon|99|Cond4
DPS6=Ikatiar's Vindication|99|Cond4
DPS7=Fevered Endemic|99|Cond4
DPS8=Lazam's Chill|99|Cond4
DPS9=Forgebound Blood|99|Cond4
DPS10=Frenzy of Spirit|99
DPS11=Bloodlust|99
DPS12=Bestial Alignment|99
DPS13=Frenzied Swipes|99
DPS14=Rimeclaw's Maelstrom|99
DPS15=Mortimus' Bite|99
DPS16=Frozen Creep|99
DPS17=Ankexfen Lance|99
DPS18=Crystalline Lance|99
DPS19=Savage Rancor|99|Cond13
DPS20=Spire of the Savage Lord|99|Cond4
DPS21=${InvSlot[Chest].Item.Name}|99|Cond4
DPS22=Ruaabri's Fury|99|Cond16
DPS23=Companion's Fury|99|Cond4
DPS24=Ferociousness|99|Cond20
DPS25=Group Bestial Alignment|99|Cond4
DPS26=Ecliptic Fury|99|MA
DPS27=Attack of the Warders|99
DPS28=Reflexive Riving|99|Cond10
DPS29=Enduring Frenzy|99
DPS30=Roar of Thunder|99
DPS31=Taste of Blood|99
DPS32=Roaring Strike|99
DPS33=Consumption of Spirit|99|cond25
DPS34=Paragon of Spirit|50|Cond21
DPS35=Sha's Reprisal|99|Cond3
DPS36=Forceful Rejuvenation|99
DPS37=Bestial Fierceness|99|Mash
DPS38=Summoned: Dazzling Modulation Shard|99|Cond24
DebuffAllOn=0

DPSCOn=1

[Burn]
BurnSize=14
;Burns are in the DPS
BurnAllNamed=0
Burn1=Ecliptic Fury|MA
Burn2=${InvSlot[Chest].Item.Name}
Burn3=Ruaabri's Fury
Burn4=Spire of the Savage Lord
Burn5=Mass Group Buff
Burn6=Paragon of Spirit
Burn7=Group Bestial Alignment
Burn8=Frenzied Swipes
Burn9=Bloodlust
Burn10=Frenzy of Spirit
Burn11=Ferociousness
Burn12=Enduring Frenzy
Burn13=Forceful Rejuvenation
Burn14=Attack of the warders
UseTribute=0


[AE]
AEOn=0
AESize=1
AERadius=50
AE1=NULL


[OhShit]
OhShitOn=0
OhShitCOn=1
OhShitBuff1=
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Spirit of Panthea
PetBuffsOn=1
PetBuffsSize=12
PetBuffs1=Spellbreaker's Synergy
PetBuffs2=Magna's Aggression
PetBuffs4=Hobble of Spirits
PetBuffs5=Companion's Aegis
PetBuffs6=Companion's Fortification
PetBuffs7=Taste of Blood
PetBuffs8=Companion's Intervening Divine Aura
PetBuffs9=Vitalizing Warder
PetBuffs10=Spiritcaller Totem of the Feral
PetBuffs12=Sapping Bite
Petbuffs13=Cohort's Unity|Dual|Pet|Insatiable Voracity
PetRampPullWait=1
PetSuspend=0
PetForceHealOnMed=0
PetFocus=NULL
PetShrinkOn=1
PetShrinkSpell=Shrink Companion
PetAssistAt=99
PetAttackDistance=115
PetToysSize=6
PetBreakMezSpell=NULL
MoveWhenHit=0
PetHoldOn=1
PetToysGave=
PetBuffs3=NULL
PetBuffs11=NULL


[Cures]
CuresOn=1
CuresSize=5
Cures1=NULL
Cures2=NULL
Cures3=NULL
Cures4=NULL
Cures5=NULL
CuresCOn=1

[Aggro]
AggroOn=1
AggroSize=2
Aggro1=Playing Possum|90|>
Aggro2=NULL


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[PullAdvanced]
PullLocsOn=0

[Spells]
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1
Gem1=Rimeclaw's Maelstrom
Gem2=Mortimus' Bite
Gem3=Frozen Creep
Gem4=Ankexfen Lance
Gem5=Hoarfrost Roar
Gem6=Lazam's Chill
Gem7=Fevered Endemic
Gem8=Forgebound Blood
Gem9=Spellbreaker's Synergy
Gem10=Ecliptic Fury
Gem11=Shriek at the Moon
Gem12=Shared Merciless Ferocity
Gem13=Crystalline Lance

[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


