; KAHybrid Source: 120 Necro ToL | https://www.redguides.com/community/resources/120-necro-tol.2314/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_NEC.ini
; Preset: GROUP
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=100
MeleeOn=0
FaceMobOn=1
MeleeDistance=250
StickHow=null
AutoFireOn=0
UseMQ2Melee=0
TargetSwitchingOn=0

##------------------------------------------------------------------------------------------------------------------##



[Buffs]
BuffsOn=1
BuffsSize=8
Buffs1=Mortifier's Unity|Dual|Flesh to Venom|Me
Buffs2=Lunaside|Me
Buffs3=Blood Magic|Mana|50|25
Buffs4=Death Bloom|Mana|80|80
Buffs5=Glowing Modulation Shard|MANA|40|60
Buffs6=Carrion Skin|Cond16
Buffs7=Dead Man Floating
Buffs8=Shield of Shadow|Me
##---Auto Pop Potion of Adventure, beware will go until your out!!!---##
;Buffs9=Potion of Adventure|Dual|Potion of Adventure
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

##------------------------------------------------------------------------------------------------------------------##

BuffsCOn=1

[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
AutoRezOn=0
HealsSize=5
Heals1=NULL
Heals2=NULL
Heals3=NULL
Heals4=NULL
Heals5=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0
HealInterval=0

##------------------------------------------------------------------------------------------------------------------##

HealsCOn=1

[DPS]
DPSOn=1
DPSSize=19
DPSSkip=1
DPSInterval=0
DPS1=Infected Wounds|99|Once
DPS2=Composite Paroxysm|98|Cond20
DPS2=Pyre of Va Xakra|97|Cond2
DPS3=Scent of Thule|96|Once
DPS4=Extinction|95|Cond9
DPS5=Hemorrhagic Venom|94|Cond3
DPS6=Zelnithak's Pallid Haze|93|Cond4
DPS7=Danvid's Grip of Decay|92|Cond5
DPS8=Pyre of the Neglected|91|Cond7
DPS9=Scalding Shadow|90|Cond6
DPS10=Proclamation for Blood|88|Cond10
DPS11=Ignite Cognition|75|Cond8
DPS12=Call Skeleton Mass|94|Weave
DPS13=Swarm of Decay|94|Weave
DPS14=Rise of Bones|94|Weave
DPS15=Wake the Dead|94|Weave|Cond17
DPS16=Gathering Dusk|94|Weave
DPS17=Embalming Venin|95|Weave
DPS18=Fleshrot's Decay|95|Weave
;Necro 2.0
;DPS19=Deathwhisper|94|Weave
DPS20=Bestow Rot|95|Cond1
DebuffAllOn=0


##------------------------------------------------------------------------------------------------------------------##

DPSCOn=1

[Burn]
BurnSize=11
BurnAllNamed=0
Burn1=Companion's Fury
Burn2=Gathering Dusk
Burn3=Spire of Necromancy
Burn4=Focus of Arcanum
Burn5=Hand of Death
Burn6=Funeral Pyre
Burn7=Mercurial Torment
Burn8=Silent Casting
Burn9=Gathering Dusk
Burn10=Embalmer's Carapace
Burn11=${InvSlot[Chest].Item.Name}|85
UseTribute=0

##------------------------------------------------------------------------------------------------------------------##


[AE]
AEOn=0
AESize=10
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL
AE4=NULL
AE5=NULL
AE6=NULL
AE7=NULL
AE8=NULL
AE9=NULL
AE10=NULL

##------------------------------------------------------------------------------------------------------------------##


[OhShit]
OhShitOn=0
OhShitCOn=1
OhShitBuff1=
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Unrelenting Assassin
PetBuffsOn=1
PetBuffsSize=4
PetBuffs1=Sigil of Undeath
PetBuffs2=Inspire Ally
PetBuffs3=Companion's Aegis
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0
PetFocus=NULL
PetShrinkOn=0
PetShrinkSpell=Tiny Companion
PetBuffs4=NULL
PetAssistAt=99
PetAttackDistance=45
PetToysSize=6
PetBreakMezSpell=NULL
MoveWhenHit=0
PetHoldOn=1
PetToysGave=

##------------------------------------------------------------------------------------------------------------------##


[Cures]
CuresOn=1
CuresSize=4
Cures1=Embrace the Decay|Me|Poison
Cures2=Embrace the Decay|Me|Disease
Cures3=Cleansing Rod|Me|Poison
Cures4=Cleansing Rod|Me|Disease

##------------------------------------------------------------------------------------------------------------------##

CuresCOn=1

[Aggro]
AggroOn=0
AggroSize=5
Aggro1=NULL
Aggro2=NULL
Aggro3=NULL
Aggro4=NULL
Aggro5=NULL

##------------------------------------------------------------------------------------------------------------------##


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

##------------------------------------------------------------------------------------------------------------------##

[PullAdvanced]
PullLocsOn=0
##------------------------------------------------------------------------------------------------------------------##


[Mez]
MezOn=0
MezRadius=50
MezMinLevel=1
MezMaxLevel=120
MezStopHPs=80
MezSpell=Penumbra Manacles
MezDebuffOnResist=0
MezDebuffSpell=Your Debuff Spell

##------------------------------------------------------------------------------------------------------------------##


[Spells]
Gem1=Pyre of Va Xakra
Gem2=Extinction
Gem3=Hemorrhagic Venom
Gem4=Zelnithak's Pallid Haze
Gem5=Danvid's Grip of Decay
Gem6=Pyre of the Neglected
Gem7=Scalding Shadow
Gem8=Infected Wounds
Gem9=Thall Va Kelun's Flashblaze
Gem10=Composite Paroxysm
Gem11=Proclamation for Blood
Gem12=Ignite Cognition
Gem13=Call Skeleton Mass
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=1
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1

##------------------------------------------------------------------------------------------------------------------##


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92

##------------------------------------------------------------------------------------------------------------------##


