; KAHybrid Source: 125 Bard for LS | https://www.redguides.com/community/resources/125-bard-for-ls.2953/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L80_BRD.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Bard|80|GOLD
ChaseAssist=1
ChaseDistance=35
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=3|60|PAL,ENC,SHM,CLR
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=0
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=1
SwitchWithMA=0
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=1 2 3 4 5 6
TwistOn=1
TwistWhat=1 2 3 4 5 6


[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist


[Buffs]
BuffsOn=1
BuffsSize=11
Buffs1=Aura of Tenisbre|Aura
;Buffs2=Regar's Lively Crescendo
Buffs2=Rallying Call|managroup|30
Buffs3=Rallying Solo|end|29
Buffs4=Rallying Call|endgroup|30
Buffs5=Selo's Sonata|Cond15
Buffs6=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs7=Summon Familiar: Striped Badger|Remove
Buffs8=Summoned: Dazzling Modulation Shard|mana|80
Buffs9=Jann's Veil|dual|Illusion Benefit Greater Jann|Cond19
Buffs10=Illusion: Djinn Emissary|remove
Buffs11=Rapier of Somber Notes|Dual|Symphony of Battle|Group|Cond20
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

BuffsCOn=1

[Melee]
MeleeTwistOn=1
MeleeTwistWhat=3 10 11 3 12 13 3 1 4 3 2 5
AssistAt=99
MeleeOn=1
MeleeDistance=75
StickHow=snaproll
UseMQ2Melee=1
FaceMobOn=1
AutoFireOn=0
TargetSwitchingOn=0
PetTauntOverride=0


[GMail]
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0
GMailSize=0


[AE]
AEOn=1
AESize=3
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL


[DPS]
DPSOn=1
DPSSize=21
DPSSkip=1
DPSInterval=2
DPS1=Blade of Vesagran|99
DPS2=Funeral Dirge|99|Cond8
DPS3=Quick Time|99|Cond8
DPS4=Spire of the Minstrels|99|Cond17
DPS5=Flurry of Notes|99|Cond8
DPS6=Frenzied Kicks|99|Cond8
DPS7=Song of Stone|99|Cond8
;DPS8=Vainglorious Shout|99|Cond8
; use boastful if you're having mez breaking / adds through walls issues
;DPS8=Boastful Bellow|99|Cond8
DPS8=Dance of Blades|99|Cond8
DPS9=Mythic Glyph of Ultimate Power V|99|Cond10
;DPS10=command:/stopdisc|99|Cond5
DPS10=Deftdance Discipline|100|Cond7
DPS11=command:/pet swarm|99|Once|Cond12
DPS12=Lyrical Prankster|99
DPS13=Bladed Song|99
DPS14=Fierce Eye|99|Cond9
DPS15=null
;Cacophony|99|Mob
DPS16=Intimidation|99|Mash
DPS17=${InvSlot[Chest].Item.Name}|99|Cond1
;DPS20=Ecliptic Psalm|99|Cond2
;DPS21=Boastful Bellow|98|Cond3
;DPS21=Boastful Bellow|99|Cond13|Once
DPS18=Selo's Sonata|15
DPS19=Thousand Blades|99|Cond8
DPS20=Reflexive Rebuttal|99|Cond16
DPS21=Summoned: Dazzling Modulation Shard|99|Cond18
DebuffAllOn=0

DPSCOn=1

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierPull=DPS
BandolierSize=0


[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=3

# Only use if my health is less than 50% | 1.5min duration
OhShit1=Hymn of the Last Stand|
OhShitCond1=${Me.PctHPs} < 50

# Only use if my health is less than 50% | 1min duration
OhShit2=Shield of Notes|
OhShitCond2=${Me.PctHPs} < 45

# Only use if my health is less than my mana
OhShit3=Fading Memories|
OhShitCond3=${Me.PctHPs} < ${Me.PctMana} && ${Me.PctHPs} < 40


[Aggro]
AggroOn=1
AggroSize=3
Aggro1=Fading Memories|90|>
Aggro2=Shield of Notes|90|>
Aggro3=Hymn of the Last Stand|95|>


[Pull]
PullTwistOn=1
PullWith=Sonic Disturbance
PullMeleeStick=0
MaxRadius=250
MaxZRange=100
UseWayPointZ=0
PullWait=3
ChainPull=0
ChainPullHP=40
PullPause=30|2
PullLevel=100|114
PullArcWidth=0
PullRadiusToUse=90
PullRoleToggle=0
PullOnReturn=0


[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
HealInterval=0
AutoRezOn=0
HealsSize=0
Heals1=Token of Resurrection|0|rez
Heals2=NULL
Heals3=NULL
Heals4=NULL
Heals5=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0

; I use the dps section for "burns" with conditions
; I still use BurnAllNamed on so i can toggle those burns.
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=NULL
Cures2=NULL
Cures3=NULL
Cures4=NULL
Cures5=NULL

CuresCOn=1

[Pet]
PetOn=0
PetBehind=TRUE
PetBuffsSize=0


[Mez]
; Use MezOn=3 if you ONLY want AOE Mez (this is how i run it)
MezOn=0
MezRadius=50
MezMinLevel=95
MezMaxLevel=999
MezStopHPs=90
MezSpell=Slumber of Suja
MezAESpell=Wave of Stupor|3
MezDebuffOnResist=0
MezDebuffSpell=Your Debuff Spell


[Burn]
BurnSize=3
BurnAllNamed=1
Burn1=NULL
BurnText=Burn
UseTribute=0
Burn2=NULL
Burn3=NULL
BurnTwistWhat=0


[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92

[PullAdvanced]
PullLocsOn=0

[Spells]
MiscGem=7
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=KissAssist
CastingInterruptOn=1
Gem1=Aria of Tenisbre
Gem2=Tatalros' Spiteful Lyric
Gem3=Eoreg's Insult
Gem4=War March of Nokk
Gem5=Dhakka's Spry Sonata
;Gem6=Kazumi's Note of Preservation
;Gem6=War Chorus of the Bloodbeast
Gem6=Chorus of Shalowain
Gem7=Pulse of August
Gem8=Slumber of Suja
Gem9=Wave of Stupor
Gem10=Swarn's Chant of Frost
Gem11=Goremand's Chant of Disease
Gem12=Kindleheart's Chant of Flame
Gem13=Marsin's Chant of Poison
CheckStuckGem=1


