; KAHybrid Source: 120 ToL Silver Mage | https://www.redguides.com/community/resources/120-tol-silver-mage.2601/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_MAG.ini
; Preset: GROUP
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
MeleeOn=0
AssistAt=98
FaceMobOn=1
MeleeDistance=25
StickHow=behindonce
AutoFireOn=0
UseMQ2Melee=0


[Buffs]
BuffsOn=1
BuffsSize=17
Buffs1=Sickle of Umbral Modulation|Summon|Sickle of Umbral Modulation|1
Buffs2=Summon Modulation Shard|Summon|Summoned: Dazzling Modulation Shard|1
Buffs3=Summon Molten Komatiite Orb|Summon|Molten Komatiite Orb|1
Buffs4=Arcane Distillect|Aura
Buffs5=Circle of Emberweave Coat
Buffs6=Volcanic Veil|Class|War,Pal
Buffs7=Summon Forbearing Minion|Summon|Summoned: Exigent Minion XXIV|1
Buffs8=Summon Forbearing Servant|Summon|Summoned: Exigent Servant XXIV|1
Buffs9=Grant Frostbound Paradox|Summon|Summoned: Frostbound Sliver|1
Buffs10=Elemental Form|Dual|Elemental Form XXXIV|Me
Buffs11=Gather Vigor|Mana|85
Buffs12=Thaumaturge's Unity|Dual|Chaotic Largesse|Me
Buffs13=Relentless Symbiosis|Dual|Relentless Symbiosis Recourse|Me
Buffs14=Shield of Inevitability|Me
Buffs15=Perfected Levitation|Dual|Group Perfected Levitation
Buffs16=Personal Hemic Source|Dual|Familiar: Personal Hemic Source|Me
Buffs17=Golden Owlbear Saddle|Dual|Summon Owlbear|Me|Cond16
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[Heals]
HealsOn=1
HealsSize=4
Heals1=Companion's Fortification|60|Pet
Heals2=Shield of the Elements|65|Me
Heals3=Renewal of Iilivina |50|Pet
Heals4=Mend Companion|40|Pet
HealsCOn=1

[DPS]
DPSOn=1
DPSSize=22
DPSSkip=0
DPSInterval=0
DPS1=Eradicate Magic|100|weave|Cond12
DPS2=command:/pet swarm|100|Once
DPS3=Malaise|100|weave|Cond1
DPS4=Summoned: Exigent Minion XXIV|100|Mob|weave|Cond7
DPS5=Summoned: Exigent Servant XXIV|100|Mob|weave|Cond7
DPS6=Roiling Servant|100
DPS7=Twincast|100|cond6
DPS8=Spear of Molten Luclinite|100
DPS9=Unmend the Unnatural|100|Cond25
DPS10=Chaotic Calamity|100
DPS11=Barrage of Many|100
DPS12=Force of Elements|100|weave|Cond26
DPS13=Thaumatize Pet|100|cond11
DPS14=Summoned: Dazzling Modulation Shard|100|Weave|cond2
DPS15=Sickle of Umbral Modulation|100|weave|cond2
DPS16=Summon Modulation Shard|100|weave|cond21
DPS17=Volcanic Veil|100|Ma|Cond22
DPS18=Molten Komatiite Orb|100|weave|Cond7
DPS19=Summoned: Frostbound Sliver|100|weave|Cond7
DPS20=Gather Vigor|100|Cond23
DPS21=Elemental Conversion|100|weave|Cond2
DPS22=Turn Summoned|100|weave|Cond24
DebuffAllOn=0
DPSCOn=1

[Burn]
BurnSize=9
BurnAllNamed=0
Burn1=Improved Twincast|Mob
Burn2=Heart of Skyfire|Mob
Burn3=Spire of Elements|Mob
Burn4=Servant of Ro|Mob
Burn5=Host of the Elements|Mob
Burn6=Focus of Arcanum|Mob
Burn7=${InvSlot[Chest].Item.Name}|Mob
Burn8=Companion's Fury|Mob
Burn9=Silent Casting|Mob

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Wind of Malaise|3
AE2=Companion of Necessity|4

[OhShit]
OhShitOn=0
OhShitCOn=1
OhShitBuff1=
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Conscription of Water
PetBuffsOn=1
PetBuffsSize=9
PetBuffs1=Iceflame Barricade
PetBuffs2=Host in the Shell
PetBuffs3=Burnout XV
PetBuffs4=Host in the Shell
PetBuffs5=Auspice of Kildrukaun
PetBuffs6=Second Wind Ward
PetBuffs7=Circle of Emberweave Coat
PetBuffs8=Volcanic Veil
PetBuffs9=Velocity
PetToysOn=1
PetToysSize=2
PetToys1=Grant Shak Dathor's Armaments|Summoned: Shadewrought Fireblade|Summoned: Shadewrought Fireblade
PetToys2=Grant Visor of Shoen
PetToysGave=Rossperot|Grant Shak Dathor's Armaments:Summoned: Shadewrought Fireblade1|Grant Shak Dathor's Armaments:Summoned: Shadewrought Fireblade2
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Cures]
CuresOn=1
CuresCOn=1
CuresBuff1=
CuresBuffCond1=


[Aggro]
AggroOn=1
AggroSize=3
Aggro1=Dimensional Shield|95|>
Aggro2=Arcane Whisper|95|>
Aggro3=Heart of Froststone|100|>

[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[SpellSet]
LoadSpellSet=2

[Spells]
Gem1=Twincast
Gem2=Call of the Heroes
Gem3=Roiling Servant
Gem4=Chaotic Calamity
Gem5=Spear of Molten Luclinite
Gem6=Barrage of Many
Gem7=Unmend the Unnatural
Gem8=Volcanic Veil
Gem9=Auspice of Kildrukaun
Gem10=Composite Companion
Gem11=Thaumatize Pet
Gem12=Gather Vigor
Gem13=Renewal of Iilivina


