; KAHybrid Source: 125 Druid - Laurion&#039;s Song DPS Based w/ light heals | https://www.redguides.com/community/resources/125-druid-laurions-song-dps-based-w-light-heals.3038/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_DRU.ini
; Preset: GROUP
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=99
MeleeOn=1
FaceMobOn=0
MeleeDistance=100
;StickHow=snaproll rear
StickHow=moveback 35% loose
AutoFireOn=0
UseMQ2Melee=0
TargetSwitchingOn=0
PetTauntOverride=0


[Buffs]
BuffsOn=1
BuffsSize=13
Buffs1=Emberquartz Blessing|Cond8
Buffs2=Mask of the Ferntender|me
Buffs3=Nature's Reaction|me
Buffs4=Emboldened Growth|Cond6
Buffs5=Talisman of the Unforgettable|Cond9
Buffs6=Second Life Rk. II|me
Buffs7=Summoned: Modulation Shard VIII|Mana|80|60|40
Buffs8=Mammoth's Force|melee|Cond14
Buffs9=Swarm of Fireflies|me|Cond11
Buffs10=Wrath of the Wild|melee|Cond10
Buffs11=${InvSlot[Charm].Item.Name}|Dual|Geomantra|Me
Buffs12=Striped Badger Whistle|dual|Summon Familiar: Striped Badger|cond12
Buffs13=Legacy of Bramblespikes|Cond7
;Will check to make sure MAG DS is not on in which case it will not cast
;Buffs14=Aged Eclipsed Mendicant's Cloak of the Selenelion|Cond13
;BuffsXX=Protection of Seasons
;BuffsXX=Chitin of the Reptile|melee
;BuffsXX=Nightspire Bulwark|Tank
;BuffsXX=Nightchill Aura|me|Aura
RebuffOn=1
CheckBuffsTimer=20
PowerSource=NULL
BuffOnJoin=1
Buffs10=NULL

BuffsCOn=1

[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
AutoRezOn=0
HealsSize=6
Heals1=Vivavida|75
Heals2=Lunacea|75
Heals3=Wildtender's Survival|30|Weave
Heals4=Spirit of the Bear|30|MT
Heals5=Blessing of Tunare|50
Heals6=Convergence of Spirits|40|MT
;HealsX=Nature's Boon|70|Cond4
HealGroupPetsOn=1
RezMeLast=0
HealInterval=0
RezCheckTimer=1
PetHealsOnly=0
PetHealInterval=1
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7

HealsCOn=1

[DPS]
DPSOn=1
DPSSize=15
DPSSkip=10
DPSInterval=20
DPS1=Twincast Rk. III|100
DPS2=Swarm of Fireflies|99|Tank
DPS3=Season's Wrath|99
DPS4=Blessing of Ro|99|Weave
DPS5=Horde of Hotaria|99|Cond16
DPS6=Searing Sunray|99
DPS7=Mythical Moonbeam|99
DPS8=Chill of the Ferntender|99|Cond16
DPS9=Nature's Boiling Wrath|99|Cond1
DPS10=Remote Sunscorch|99
DPS11=Ecliptic Winds|99
DPS12=Tempest Roar|99|Weave
DPS13=Sunscald|99|Cond1
DPS14=Winter's Wildgale|99
DPS15=Entrap|25
;DPS14=Nature's Fire|99|weave
;DPS15=Nature's Frost|99|weave
;DPS16=Nature's Bolt|99|weave
DebuffAllOn=0

DPSCOn=1

[Burn]
BurnAllNamed=0
UseTribute=0
BurnSize=18
Burn1=Silent Casting
Burn2=Spire of Nature
Burn3=Spirit of the Bear|MA
Burn4=Wrath of the Wild|MA
Burn5=${InvSlot[Chest].Item.Name}
Burn6=Nature's Blessing
Burn7=Nature's Boon
Burn8=Spirit of Nature
Burn9=Focus of Arcanum
Burn10=Blessing of Ro
Burn11=Season's Wrath
Burn13=Spirit of the Great Wolf
Burn14=Spirit of the Wood
Burn15=Destructive Vortex
Burn16=Improved Twincast
Burn17=Nature's Fury
Burn18=Nature's Guardian
Burn12=NULL
;BurnX=Distant Conflagration


[AE]
AEOn=0
AESize=3
AERadius=50
AE1=Spirit of the Wood|3
AE2=Spirit of the Great Wolf|4
AE3=Spirit of the Bear|3|MA


[OhShit]
OhShitOn=1
OhShitCOn=1
OhShitBuff1=Convergence of Spirits
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=0
PetSpell=Nature Walker's Behest
PetShrinkOn=0
PetShrinkSpell=Tiny Companion
PetBuffsOn=0
PetBuffsSize=8
PetBuffs1=NULL
PetBuffs2=NULL
PetBuffs3=NULL
PetBuffs4=NULL
PetBuffs5=NULL
PetBuffs6=NULL
PetBuffs7=NULL
PetBuffs8=NULL
PetCombatOn=1
PetAssistAt=95
PetAttackDistance=115
PetToysSize=6
PetBreakMezSpell=NULL
PetRampPullWait=0
PetSuspend=0
PetHoldOn=1
PetForceHealOnMed=0
PetToysGave=
PetFocus=NULL
PetShrunkSizeHelp=Stores the size of the pet when shrunk
PetShrunkSize=2.0
PetPullDistance=150
PetFocusOn=1
CheckPetBuffsTimer=5
BattleSummonPet=0
ReclaimHelp=Reclaim energy from pets with an item or spell, and the name of the pet spell.
ReclaimEnergyMethod=NULL
SacrificialPetSpell=NULL
PetAlwaysFollowOn=0
GivePetToyBags=0
PetLineOfSightOn=0
PetTauntOn=0
PetAllowTaunt=1
RequestPetToys=0
ProvidePetToys=0
MoveWhenHit=0


[Cures]
CuresOn=1
CuresSize=2
Cures1=Radiant Cure
Cures2=Purified Spirits
CheckCuresTimer=1

CuresCOn=1

[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Silent Casting|90|>
Aggro2=Veil of the Underbrush|100|>
Aggro3=NULL
Aggro4=NULL
Aggro5=NULL
AggroHelp=Use to lower or raise hate with a mob. Spell/Ability|pct hate|< gain/lose > aggro. E.g. Boggle|60|> or Taunt|100|<
MitigateHelp=Mitigate aggro: debuff, slow methods to handle loose mobs.
MitigateDebuff=null
MitigateSlow=null


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0
HelpPullManual=Enables you to use /pull at will rather than setting your role as puller.
PullManual=1
PullEscapeMethod=null
PullCampAdvanceHelp=Puller calls the group to them and continues pulling from the new camp
PullCampAdvanceOn=0
PullCampDistFromCamp=150
PullCampDistToMob=150


[PullAdvanced]
PullLocsOn=0


[Spells]
MiscGem=13
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=Kissassist
CastingInterruptOn=1
Gem1=Twincast
Gem2=Vivavida
Gem3=Lunacea
Gem4=Horde of Hotaria
Gem5=Chill of the Ferntender
Gem6=Nature's Boiling Wrath
Gem7=Remote Sunscorch
Gem8=Tempest Roar
Gem9=Sunscald
Gem10=Winter's Wildgale
Gem11=Searing Sunray
Gem12=Ecliptic Winds
Gem13=Mythical Moonbeam
HotSwapGem=0
CheckStuckGem=1


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92
MercAttackDistance=75


