; KAHybrid Source: 125 LS Fire Wizard | https://www.redguides.com/community/resources/125-ls-fire-wizard.2993/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L80_WIZ.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Wizard|80|GOLD
ChaseAssist=1
ChaseDistance=35
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=0
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=6
SwitchWithMA=FALSE
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0


[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist


[Buffs]
BuffsOn=1
BuffsSize=13
;Buffs1=Aegis of the Umbra
Buffs1=Improved Familiar
Buffs2=Pyromancy
Buffs3=Summoned: Modulation Shard VIII|mana|80|85
Buffs4=Wand of Pelagic Transvergence|mana|80|85
Buffs5=${InvSlot[Chest].Item.Name}|Mana|78
Buffs6=Anodyne Gambit|Mana|80
Buffs7=Harvest of Druzzil|Mana|75
Buffs8=Shield of Inevitability
Buffs9=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs10=Summon Familiar: Striped Badger|Remove
Buffs11=Etherealist's Unity|Dual|Shield of Shadows
Buffs12=Radiant Hawk Harness|Dual|Mount Blessing Ozah
Buffs13=Summon Mount: Radiant Hawk|Remove
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

BuffsCOn=1

[Melee]
AssistAt=99
MeleeOn=1
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
PetTauntOverride=0

[GoM]
GoMOn=1
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMCOn=0
GoMSize=0


[GMail]
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0
GMailSize=0


[AE]
AEOn=0
AESize=10
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL
AE4=NULL
AE5=NULL
AE6=NULL
AE7=NULL
AE8=NULL
AE9=NULL
AE10=NULL

[DPS]
DPSOn=1
DPSSize=31
DPSSkip=0
DPSInterval=0
; AA and always-use burns
DPS1=Twincast|98|cond8
DPS2=Staff of Phenomenal Power|99
DPS3=Spire of Arcanum|99
DPS4=Ecliptic Fire|99|cond10
; Rotation Part 1
DPS5=Shadebright Vortex|99
DPS6=null
;Thricewoven Effulgence|99
DPS7=Claw of Ingot|99
DPS8=Force of Flame|99|weave
DPS9=Force of Ice|99|weave
DPS10=Force of Will|99|weave
; Rotation Part 2
DPS11=Shadebright Vortex|98
DPS12=null
;Thricewoven Effulgence|98
DPS13=Claw of Ingot|98
DPS14=Ethereal Immolation|98|cond5
DPS15=Ethereal Plait|98|cond5
DPS16=Ethereal Freeze|98|cond6
DPS17=Ethereal Blitz|98|cond7
DPS18=Force of Flame|99|weave
DPS19=Force of Ice|99|weave
DPS20=Force of Will|99|weave
; Rotation Part 3
DPS21=Shadebright Vortex|97
DPS22=null
;Thricewoven Effulgence|97
DPS23=Claw of Ingot|97
DPS24=Ethereal Immolation|97
DPS25=Ethereal Plait|97
DPS26=Kindleheart's Fire|97
DPS27=Flashroast|97
DPS28=Force of Flame|99|weave
DPS29=Force of Ice|99|weave
DPS30=Force of Will|99|weave
DPS31=Summoned: Modulation Shard VIII|99|Cond11
DebuffAllOn=0

DPSCOn=1

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierPull=Blunt
BandolierSize=0


[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=4

# Only use if my health is under 50% and my target is targeting me
OhShit1=Mind Crash|Mob
OhShitCond1=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}
# Only use if my health is under 50% and my target is targeting me
OhShit2=Dimensional Shield
OhShitCond2=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}
# Only use if my health is under 50% and my target is targeting me
OhShit3=Arcane Whisper|Mob
OhShitCond3=${Me.PctHPs} < 50 && ${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Only use if my health is under 50%
OhShit4=Silent Casting|
OhShitCond4=${Me.PctHPs} < 50


[Aggro]
AggroOn=1
AggroSize=5
Aggro1=Concussion|10|>|Mob
Aggro2=Concussive Intuition|40|>|Mob
Aggro3=Arcane Whisper|70|>|Mob
Aggro4=Mind Crash|100|>|Mob
Aggro5=Dimensional Shield|100|>


[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
HealInterval=0
AutoRezOn=0
HealsSize=5
Heals1=NULL
Heals2=NULL
Heals3=NULL
Heals4=NULL
Heals5=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=NULL
Cures2=NULL
Cures3=NULL
Cures4=NULL
Cures5=NULL
CuresCOn=1

[Pet]
PetOn=0
PetSpell=YourPetSpell
PetFocus=NULL
PetShrinkOn=0
PetShrinkSpell=Tiny Companion
PetBuffsOn=0
PetBuffsSize=8
PetBuffs1=NULL
PetBuffs2=NULL
PetBuffs3=NULL
PetBuffs4=NULL
PetBuffs5=NULL
PetBuffs6=NULL
PetBuffs7=NULL
PetBuffs8=NULL
PetCombatOn=1
PetAssistAt=95
PetAttackDistance=115
PetToysSize=6
PetBreakMezSpell=NULL
PetRampPullWait=0
PetSuspend=0
MoveWhenHit=0
PetHoldOn=1
PetForceHealOnMed=0

[Burn]
BurnSize=8
BurnAllNamed=1
Burn1=Fury of the Gods
Burn2=Frenzied Devastation
Burn3=Silent Casting
Burn4=Arcane Fury
Burn5=Focus of Arcanum
Burn6=Improved Twincast
Burn7=Call of Xuzl
Burn8=Thricewoven Effulgence|99
UseTribute=0


[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92

[PullAdvanced]
PullLocsOn=0

[Spells]
Gem1=Claw of Ingot
Gem2=Ethereal Immolation
Gem3=Ecliptic Fire
Gem4=Ethereal Plait
Gem5=Twincast
Gem6=Anodyne Gambit
Gem7=Shadebright Vortex
Gem8=Thricewoven Effulgence
Gem9=Ethereal Freeze
Gem10=Kindleheart's Fire
Gem11=Flashroast
Gem12=Ethereal Blitz
Gem13=Contemplative Harvest
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1


