; Source class template: UltimateEQAssist_L25_BER.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Bloodlust Aura|Aura
Buffs2=Axe of the Annihilator|Summon|Axe of the Annihilator|100
Buffs3=Deathfury Axe|Summon|Deathfury Axe|100
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Cleaving Anger Discipline|2
AE2=Vengeful Flurry Discipline|3

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=0
DPSInterval=2
DPS1=Mind Strike|99
DPS2=Kick|99
DPS3=Tendon Cleave|99
DPS4=Annihilator's Volley|99
DPS5=Battle Cry of Mastruq|99
DPS6=Cry Havok|99
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Healing Will Discipline|30|Me
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=1
Burn1=Cleaving Anger Discipline
Burn2=Desperation

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Cures]
CuresOn=0
CuresCOn=0
