; Source class template: UltimateEQAssist_L25_SHD.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=12.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Grim Aura
Buffs2=Endure Cold
Buffs3=Vampiric Embrace
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=6
DPSSkip=20
DPSInterval=2
DPS1=Disease Cloud|98
DPS2=Scream of Pain|95
DPS3=Lifespike|75|cond3
DPS4=Spike of Disease|70
DPS5=Engulfing Darkness|65
DebuffAllOn=0
DPSCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Cure Disease|disease
CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Convoke Shadow
PetBuffsOn=0
PetBuffsSize=5
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=5
BurnAllNamed=0

[GoM]
GoMSize=1

[KConditions]
ConOn=1
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=${Me.PctHPs} < 75
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Spike of Disease
Gem2=Disease Cloud
Gem3=Lifespike
Gem4=Scream of Pain
Gem5=Engulfing Darkness
Gem6=Feign Death
Gem7=Convoke Shadow
Gem8=Grim Aura
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Heals]
HealsOn=0
HealsCOn=0
