; Source class template: UltimateEQAssist_L70_RNG.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Storm Strength
Buffs2=Strength of The Hunter
Buffs3=Hunter's Vigor
Buffs4=Ward of the Hunter
Buffs5=Howl of the Predator
Buffs7=Call of Lightning
Buffs8=Mask of the Stalker
Buffs9=Shield of Needles|MA
Buffs10=Onyx Skin|MA
Buffs11=Pack Shrew
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=0
DPSInterval=2
DPS1=Frost Wind|99
DPS2=Scorthed Earth|99
DPS3=Earthen Shackles|50|Once
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Sunderock Springwater|20
HealsCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0
Burn1=Guardian of the Forest

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Storm Strength
Gem2=Frost Wind
Gem3=Sunderock Springwater
Gem4=Strength of The Hunter
Gem5=Earthen Shackles
Gem6=Mask of the Stalker
Gem7=Call of Lightning
Gem8=Howl of the Predator
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Cures]
CuresOn=0
CuresCOn=0
