; Source class template: UltimateEQAssist_L70_CLR.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Aura of Devotion|Me
Buffs2=Armor of the Pious|Me
Buffs3=Hand of Conviction|Me
Buffs4=Rod of Mystical Transvergence|Mana|80
Buffs5=!Panoply of Vie|Me|Combat
Buffs6=!Divine Intervention|MA
RebuffOn=1
CheckBuffsTimer=1
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Exquisite Benediction|4|me
AE2=Silent Casting|4

[Heals]
HealsOn=1
HealsSize=15
Heals1=Pious Elixir|90|class|sk
Heals2=Ancient: Hallowed Light|60
Heals3=Divine Arbitration|30|MA
Heals4=!Aegis of Superior Divinity|40|MA
Heals5=Pious Remedy|80
Heals6=!Pious Remedy|99|MA
Heals7=Bestow Divine Aura Azia|25
AutoRezOn=1
AutoRezWith=Reviviscence
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Radiant Cure
Cures2=Remove Greater Curse|Curse
Cures3=Antidote|Poison
Cures4=Earring of Purity|Diseases
CuresCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0
Burn1=Exquisite Benediction|cond1
Burn2=Celestial Hammer
Burn3=Celestial Regeneration|cond2

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=${Me.AltAbilityReady[Exquisite Benediction]} && ${SpawnCount[Call of the Ancients]}<1 && ${SpawnCount[Nature's Boon]}<1 && ${SpawnCount[Exquisite Benediction]}<1
Cond2=${Me.AltAbilityReady[Celestial Regeneration]} && ${Spawn[ID ${Group.MainAssist.ID}].PctHPs} < 35
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[DPS]
DPSOn=0
DPSCOn=0
