; Source class template: UltimateEQAssist_L70_BST.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=35

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Spiritual Ascendance|Me
Buffs2=Ferocity of Irionu|Class|Mnk,Ber
Buffs3=Paragon of Spirit|Managroup|70
Buffs4=Rod of Mystical Transvergence|Mana|80
Buffs5=Spiritual Vitality|melee
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=50
AE1=Bestial Fury Discipline

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=1
DPS1=Sha's Legacy|98|debuffall|slow|always
DPS2=Ancient: Savage Ice|90
DPS3=!Festering Malady|95|Once
DebuffAllOn=1
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Muada's Mending|50
Heals2=Healing of Mikkily|30|Pet
Heals3=Mend Companion|40|Pet
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Spirit of Rashara
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Spirit of Irionu
PetBuffs2=Growl of the Beast
PetBuffs3=Hobble of Spirits
PetBuffs4=Spiritcaller Totem of the Feral
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=15
BurnAllNamed=0
Burn1=Bestial Empathy
Burn2=Bestial Fury Discipline
Burn3=Bestial Alignment
Burn4=Roar of Thunder
Burn5=Frenzy Spirit
Burn6=Ancient: Savage Ice

[GoM]
GoMSize=3

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Cures]
CuresOn=0
CuresCOn=0
