; Source class template: UltimateEQAssist_L70_WIZ.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=9
Buffs1=Ether Shield
Buffs2=Elemental Barrier
Buffs3=Greater Familiar
Buffs4=Harvest|Mana|50
Buffs5=Reflect
Buffs6=Ether Skin
Buffs7=Bulwark of Calrena|me
Buffs8=Spellshield
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Gelid Rains|3

[DPS]
DPSOn=1
DPSSize=6
DPSSkip=20
DPSInterval=2
DPS1=Solist's Frozen Sword|98
DPS2=Thundaka|80
DPS3=Corona Flare|70
DPS4=Gelidin Comet|65
DPS5=Atol's Spectral Shackles|25
DebuffAllOn=0
DPSCOn=1

[Aggro]
AggroOn=1
AggroSize=2
Aggro1=Concussion|55|>

[Burn]
BurnSize=5
BurnAllNamed=1
Burn1=Thundaka
Burn2=Gelidin Comet
Burn3=Concussion
Burn4=Corona Flare

[GoM]
GoMSize=2
GoMSpell1=Corona Flare

[KConditions]
ConOn=0
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Thundaka
Gem2=Corona Flare
Gem3=Concussion
Gem4=Gelidin Comet
Gem5=Harvest
Gem6=Teleport
Gem7=Atol's Spectral Shackles
Gem8=Solist's Frozen Sword
Gem9=Gelid Rains
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL

[Heals]
HealsOn=0
HealsCOn=0

[Cures]
CuresOn=0
CuresCOn=0
