return {
	['inputBuffer'] = '',
	['snippets'] = {
		[1] = {
			['name'] = 'Combat: List active AAs',
			['code'] = 'local me = T.Me\nfor i = 1, 500 do\n    local aa = me.AltAbility(i)\n    if aa() and me.AltAbilityReady(i)() then\n        print(i, aa.Name(), \'ready\')\n    end\nend\n',
		},
		[2] = {
			['name'] = 'Merc: state + target',
			['code'] = 'print(\'MercState:\', T.Me.Mercenary.State())\nprint(\'MercTarget:\', T.Me.Mercenary.Target.CleanName())\nprint(\'MercPctHP:\', T.Me.Mercenary.PctHPs())\n',
		},
		[3] = {
			['name'] = 'Nav: path status',
			['code'] = 'print(\'Nav Active:\', T.Navigation.Active())\nprint(\'Nav Paused:\', T.Navigation.Paused())\nprint(\'Nav PathExists:\', T.Navigation.PathExists())\nprint(\'Nav Distance:\', T.Navigation.PathLength())\n',
		},
		[4] = {
			['name'] = 'UI: chat window check',
			['code'] = 'print(\'ChatWnd Open:\', T.Window[\'ChatWindow\'].Open())\nprint(\'MainChat Open:\', T.Window[\'MainChatWnd\'].Open())\n',
		},
		[5] = {
			['name'] = 'Utility: inventory slots',
			['code'] = 'for i = 1, 34 do\n    local item = T.Me.Inventory(i)\n    if item() then\n        print(i, item.Name(), item.Stack())\n    end\nend\n',
		},
		[6] = {
			['name'] = 'Target: buff timers',
			['code'] = 'if not T.Target() then print(\'No target.\') return end\nfor i = 1, 97 do\n    local b = T.Target.Buff(i)\n    if b() then print(i, b.Name(), b.Duration.TimeHMS()) end\nend\n',
		},
		[7] = {
			['name'] = 'Group: HP snapshot',
			['code'] = 'for i = 1, 6 do\n    local m = T.Group.Member(i)\n    if m() then\n        print(i, m.CleanName(), m.PctHPs(), m.Class.ShortName())\n    end\nend\n',
		},
		[8] = {
			['name'] = 'Spawn: nearest named',
			['code'] = 'local s = T.Spawn(\'npc named radius 200\')\nprint(\'Nearest named:\', s.CleanName(), \'Dist:\', s.Distance())\n',
		},
		[9] = {
			['name'] = 'Buffs: self long buffs',
			['code'] = 'for i = 1, 42 do\n    local b = T.Me.Buff(i)\n    if b() then print(i, b.Name(), b.Duration.TimeHMS()) end\nend\n',
		},
		[10] = {
			['name'] = 'Debug: zone + spawn count',
			['code'] = 'print(\'Zone:\', T.Zone.ShortName(), T.Zone.ID())\nprint(\'SpawnCount:\', T.SpawnCount())\n',
		},
	},
	['logFilter'] = 'Show All',
	['logSearch'] = '',
	['history'] = {},
	['chatModeEnabled'] = false,
	['chatEvalToken'] = '!',
	['slowEvalWarnMs'] = 75,
	['watches'] = {},
	['watchIntervalMs'] = 250,
	['currentTab'] = 'Console',
	['triggers'] = {},
	['openSections'] = {
		['systems'] = true,
		['snippets'] = true,
		['triggers'] = true,
		['watches'] = true,
		['inspect'] = true,
		['events'] = true,
		['perf'] = true,
	},
	['debug'] = false,
	['theme'] = 'maui_gold',
	['themeIndex'] = 1,
	['layoutPreset'] = 'default',
	['topLogRatio'] = 0.58,
	['windowState'] = {
		['y'] = 128,
		['w'] = 1227,
		['h'] = 760,
		['collapsed'] = false,
		['x'] = 664,
	},
	['autocompleteEnabled'] = true,
	['autoSaveEnabled'] = true,
	['autoSaveIntervalMs'] = 30000,
	['remoteEvalEnabled'] = true,
	['remoteEvalIntervalMs'] = 1000,
	['plots'] = {},
	['nextPlotId'] = 1,
	['plotIntervalMs'] = 250,
	['allowUnsafeMqEnv'] = false,
	['usePerCharacterFiles'] = true,
	['selectedSnippet'] = 0,
	['nextTriggerId'] = 1,
	['nextWatchId'] = 1,
	['triggerIntervalMs'] = 150,
	['showUI'] = true,
	['autoscroll'] = true,
	['showTimestamps'] = true,
	['macroSync'] = {},
	['nextMacroSyncId'] = 1,
}