local liveGuides = {}

liveGuides.lines = {
    [=[Live Guide and NPC Import (from liurnia API)]=],
    [=[]=],
    [=[Snapshot Date: 2026-04-22]=],
    [=[API sections detected: 16]=],
    [=[Total indexed entities: items 120705, spells 42659, npcs 1430]=],
    [=[]=],
    [=[Guide section keys:]=],
    [=[- aa_ranks]=],
    [=[- getting_started_guides]=],
    [=[- player_commands]=],
    [=[- progression_guides]=],
    [=[- progression_requirements]=],
    [=[- quest_canon]=],
    [=[- quest_guides]=],
    [=[- specializations]=],
    [=[- spell_scrolls]=],
    [=[- spells]=],
    [=[- spells_forge_progression]=],
    [=[- system_guides]=],
    [=[- talents]=],
    [=[- ultimate_item_catalog]=],
    [=[- zone_npc_guides]=],
    [=[- zones]=],
    [=[]=],
    [=[Core progression NPC guides: 4]=],
    [=[- Mel [guildlobby] script guildlobby/Mel.pl]=],
    [=[- Herald [guildlobby] script guildlobby/Herald.pl]=],
    [=[- Quake [guildlobby] script guildlobby/Quake.pl]=],
    [=[- Seism [guildlobby] script guildlobby/Seism.pl]=],
    [=[]=],
    [=[Getting-started guides: 7]=],
    [=[- Juggernaut [guildlobby] script guildlobby/Juggernaut.pl]=],
    [=[- Mel [tutorial] script tutorial/Mel.pl]=],
    [=[- Juggernaut [tutorial] script tutorial/Juggernaut.pl]=],
    [=[- Trader Baggins [tutorial] script tutorial/Trader_Baggins.pl]=],
    [=[- Quake [tutorial] script tutorial/Quake.pl]=],
    [=[- Jenna [tutorial] script tutorial/Jenna.pl]=],
    [=[- Herald [tutorial] script tutorial/Herald.pl]=],
    [=[]=],
    [=[Quest guide NPCs: 12]=],
    [=[- A Mysterious Avatar [sleeper] script sleeper/A_Mysterious_Avatar.pl]=],
    [=[- Weasel The Redeemer [templeveeshan] script templeveeshan/Weasel_the_Redeemer.pl]=],
    [=[- Farnsworth [velketor] script velketor/Farnsworth.pl]=],
    [=[- Curious Gnome Zombie [hole] script hole/Curious_Gnome_Zombie.pl]=],
    [=[- The Keymaster [oot] script oot/2000185.pl]=],
    [=[- Arch Magus Phil [oot] script oot/Arch_Magus_Phil.pl]=],
    [=[- Cloud [oot] script oot/2000195.pl]=],
    [=[- Herald Of Guk [guktop] script guktop/Herald_of_Guk.pl]=],
    [=[- Herald Of Guk [gukbottom] script gukbottom/Herald_of_Guk.pl]=],
    [=[- A Mysterious Avatar [tutorial] script tutorial/A_Mysterious_Avatar.pl]=],
    [=[- Arch Magus Phil [guildlobby] script guildlobby/Arch_Magus_Phil.pl]=],
    [=[- Maester Aemon [tutorial] script tutorial/Maester_Aemon.pl]=],
    [=[]=],
    [=[Zone NPC guide records: 62]=],
    [=[- Curious Gnome Remains [blackburrow] script blackburrow/Curious_Gnome_Remains.pl]=],
    [=[- Forge [blackburrow] script blackburrow/Forge.pl]=],
    [=[- Forge [blackburrow] script blackburrow/Forge_.pl]=],
    [=[- Measel [blackburrow] script blackburrow/Measel.pl]=],
    [=[- Measel [blackburrow] script blackburrow/Measel_.pl]=],
    [=[- Deasel [blackburrow] script blackburrow/deasel.pl]=],
    [=[- Herald Of Guk [guktop] script guktop/Herald_of_Guk.pl]=],
    [=[- Herald Of Guk [gukbottom] script gukbottom/Herald_of_Guk.pl]=],
    [=[- Forge [templeveeshan] script templeveeshan/Forge.pl]=],
    [=[- Forge [templeveeshan] script templeveeshan/Forge_.pl]=],
    [=[- Forge The Hardcore [templeveeshan] script templeveeshan/Forge_the_Hardcore.pl]=],
    [=[- Weasel [templeveeshan] script templeveeshan/Weasel.pl]=],
    [=[- Weasel [templeveeshan] script templeveeshan/Weasel_.pl]=],
    [=[- Weasel The Hardcore [templeveeshan] script templeveeshan/Weasel_the_Hardcore.pl]=],
    [=[- Weasel The Hardcore Redeemer [templeveeshan] script templeveeshan/Weasel_the_Hardcore_Redeemer.pl]=],
    [=[- Weasel The Redeemer [templeveeshan] script templeveeshan/Weasel_the_Redeemer.pl]=],
    [=[- A Mysterious Avatar [sleeper] script sleeper/A_Mysterious_Avatar.pl]=],
    [=[- Forge [sleeper] script sleeper/Forge.pl]=],
    [=[- Forge [sleeper] script sleeper/Forge_.pl]=],
    [=[- Forge The Hardcore [sleeper] script sleeper/Forge_the_Hardcore.pl]=],
    [=[- Forge [kael] script kael/Forge.pl]=],
    [=[- Forge The Hardcore [kael] script kael/Forge_the_Hardcore.pl]=],
    [=[- Kragek Thunderforge [kael] script kael/Kragek_Thunderforge.pl]=],
    [=[- The Avatar Of War [kael] script kael/The_Avatar_of_War.pl]=],
    [=[- Forge [kael] script kael/forge_.pl]=],
    [=[- Forge [veeshan] script veeshan/Forge.pl]=],
    [=[- Forge [veeshan] script veeshan/Forge_.pl]=],
    [=[- Measel [veeshan] script veeshan/Measel.pl]=],
    [=[- Deasel [veeshan] script veeshan/deasel.pl]=],
    [=[- Curious Gnome Remains [mistmoore] script mistmoore/Curious_Gnome_Remains.pl]=],
    [=[- Forge [mistmoore] script mistmoore/Forge.pl]=],
    [=[- Forge [mistmoore] script mistmoore/Forge_.pl]=],
    [=[- Measel [mistmoore] script mistmoore/Measel.pl]=],
    [=[- Measel [mistmoore] script mistmoore/Measel_.pl]=],
    [=[- Deasel [mistmoore] script mistmoore/deasel.pl]=],
    [=[- Curious Gnome Remains [soldunga] script soldunga/Curious_Gnome_Remains.pl]=],
    [=[- Forge [soldunga] script soldunga/Forge.pl]=],
    [=[- Forge [soldunga] script soldunga/Forge_.pl]=],
    [=[- Measel [soldunga] script soldunga/Measel.pl]=],
    [=[- Measel [soldunga] script soldunga/Measel_.pl]=],
    [=[- Deasel [soldunga] script soldunga/deasel.pl]=],
    [=[- Curious Gnome Zombie [hole] script hole/Curious_Gnome_Zombie.pl]=],
    [=[- Forge [hole] script hole/Forge.pl]=],
    [=[- Forge [hole] script hole/Forge_.pl]=],
    [=[- Measel [hole] script hole/Measel.pl]=],
    [=[- Measel [hole] script hole/Measel_.pl]=],
    [=[- Deasel [hole] script hole/deasel.pl]=],
    [=[- Forge [frozenshadow] script frozenshadow/Forge.pl]=],
    [=[- Forge [frozenshadow] script frozenshadow/Forge_.pl]=],
    [=[- Deasel [frozenshadow] script frozenshadow/deasel.pl]=],
    [=[- Farnsworth [velketor] script velketor/Farnsworth.pl]=],
    [=[- Forge [velketor] script velketor/Forge.pl]=],
    [=[- Forge [velketor] script velketor/forge_.pl]=],
    [=[- The Keymaster [oot] script oot/2000185.pl]=],
    [=[- Cloud [oot] script oot/2000195.pl]=],
    [=[- ootplayercounter [oot] script oot/2000213.pl]=],
    [=[- Arch Magus Phil [oot] script oot/Arch_Magus_Phil.pl]=],
    [=[- Arch Magus Phil [oot] script oot/Arch_Magus_Phil_.pl]=],
    [=[- Forge [oot] script oot/Forge.pl]=],
    [=[- Forge [oot] script oot/Forge_.pl]=],
    [=[]=],
    [=[Lookup URLs (replace placeholders):]=],
    [=[- https://www.liurnia.com/ultimateeq/items/<item_id>]=],
    [=[- https://www.liurnia.com/ultimateeq/spells/<spell_id>]=],
    [=[- https://www.liurnia.com/ultimateeq/npcs/<npc_uid>]=],
    [=[- https://www.liurnia.com/ultimateeq/guide]=],
}

return liveGuides
