local liveItemIds = {}

liveItemIds.lines = {
    [=[Live Progression Item IDs (from progression_requirements)]=],
    [=[]=],
    [=[Snapshot Date: 2026-04-22]=],
    [=[Progression requirement entries: 25]=],
    [=[]=],
    [=[- [Pre-Ultimate] Vanilla Progression]=],
    [=[  - Nagafen's Head [ID 147528] zone soldungb target Lord Nagafen]=],
    [=[  - Innoruuk's Brain [ID 147533] zone hateplane target Innoruuk]=],
    [=[  - Cazic Thule's Eye [ID 147532] zone fearplane target Cazic Thule]=],
    [=[  - Ultimate Charm [ID 1079] zone n/a target n/a]=],
    [=[- [Pre-Ultimate] Kunark Progression]=],
    [=[  - Trakanon's Tail [ID 147531] zone sebilis target Trakanon]=],
    [=[  - Phara'Dars' Tooth [ID 147534] zone veeshan target Phara Dar]=],
    [=[  - Venril Sathir's Belt [ID 147535] zone karnor target Venril Sathir]=],
    [=[  - Ultimate Charm - Tier 1 [ID 147536] zone n/a target n/a]=],
    [=[- [Pre-Ultimate] Velious Progression]=],
    [=[  - The Statue's Helmet [ID 147540] zone kael target The Statue of Rallos Zek]=],
    [=[  - Tunare's Torn Dress [ID 147541] zone growthplane target Tunare]=],
    [=[  - Vulak's Scale [ID 147542] zone templeveeshan target Vulak`Aerr]=],
    [=[  - Ultimate Charm - Tier 2 [ID 147537] zone n/a target n/a]=],
    [=[- [Pre-Ultimate] Luclin Progression]=],
    [=[  - Emperor Ssra's Idol [ID 147543] zone ssratemple target Emperor Ssraeshza]=],
    [=[  - Aten's Ring [ID 147544] zone vexthal target Aten Ha Ra]=],
    [=[  - Grieg's Torn Parchment [ID 147545] zone griegsend target Grieg Veneficus]=],
    [=[  - Ultimate Charm - Tier 3 [ID 147538] zone n/a target n/a]=],
    [=[- [Pre-Ultimate] Planes of Power Progression]=],
    [=[  - Rallos Zek's Axe [ID 147636] zone potactics target Rallos Zek the Warlord]=],
    [=[  - Solusek's Burning Staff [ID 147637] zone solrotower target Solusek Ro]=],
    [=[  - Fennin Ro's Burning Boots [ID 147638] zone pofire target Fennin Ro the Tyrant of Fire]=],
    [=[  - Ultimate Charm - Tier 4 [ID 147539] zone n/a target n/a]=],
    [=[- [Ultimate] Ultimate Rank 1 Access]=],
    [=[  - Heart of Crush the Transformed [ID 147639] zone crushbone target Crush the Transformed]=],
    [=[- [Ultimate] Ultimate Rank 2 Access]=],
    [=[  - Ghoul Lord's Head [ID 147800] zone gukbottom target lord]=],
    [=[  - Froglok King's Head [ID 147801] zone gukbottom target king]=],
    [=[  - Shin Lord's Head [ID 147802] zone guktop target shin lord]=],
    [=[  - Ancient Croc's Head [ID 147803] zone guktop target an ancient croc]=],
    [=[- [Ultimate] Ultimate Rank 3 Access]=],
    [=[  note: Requires your Ultimate Legendary weapon (no direct item turn-in to Mel).]=],
    [=[- [Ultimate] Ultimate Rank 4 Access]=],
    [=[  - Ultimate Vulak's Scale [ID 148099] zone templeveeshan target Vulak`Aerr]=],
    [=[- [Ultimate] Ultimate Rank 5 Access]=],
    [=[  - Ultimate Kael Completion Pass [ID 148165] zone kael target The Avatar of War]=],
    [=[- [Avatar] Avatar Rank 1 Access]=],
    [=[  note: Also requires Rank 6 charm completion.]=],
    [=[  - Ultimate Kerafyrm's Scale [ID 149860] zone sleeper target Kerafyrm]=],
    [=[- [Avatar] Avatar Rank 2 Access]=],
    [=[  - Mayong's Head [ID 148563] zone mistmoore target Mayong]=],
    [=[  - Fippy's Head [ID 148564] zone blackburrow target Fippy]=],
    [=[  - Goblin King's Head [ID 148565] zone soldunga target Solusek goblin king]=],
    [=[- [Avatar] Avatar Rank 3 Access]=],
    [=[  note: Zone unlock to Tower of Frozen Shadow also requires Rank 7 charm completion.]=],
    [=[  - An Earthen Soulstone [ID 148605] zone hole target Master Yael]=],
    [=[- [Avatar] Avatar Rank 4 Access]=],
    [=[  - Frozen Avatar Energy [ID 148807] zone frozenshadow target Tserrina]=],
    [=[- [Demigod] Demigod Rank 1 Access]=],
    [=[  note: Demigod unlock also requires Rank 8 charm completion.]=],
    [=[  - Heart of the Peak [ID 148973] zone veeshan target Phara Dar]=],
    [=[- [Demigod] Demigod Rank 2 Access]=],
    [=[  note: Plane of Fear unlock also requires Rank 9 charm and Ultimate 2.0 completion.]=],
    [=[  - Coalesced Demigod Energy [ID 149050] zone oot target Kizdean Gix]=],
    [=[  - Ultimate Unrest Commendation [ID 149241] zone chambersa target Ultimate Weasel the Dread]=],
    [=[- [Demigod] Demigod Rank 3 Access]=],
    [=[  - A Freshly Severed Head [ID 149257] zone fearplane target n/a]=],
    [=[- [Demigod] Demigod Rank 4 Access]=],
    [=[  note: Goblin Vault unlock also requires Rank 10 charm completion.]=],
    [=[  - Velketorian Essence [ID 149391] zone velketor target Velketor the Sorcerer]=],
    [=[- [God] God Rank 1 Access]=],
    [=[  - Realm of the Gods Commendation [ID 149453] zone brellsarena target Harbinger of Dread]=],
    [=[- [God] God Rank 2 Access]=],
    [=[  - Abomination Head [ID 150048] zone crystallos target Kerafyrm]=],
    [=[- [Charm Progression] Ultimate Charm Rank 6]=],
    [=[  - Ultimate Charm Upgrade Token (Rank 6) [ID 148330] zone lakerathe target Ancient Megalodon]=],
    [=[- [Charm Progression] Ultimate Charm Rank 7]=],
    [=[  - Coalesced Avatar Energy [ID 148606] zone hole target Guardian of the Seal]=],
    [=[  - Ultimate Charm - Tier 6 [ID 148331] zone n/a target n/a]=],
    [=[- [Charm Progression] Ultimate Charm Rank 8]=],
    [=[  - Ultimate Veeshan's Peak Artifact (Charm) [ID 148968] zone veeshan target Phara Dar]=],
    [=[  - Ultimate Charm - Tier 7 [ID 148566] zone n/a target n/a]=],
    [=[- [Charm Progression] Ultimate Charm Rank 9]=],
    [=[  - Soul-Essence of Mata Muram [ID 149123] zone oot target Overlord Mata Muram]=],
    [=[  - Ultimate Charm - Tier 8 [ID 148881] zone n/a target n/a]=],
    [=[- [Charm Progression] Ultimate Charm Rank 10]=],
    [=[  - Glinting Velketorian Shard [ID 149392] zone velketor target Lord Doljonijiarnimorinar]=],
    [=[  - Ultimate Charm - Tier 9 [ID 149124] zone n/a target n/a]=],
    [=[]=],
    [=[Full catalog quick URL: https://www.liurnia.com/ultimateeq/items?scope=ultimate&dropSourceMode=custom]=],
}

return liveItemIds
