local localNpcGuides = {}

localNpcGuides.lines = {
    [=[Local Imported NPC + Guide Index (Hardcoded)]=],
    [=[]=],
    [=[Source: C:\\Users\\E9ine\\Downloads\\ultihelp\\*.pl + *.md]=],
    [=[Perl scripts: 48]=],
    [=[Markdown guides: 27]=],
    [=[]=],
    [=[NPC guide markdown records:]=],
    [=[- Aftershock [Guild Lobby/guildlobby] (aftershock.md)]=],
    [=[- Arcane Translocator [Guild Lobby/guildlobby] (arcane-translocator.md)]=],
    [=[- Arch Magus Phil [Guild Lobby/guildlobby] (arch-magus-phil.md)]=],
    [=[- Crumble [Guild Lobby/guildlobby] (crumble.md)]=],
    [=[- Cyan [Guild Lobby/guildlobby] (cyan.md)]=],
    [=[- Donald [Guild Lobby/guildlobby] (donald.md)]=],
    [=[- Doug [Guild Lobby/guildlobby] (doug.md)]=],
    [=[- Fleb [Guild Lobby/guildlobby] (fleb.md)]=],
    [=[- Flex [Guild Lobby/guildlobby] (flex.md)]=],
    [=[- Forge [Guild Lobby/guildlobby] (forge.md)]=],
    [=[- Harbinger of Dread [Guild Lobby/guildlobby] (harbinger-of-dread.md)]=],
    [=[- Herald [Guild Lobby/guildlobby] (herald.md)]=],
    [=[- Illuminous [Guild Lobby/guildlobby] (illuminous.md)]=],
    [=[- John [Guild Lobby/guildlobby] (john.md)]=],
    [=[- Locke [Guild Lobby/guildlobby] (locke.md)]=],
    [=[- Max [Guild Lobby/guildlobby] (max.md)]=],
    [=[- Mel [Guild Lobby/guildlobby] (mel.md)]=],
    [=[- Quake [Guild Lobby/guildlobby] (quake.md)]=],
    [=[- Relm [Guild Lobby/guildlobby] (relm.md)]=],
    [=[- Rock [Guild Lobby/guildlobby] (rock.md)]=],
    [=[- Ronald [Guild Lobby/guildlobby] (ronald.md)]=],
    [=[- Rumble [Guild Lobby/guildlobby] (rumble.md)]=],
    [=[- Seism [Guild Lobby/guildlobby] (seism.md)]=],
    [=[- Smack [Guild Lobby/guildlobby] (smack.md)]=],
    [=[- Tiny [Guild Lobby/guildlobby] (tiny.md)]=],
    [=[- Trent [Guild Lobby/guildlobby] (trent.md)]=],
    [=[- Weasel [Guild Lobby/guildlobby] (weasel.md)]=],
    [=[]=],
    [=[Quest script files:]=],
    [=[- 2000053.pl]=],
    [=[- 2000171.pl]=],
    [=[- 2000226.pl]=],
    [=[- A_Goblin_Treasure_Hoarder.pl]=],
    [=[- A_Goblin_Treasure_Master.pl]=],
    [=[- A_Goblin_Treasure_Picker.pl]=],
    [=[- A_Goblin_Treasure_Snatcher.pl]=],
    [=[- Aftershock.pl]=],
    [=[- Arcane_Translocator.pl]=],
    [=[- arch_magus_chuck.pl]=],
    [=[- Arch_Magus_Phil.pl]=],
    [=[- cheapskate.pl]=],
    [=[- Crumble.pl]=],
    [=[- Cyan.pl]=],
    [=[- Donald.pl]=],
    [=[- Doug.pl]=],
    [=[- Fleb.pl]=],
    [=[- Flex.pl]=],
    [=[- Foreshock.pl]=],
    [=[- Forge.pl]=],
    [=[- god_talents.pl]=],
    [=[- Harbinger_of_Dread.pl]=],
    [=[- Herald.pl]=],
    [=[- Illuminous.pl]=],
    [=[- Jackson.pl]=],
    [=[- Jenkins.pl]=],
    [=[- John.pl]=],
    [=[- Juggernaut.pl]=],
    [=[- lobby_pvp_trigger.pl]=],
    [=[- Locke.pl]=],
    [=[- mack.pl]=],
    [=[- Max.pl]=],
    [=[- Mel.pl]=],
    [=[- player.pl]=],
    [=[- Quake.pl]=],
    [=[- Relm.pl]=],
    [=[- Rock.pl]=],
    [=[- Ronald.pl]=],
    [=[- Seism.pl]=],
    [=[- Slacker.pl]=],
    [=[- Smack.pl]=],
    [=[- test_caster_focus_gear.pl]=],
    [=[- test_melee_focus_gear.pl]=],
    [=[- Tiny.pl]=],
    [=[- training_dummy.pl]=],
    [=[- Trent.pl]=],
    [=[- ultimateunresttrigger.pl]=],
    [=[- Weasel.pl]=],
}

return localNpcGuides
