local aa = {}

aa.lines = {
    'Progression Flags (Mel Review)',
    '',
    'Tracked completion flags include:',
    '- Vanilla Complete',
    '- Kunark Complete',
    '- Velious Complete',
    '- Luclin Complete',
    '- Planes of Power Complete',
    '- Ultimate Crushbone Complete',
    '- Guk Complete',
    '- Ultimate Weapon Complete',
    '- Temple of Veeshan Complete',
    '- Kael Drakkel Complete',
    '- Sleeper\'s Tomb Complete',
    '- Rank 6 Charm Complete (Uber Megalodon)',
    '- Avatar Tier One Complete',
    '- The Hole Complete',
    '- Rank 7 Charm Complete (The Hole)',
    '- Tower of Frozen Shadow Complete',
    '- Rank 8 Charm Complete (Veeshan\'s Peak)',
    '- Veeshan\'s Peak Complete',
    '- Ocean of Tears Complete',
    '- Unrest Complete',
    '- Ultimate 2.0 Complete',
    '- Rank 9 Charm Complete (OOT)',
    '- Plane of Fear Complete',
    '- Velketor\'s Labyrinth Complete',
    '- Rank 10 Charm Complete (Velketor)',
    '- The Goblin Vault Complete (God Access)',
    '- Reach Level 75',
    '- Crystallos Complete',
    '',
    'Tip:',
    '- Use Mel > I\'d Like To Review My Progression Flags to quickly diagnose access issues.',
}

return aa
