local serverNpcs = {}

serverNpcs.lines = {
    'UltimateEQ NPC Directory (Guild Lobby)',
    '',
    'Core progression and access:',
    '- Mel: progression tasks, charm starter, progression flag display.',
    '- Quake: Ultimate and Avatar zone access + info popups.',
    '- Seism: Demigod and God access + expedition instance management.',
    '- Illuminous: God-tier leveling (71-75), relic cap upgrades, palantir upgrades.',
    '- Arch Magus Phil: Uber boss currency pooling, Uber Megalodon, charm rank 6 upgrade.',
    '',
    'Weapons, credits, economy:',
    '- Forge: Ultimate 1.0/1.5 weapon crafting and quality system.',
    '- Weasel: gambling rerolls and quality risk/reward.',
    '- Aftershock: Ultimate Credit store, utility items, boosters, maps, services.',
    '- Tiny: conversion token exchange NPC.',
    '- Smack: AA purchase/convert flow.',
    '',
    'Tier vendors and augment NPCs:',
    '- Doug, Flex, Max, Relm, Cyan, Locke: tier vendors by currency band.',
    '- Donald, Ronald, Trent: zone gear-to-augment conversion lines.',
    '',
    'Utility and support:',
    '- Herald: server fundamentals and system explanations.',
    '- John: pet weapon progression tools.',
    '- Arcane Translocator: Arcane Academy transport.',
    '- Harbinger of Dread: leveling zones and ornament flow.',
    '',
    'Talent/specialization ecosystem:',
    '- Rock: specializations.',
    '- Rumble: specialization/talent rank detail.',
    '- Crumble: God talent purchasing and resets.',
    '',
    'Other named NPCs from captured docs:',
    '- Fleb, Tiny, Smack, Trent, Rumble plus class/tier-specific helper NPCs in progression zones.',
}

return serverNpcs
