return {
  tiers = {
    ['11.1'] = {
      "11.1|telkorenar: tank & spank|1",
      "11.1|gozzrem: tank & spank|1",
      "11.1|lendiniara: dispels often, use little buddy confidence booster 5000|1",
      "11.1|kill telkorenar|1",
      "11.1|kill gozzrem|1",
      "11.1|kill lendiniara|1",
      "11.1|hail grendel to finish|1",
      "11.1|collect astrial parts: left corner, right corner, top, bottom, center|1",
      "11.1|combine astrial parts in pok forge|1",
    },
    ['11.2'] = {
      "11.2|ruiner isaka|1",
      "11.2|elite aneuk miseryfiend|1",
      "11.2|frostkeeper rybah|1",
      "11.2|gelidran conjurer|1",
      "11.2|pyrilen researcher|1",
      "11.2|girplan stonesinger|1",
      "11.2|pyrilen summoner|1",
      "11.2|mistwalker|1",
      "11.2|bottom shard of astrial|1",
      "11.2|center shard of astrial|1",
      "11.2|left shard of astrial|1",
      "11.2|right shard of astrial|1",
      "11.2|top shard of astrial|1",
      "11.2|visit dwight schrute in nexus or pok|1",
      "11.2|kill chailak and loot book with missing pages (container)|1",
      "11.2|kill feratha and loot eternity binding glue|1",
      "11.2|loot missing pages from these named|1",
      "11.2|combine all 8 pages plus the glue inside the book with missing pages|1",
      "11.2|deliver the completed instructions book back to grendal|1",
      "11.2|loot missing page from elite aneuk miseryfiend|1",
      "11.2|loot missing page from ruiner isaka|1",
      "11.2|loot missing page from frostkeeper rybah|1",
      "11.2|loot missing page from gelidran conjurer|1",
      "11.2|loot missing page from pyrilen researcher|1",
      "11.2|loot missing page from girplan stonesinger|1",
      "11.2|loot missing page from pyrilen summoner|1",
      "11.2|loot missing page from mistwalker|1",
    },
    ['11.3'] = {
      "11.3|hand all 4 pages to him at the same time|1",
      "11.3|torn page of mastery water|1",
      "11.3|torn page of mastery earth|1",
      "11.3|torn page of mastery wind|1",
      "11.3|torn page of mastery fire|1",
      "11.3|hail borat at the zone in of najena and you can explore those options of what you would like to buy|1",
      "11.3|flower power (4 second, 35000 heal) ****highly recommended****|1",
      "11.3|resurrection stone (clicky divine rez)|1",
      "11.3|call of the hero stone (coh someone!)|1",
      "11.3|loot torn page of mastery fire|1",
      "11.3|loot torn page of mastery wind|1",
      "11.3|loot torn page of mastery earth|1",
      "11.3|loot torn page of mastery water|1",
      "11.3|deliver all 4 pages to borat in najena|1",
    },
    ['11.4'] = {
      "11.4|collect first piece of underfoot stone|1",
      "11.4|collect second piece of underfoot stone|1",
      "11.4|collect third piece of underfoot stone|1",
      "11.4|collect fourth piece of underfoot stone|1",
      "11.4|collect fifth piece of underfoot stone|1",
      "11.4|collect sixth piece of underfoot stone|1",
      "11.4|combine all 6 pieces in a universal assembly crate|1",
      "11.4|give the completed item to borat in the hole|1",
    },
    ['11.5'] = {
      "11.5|kill lieutenant vhalek and loot mastery of mind rune|1",
      "11.5|kill stormer and loot mastery of arcana rune|1",
      "11.5|kill cadavor fonidan and loot mastery of body rune|1",
      "11.5|kill neuromancer vionne and loot mastery of power rune|1",
      "11.5|kill diodite bluespark and loot mastery of the realms rune|1",
      "11.5|kill strategist kin'muram and loot mastery of tactics|1",
      "11.5|combine all 6 runes in a universal assembly crate|1",
      "11.5|turn in progression seal: mastery of all to borat|1",
    },
    ['11.6'] = {
      "11.6|kill king tormax and loot mindset of tormax|1",
      "11.6|kill keldor dek'torek and loot sensibility of keldor|1",
      "11.6|kill derakor the vindicator and loot viewpoint of the vindicator|1",
      "11.6|kill statue of rallos zek and loot statue of rallos zek|1",
      "11.6|kill idol of rallos zek and loot temperament of the idol|1",
      "11.6|kill avatar of war and loot attitude of avatar|1",
      "11.6|combine all 6 items in a universal assembly crate|1",
      "11.6|turn in mixed bag of opinions to borat in kael|1",
    },
    ['11.7'] = {
      "11.7|keldovan|1",
      "11.7|jelvan|1",
      "11.7|ture|1",
      "11.7|hanvar|1",
      "11.7|arch magus|1",
      "11.7|omm|1",
      "11.7|kill keldovan and loot the required mark|1",
      "11.7|kill jelvan and loot the required mark|1",
      "11.7|kill ture and loot the required mark|1",
      "11.7|kill hanvar and loot the required mark|1",
      "11.7|kill arch magus and loot the required mark|1",
      "11.7|kill omm and loot the required mark|1",
      "11.7|combine all 6 marks in a universal assembly crate|1",
      "11.7|give mark of completion to borat in anguish|1",
    },
    ['11.8'] = {
      "11.8|kill the final arbiter and loot the arbiter's heart|1",
      "11.8|kill the progenitor and loot proof of the progenitor's end|1",
      "11.8|kill nanzata the warder and loot the required item|1",
      "11.8|kill tukaarak the warder and loot the required item|1",
      "11.8|kill hraashna the warder and loot the required item|1",
      "11.8|kill ventani the warder and loot the required item|1",
      "11.8|combine all 6 items in a universal assembly crate|1",
      "11.8|turn in the combined item to borat in sleepers|1",
    },
    ['11.9'] = {
      "11.9|collect xorbb's reflective lens|1",
      "11.9|collect frozen soul that gazed at xorbb|1",
      "11.9|collect fragment of xorbb's throne|1",
      "11.9|collect testimony of the lords|1",
      "11.9|collect lost crown of xorbb|1",
      "11.9|collect the lost foci|1",
      "11.9|combine all 6 items in a universal assembly crate|1",
      "11.9|turn in the combined item to borat in xorbb|1",
    },
    ['11.10'] = {
    },
    ['11.11'] = {
    },
    ['11.12'] = {
    },
    ['11.13'] = {
    },
    ['11.14'] = {
    },
    ['11.15'] = {
    },
  },
}
