; KAHybrid Source: 120 Paladin | https://www.redguides.com/community/resources/120-paladin.2381/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L80_PAL.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=35
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Paladin|80|GOLD
ChaseAssist=0
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=3|60|PAL,ENC,SHM,CLR
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=1
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=0
SwitchWithMA=0
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=0
TwistMed=0
TwistOn=0
TwistWhat=0


[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=14
Buffs1=Divine Protector's Unity|Dual|Silent Piety
Buffs2=Blessed Aura|Aura|Blessed Aura Effect
Buffs3=Brell's Tenacious Barrier
Buffs4=Hand of the Dreaming Keeper
Buffs5=Night's Calming|End|15
Buffs6=Marr's Gift|Mana|85
Buffs7=Preservation of the Basilica|Me
Buffs8=Confluent Blessing|Me
Buffs9=Adamant Stance|Me
Buffs10=Ice Bound Ulthork|Dual|Familiar: Ice Bound Ulthork
Buffs11=command:/bandolier activate 1hs|Cond1
Buffs12=Luclinite Ensanguined Cloak of Security|dual|Illusionary Spikes XXIV
Buffs13=Marr's Salvation|dual|Marr's Salvation IX|!Me
Buffs14=Hallowed Steed|Dual|Mount Blessing Azia
RebuffOn=1
CheckBuffsTimer=5
BuffsCOn=1

[Melee]
MeleeOn=1
TargetSwitchingOn=1
BeforeCombat=Cast Before Melee Disc
MeleeDistance=75
StickHow=front 10
Autohide=0
DismountDuringFights=0
MeleeTwistOn=0
TankAllMobs=1
AssistAt=100
FaceMobOn=1
AutoFireOn=0
UseMQ2Melee=0


[GoM]
GoMOn=1
GoMCOn=0
GoMSize=0
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob


[GMail]
GMailSize=0
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0


[AE]
AEOn=1
AESize=23
AERadius=50
AE1=command:/bandolier activate 1hs|4|Mob|Cond1
AE2=Pureforge Discipline|2|Mob
AE3=Revered Guardian Discipline|3|Mob
AE4=Supernal Mantle|3|Mob
AE5=Armor of the Forthright|3|Mob
AE6=Hallowed Lodestar|3|Mob
AE7=Reflexive Redemption|3|Mob
AE8=Righteous Censure|3|Mob
AE9=Projection of Piety|4|Mob
AE10=Group Armor of the Inquisitor|4|Mob|Cond12
AE11=Armor of the Inquisitor|4|Mob|Cond12
AE12=Spire of Chivalry|4|Mob
AE13=Thunder of Karana|4|Mob
AE14=Beacon of the Righteous|4|Mob
AE15=Valorous Rage|4|Mob
AE16=Inquisitor's Judgment|4|Mob
AE17=Mom's Love|4|Mob
AE18=Nightbane, Sword of the Valiant|4|Mob
AE19=Hand of Piety|4|Mob
AE20=Gift of Life|4|Mob
AE21=Hand of Tunare|4|Mob
AE22=Heroic Leap|4|Mob
AE23=Armor of Experience|4|Mob

[DPS]
DPSOn=1
DPSSize=26
DPSSkip=20
DPSInterval=2
DPS1=command:/bandolier activate 2hs|100|Cond10
DPS2=Repudiate|100|Mash
DPS3=Shield Flash|100|Mash|Cond16
DPS4=Disruptive Persecution|100|Mash
DPS5=Deflection Discipline|100|Mash|Cond4
DPS6=Supernal Mantle|100|Mash|Cond19
DPS7=Armor of the Forthright|100|Mash|Cond20
DPS8=Force of the Umbra|99
DPS9=Crush of the Umbra|99
DPS10=Brilliant Acquittal|99
DPS11=Protective Revelation|99|Cond9
DPS12=Regenerating Steel|99|once
DPS13=Confluent Blessing|99|Cond13
DPS14=Preservation of the Basilica|99|Cond8
DPS15=Halt the Dead|100|Cond2
DPS16=Vanquish the Fallen|99|Cond2
DPS17=Doctrine of Annulment|99|Cond2
DPS18=Vanquish the Fallen|99|Cond2
DPS19=Holyforge Discipline|99|Cond7
DPS20=_Glyph of Destruction (120+)|90|Cond14
DPS21=Miniature Horn of Unity|99|Cond5
DPS22=Righteous Censure|99|Cond11
DPS23=Composite Force|99|Cond6
DPS24=Pureforge Discipline|99
DPS25=Blunted Blade|99|Cond22
DPS26=Sanctification Discipline|99|Cond23
DebuffAllOn=0
DPSCOn=1

[Bandolier]
BandolierOn=0
BandolierCOn=0
BandolierSize=2
BandolierPull=1HS
Bandolier1=NULL
BandolierCond1=FALSE
Bandolier2=NULL
BandolierCond2=FALSE


[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=7

# Class AA | 24m refresh (instant)
# Only use in combat
# Only use under 50% health
OhShit1=Hand of Piety|
OhShitCond1=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 40

# Class AA | 24m refresh (35s duration)
# Only use in combat
# Only use under 50% health
OhShit2=Lay on Hands|Me
OhShitCond2=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 40

# SOD Group BP | 10m recast
# Only use in combat
# Only use under 50% health
OhShit3=Purified Chromasteel Breastplate|
OhShitCond3=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# Class AA | 15m recast, 78s duration
# Only use in combat
# Only use under 50% health
OhShit4=Armor of the Inquisitor|
OhShitCond4=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# TSS Group BP | 15m recast, 60s duration
# Only use in combat
# Only use under 50% health
OhShit5=Silver-Scribed Plate Breastplate|
OhShitCond5=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# Discipline | 15m recast, 60s duration
# Only use in combat
# Only use under 50% health
OhShit6=Armor of Decorum Rk. II|
OhShitCond6=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# Class Skill
# Use if target is aggressive
# Use if my target's target isn't me
# Use if within 30 range
OhShit7=Taunt|Mob
OhShitCond7=${Target.Aggressive} && !${Me.TargetOfTarget.CleanName.Equal[${Me}]} && ${Target.Distance} < 30


[Aggro]
AggroOn=1
AggroSize=6
Aggro1=Taunt|100|<
Aggro2=Valiant Deterrence|100|<
Aggro3=Heroic Leap|95|<
Aggro4=Ageless Enmity|90|<
Aggro5=Parlay for Honor|96|<
Aggro6=Projection of Piety|89|<

[Pull]
PullLevel=0|0
MaxZRange=500
ChainPullHP=90
ChainPull=0
PullRoleToggle=0
ChainPullPause=30|2
PullArcWidth=0
PullWait=6
PullWith=Trial for Honor Rk. II
PullMeleeStick=0
MaxRadius=400
UseCalm=0
CalmRadius=50
CalmWith=Harmony
PullCond=TRUE
CheckForMemblurredMobsInCamp=1
ActNatural=1
PullNamedsFirst=0
GrabDeadGroupMembers=1
PrePullCond=TRUE


[Heals]
HealsOn=1
HealsSize=16
Heals1=Shield Flash|45|Tap|Cond16
Heals2=Protective Revelation|75|tap
Heals3=Burst of DawnBreak|70|tap
Heals4=Burst of DawnBreak|50|tap
Heals5=Burst of DawnBreak|30|tap
Heals6=Wave of Bereavement|99|tap|Cond6
Heals7=Composite Force|40|tap
Heals8=Valiant Deterrence|70|tap
Heals9=Lay on Hands|20
Heals10=Hand of Piety|60|Cond15
Heals11=Gift of Life|50|Cond15
Heals12=Gift of Resurrection|0|rez
Heals15=Marr's Gift|30
Heals16=${InvSlot[Charm].Item.Name}|99|Me|Cond21
AutoRezOn=1
AutoRezWith=Gift of Resurrection
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=3
Cures1=Radiant Cure
Cures2=Blessing of Purification
Cures3=Consecrate
CuresCOn=1

[Pet]
PetOn=nil
PetBehind=TRUE


[Burn]
BurnSize=25
BurnAllNamed=1
Burn1=command:/bandolier activate 1hs|Cond1
Burn2=command:/stopdisc|Cond17
Burn3=Revered Guardian Discipline|Cond18
Burn4=Deflection Discipline
Burn5=Unrelenting Affirmation
Burn6=Armor of the Forthright|Cond19
Burn7=Supernal Mantle|Cond20
Burn8=Armor of the Inquisitor|Cond12
Burn9=Group Armor of the Inquisitor|Cond12
Burn10=Thunder of Karana
Burn11=Beacon of the Righteous
Burn12=Hand of Tunare
Burn13=Hallowed Lodestar
Burn14=Spire of Chivalry
Burn15=Valorous Rage
Burn16=Inquisitor's Judgment
Burn17=Reflexive Redemption
Burn18=${InvSlot[Chest].Item.Name}
Burn19=Projection of Piety
Burn20=Miniature Horn of Unity
Burn21=Nightbane, Sword of the Valiant
Burn22=Mom's Love
Burn23=Infusion of the Faithful
Burn24=Intensity of the Resolute
Burn25=Armor of Experience

[Merc]
MercOn=0
MercAssistAt=92
Help=To use: Turn off Auto Assist in Manage Mercenary Window


[AFKTools]
AFKToolsOn=1
AFKPCRadius=500
CampOnDeath=0
BeepOnNamed=0
AFKGMAction=1
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
ClickBacktoCamp=0



[Spells]
Gem1=Parlay for Honor Rk. II
Gem2=Valiant Deterrence Rk. II
Gem3=Force of the Umbra Rk. II
Gem4=Composite Force
Gem5=Brilliant Acquittal Rk. II
Gem6=Protective Revelation Rk. II
Gem7=Burst of Dawnbreak Rk. II
Gem8=Wave of Bereavement Rk. II
Gem9=Preservation of the Basilica Rk. II
Gem10=Adamant Stance Rk. II
Gem11=Confluent Blessing Rk. II
Gem12=Regenerating Steel Rk. II
Gem13=Crush of the Umbra Rk. II


