; KAHybrid Source: 130, SK tank, Uses AE&#039;s | https://www.redguides.com/community/resources/130-sk-tank-uses-aes.3277/
; Preset: RAID
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_SHD.ini
; Preset: RAID
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=35
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=98
MeleeOn=1
FaceMobOn=1

## I - Ignore Sticking in Combat, When NOT Using MQ2Melee.
## Stick while in combat will try and use MAX melee distance.
## To adjust for this, use the % option in your StickHow command to move closer to the mob.

## Example: StickHow=MoveBack 50% loose

StickHow=I
MeleeDistance=30

AutoFireOn=0
UseMQ2Melee=1

## TargetSwitchingOn should allow your tank to swap targets without reverting back to your original target.
TargetSwitchingOn=1
PetTauntOverride=0



[Buffs]
BuffsOn=1
BuffsSize=12

RebuffOn=1
CheckBuffsTimer=12

## ------ Power Source ------ ##
# If you use a PowerSource and run out of a charged one, Bad things happen
PowerSource=NULL

## ------ SPELLS ------ ##
Buffs1=Spitetangle's Skin|Me|Cond1
Buffs2=Unyielding Stance|Me|Cond2
Buffs3=Paradoxical Disruption|Me|Cond3
Buffs4=|Me|Cond39

## ------ AA's && Combat Abilities ------ ##
#Timer 13
Buffs5=Hiatus V|Me|Cond4

# !!! Must have Banshee Skin VIII Spell. This AA uses this spell buff to recast. !!!
Buffs6=Dark Lord's Unity (Beza)|Me|Cond5

## ------ ITEMS ------ ##
Buffs7=${InvSlot[Charm].Item.Name}|Me|Cond7
Buffs8=Summoned: Modulation Shard IX|mana|75

# !!! Make sure your mount is in your "Stat Mount" key ring !!!
#TOV - Snow Griffin Saddle (Kala)
#COV - Winter Jackalope Saddle (Lena)
#TOL - Golden Owlbear Saddle (Meda)
#NOS - Eye-Spotted Shik'Nar Saddle (Neza)
#LS - Radiant Hawk Harness|Dual|Mount Blessing Ozah
Buffs9=Steed of Souls|Dual|Mount Blessing Qela|Cond40

# !!! Make sure your familiar is in your "Stat Familiar" key ring !!!
#TOV - Emperor Ganak Familiar|dual|Familiar: Emperor Ganak Familiar
#COV - Ice Bound Ulthork|dual|Familiar: Ice Bound Ulthork
#TOL - Personal Hemic Source|dual|Familiar: Personal Hemic Source
#NOS - Fungal Underbulk|dual|Familiar: Fungal Underbulk
#LS - Striped Badger Whistle|dual|Familiar: Striped Badger
Buffs10=Candlefolk Whistle|dual|Familiar: Candlefolk
Buffs11=NULL

# !!! This is if you like illusions, condition 6 must be changed to your Illusion name !!!
# !!! Make sure your Jann's Veil is in your "Stat Illusion" key ring !!! (Illusion mask from TBL)
#Buffs10=Amulet of Necropotence|Me|Cond6

## ------ Bandolier (Change "1HS" to the Name in Bandolier you wish to switch too, Typically Sword and Board) ----- ##
# !!! You must enter the name of your one handed weapon in Condition 8 & 32 !!!
Buffs12=Command:/bandolier activate 1HS|Cond8

# Glyph of Destruction
# !!! You can alter how many AA to bank and when to burn a Glyph with Conditions 34 & 35
#Buffs13=command:/Alt Buy 5304|Cond34

BuffsCOn=1

[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
# 0=Off 1=On 2=Group only healing. 3=MainAssist only. 4=Self only. - (4) Mainly used by SK's to not waste time checking others for heals.
HealsOn=1
HealsSize=6
HealInterval=10
Heal_Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50

AutoRezOn=0
RezMeLast=0

HealGroupPetsOn=0

## ------ Spells ------ ##
Heals1=Reciprocal Fang|95|Tap|Cond19
Heals2=Dire Implication X|98|Tap|Cond19
Heals3=Touch of Bonesplinter|99|Tap|Cond19
Heals4=Insidious Deflection Vii|99|Tap|Cond19

## ------ Items ------ ##
Heals4=${InvSlot[Charm].Item.Name}|99|Tap|Cond7

XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
XTarHealList_Help=Format Xtar slots Slots ~> Example: 5|6|7
Heals5=NULL
Heals6=NULL


HealsCOn=1

[DPS]
DPSOn=1
DPSSize=40
DPSSkip=0
DPSInterval=0
DebuffAllOn=0

# ------ The MA of the Group uses the AssistAt value to check if it should cast DPS and not the DPS entry values.
# ------ Lower size to 39 if you want to glyph when you want to.

## ------ LIFE SAVING ------ ##
DPS1=Impede|99|Tap|Mash
DPS2=Shield Flash|55|Tap|Mash|Cond13
DPS3=Leech Touch|45|Tap|Mash|Cond14

# !!! You must enter the name of your SHIELD in Condition 15 !!!
DPS4=Deflection Discipline|99|Mash|Cond15

## ------ Discs ------ ##
#Timer 11
DPS5=Soul Carapace XV|99|Tap|Weave|Cond16
#Timer 17
DPS6=Unholy Guardian Discipline IV|99|Tap|Weave|Cond17
#Timer 14
DPS7=Spite of Mirenilla|99|Tap|Weave|Cond18

## ----- Bandolier ------ ##
# !!! You must enter the name of your TWO handed weapon in Condition 30 !!!
# !!! You must enter the name of your ONE handed weapon in Condition 8 & 32 !!!
## ------ Bandolier (Change "2HS" to the Name in Bandolier you wish to switch too, Typically 2 Hander Dps weapon) ----- ##
DPS8=Command:/bandolier activate 2HS|99|Cond30
DPS9=Command:/bandolier activate 1HS|99|Cond32

## ------ Area of Effect ------ ##
DPS10=Explosion of Spite|100|Mash|Cond9
DPS11=Explosion of Hatred|100|Mash|Cond10
DPS12=Insidious Deflection VII|100|Cond11
DPS13=NULL

## ------ AC Increase ------ ##
DPS14=Duel for Power|99|Cond22

## ------ Snare ------ ##
DPS15=Encroaching Darkness|99|Cond26

## ------ SPELLS ------ ##
DPS16=Reciprocal Fang|40
DPS17=Touch of Bonesplinter|49
DPS18=Dire Implication X|49|Cond19

DPS19=Blood of Lherre|99|Once|Cond41
DPS20=Spear of Wremm|98|Cond23

DPS21=Bond of the Devourer|99
#Blood of Lherre|99|Once|Cond41 (If you have the mana, put in rotation)
## If you prefer DOTS (Strongest DOT should be under GOM)

## ------ Abilities and AA's ------ ##
#Removed AA
DPS22=Leechcurse Discipline|99|Cond29
#Timer 10
DPS23=Gouging Blade VIII|99|Mash
#Timer 19
DPS24=null
#Alt Act 825
DPS25=Vicious Bite of Chaos|99|Mash
#Alt Act 87
DPS26=Thought Leech|99|Cond27
#Alt Act 7755
DPS27=Scourge Skin|99|Cond29
#Alt Act 9403
DPS28=Visage of Death|99|Cond29
#Alt Act 2034
DPS29=Gift of the Quick Spear|99|Cond24
DPS41=T'vyl's Resolve|99|Cond29
DPS42=Reflexive retribution|99|Cond29

## ------------------------------------------------------ Items ----------------------------------------------------- ##
# ------ NULL out any items you do not have or prefer to click manually!

# - Anguish BP - #
DPS30=Duskbringer's Plate Chestguard of the Hateful|99|Tap|Weave|Cond28
#Duskbringer's Plate Chestguard of the Hateful|99|Tap|Weave|Cond28

# - SK Epic - # (Use |Weave|Cond29 over duration is under 5 minutes : Use |Weave|Cond39 if duration is 5 minutes or under)
DPS31=Innoruuk's Dark Blessing|99|Tap|Weave|Cond39

# - Expansion BP (Rousing Consumption)- #
DPS32=${InvSlot[Chest].Item.Name}|99|Tap|Weave|Cond38

# - Call of the Forsaken Completion Reward - #
DPS33=NULL
#Staff of Viral Flux|99|once

# - Anniversary Quest - #
DPS34=Unified Phoenix Feather|99|Cond27
#Unified Phoenix Feather|99|Cond27
DPS35=Miniature Horn Of Unity|99|Cond27
#Miniature Horn Of Unity|99|Cond27

#The Strength of a Wolf: Leader of the Pack Achievement -- (NOS - Quests)
DPS36=Spirit Drinker's Coating|99|Cond19
#Spirit Drinker's Coating|99|Cond19

## ------ Discs (for Named after Deflection wears off) ------ ##
#Timer 2
DPS37=Unholy Aura Discipline|100|Cond36

## ----- Defense Skin (Refresh if less then 1 miinute left on buff timer) ------ ##
DPS38=Spitetangle's Skin|99|Tap|Cond1

# Glyph of Destruction
# !!! You can alter how many AA to bank and when to burn a Glyph with Conditions 34 & 35
#DPS39=command:/Alt Buy 5304|99|Cond34
#DPS40=command:/Alt Act 5304|99|Cond35
DPS39=NULL
DPS40=NULL

DPSCOn=1

[Burn]
BurnSize=8
UseTribute=0
BurnAllNamed=1

Burn1=Spire of the Reavers
Burn2=Crimson Blade VIII
Burn3=Gift of the Quick Spear
Burn4=Visage of Decay
Burn5=${InvSlot[Chest].Item.Name}
Burn6=Harm Touch
Burn7=Thought Leech
Burn8=Chattering bones


## To turn burn section off /Burn Off
# ! The burn section will never be activated.

## To turn burn section on /Burn On
# !! The burn section will go active on any named mob.

## To activate a burn at any time /Burn
# !!! The burn section must be on via /Burn On prior for this to work.


[AE]
AEOn=0
AESize=1
AERadius=50
AE1=NULL

[OhShit]
OhShitOn=1
OhShitCOn=1
OhShitBuff1=Deflection Discipline
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=1
PetSpell=Minion of Telthel

PetShrinkOn=1
# Optional-- Easily obtained in game from Morell's Castle mobs.
# Adjust condition 33 to the height you want your pet to be under.
PetShrinkSpell=Curious Companion Compactor|Cond33

PetBuffsOn=1
PetBuffsSize=1
# !!! I love my pet totem. Remove or change if your not one of them guys. !!!
PetBuffs1=NULL
PetBuffs2=Companion's Fortification
PetBuffs3=Companion's Intervening Divine Aura
PetBuffs4=Companion's Aegis

PetCombatOn=1
PetAssistAt=95
PetAttackDistance=35

PetToysSize=6
PetBreakMezSpell=NULL
PetRampPullWait=0
PetSuspend=0
MoveWhenHit=0
PetHoldOn=1
PetForceHealOnMed=0
PetToysGave=
PetFocus=NULL


[Cures]
CuresOn=1
CuresSize=1
Cures1=NULL
CuresCOn=1

[Aggro]
AggroOn=1
AggroSize=8

##This Checks the secondary aggro you can see just how close some other character is to grabbing aggro from you.
## The new arg is <<.
# !!! Example: Aggro1=MobsHateThis|50|<< This will use MobsHateThis if the PRIMARY TARGET's secondary aggro gets above 50.

## ------ Single ------ ##
Aggro1=Taunt|100|<
Aggro2=Terror of Telthel|100|<
Aggro3=Duel for Power|100|<

## ------ Named ------ ##
Aggro4=Ageless Enmity|100|<|Cond37
Aggro5=Projection of Doom|100|<|Cond37
Aggro6=Unquestioned Acrimony|100|<|Cond37

## ------ Current target Aggro Slipping ------ ##
Aggro7=Terror of Telthel|95|<<
Aggro8=Duel for Power|90|<<


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
## In game command to change -- /zoneinfo (Mainly used for adding/ignoring targets as instances do not align with actual zone)
## Displays the entries from the KissAssist_Info.ini file, for the current zone.

## Pull with highest terror spell - (Remove #)
#PullWith=Terror of Telthel

## OR

## Pull with pet! - (Add # to not pull with pet)
## Be sure to increase Pet buff size to 4 if using pet to pull!
#PullWith=Pet

PullMeleeStick=1

## In game command to change -- /maxradius <#>
MaxRadius=500
## In game command to change -- /maxzrange <#>
MaxZRange=500

## Only used with Advanced Path
UseWayPointZ=1

## Percentage of spell range distance to stop at before you use spell to cast.
#PullRadiusToUse=90

## Seconds to wait between Pulls
PullWait=1

PullRoleToggle=0
ChainPull=0
ChainPullHP=90

## Time in Minutes to pull mobs before Holding Pulls|How long in minutes after holding to resume pulls.

PullPause=180|4|Cond31


PullLevel=50|200
## In game command to change -- /setpullarc <anglewidth#> <direction>
## Valid directions are n,ne,e,se,s,sw,w,nw, or any number from 1 - 360. If you leave the direction blank your current heading is used.
PullArcWidth=360

PullOnReturn=1
PullPause=30|2
PullRadiusToUse=90
PullWith=Melee


[PullAdvanced]
PullLocsOn=0


[Spells]
MiscGem=1
MiscGemLW=0
MiscGemRemem=1

CheckStuckGem=0
CastingInterruptOn=0
# Buffs = 2, Heals = 4, DPS = 8, and Mez = 16, 32 = Cure.
## Setting gives the ok to interrupt the type of cast that the number adds up to.
### IE - Prioritizing heals would be 10. (interrupt buffs (2) and dps(8) (2 + 8 = 10). interrupt everything except for Heals (4).

## In game command to change -- /writespells
## Writes your current spell set to the .ini file.
LoadSpellSet=2
SpellSetName=KissAssist

#Level
Gem1=Tormentor's Audacity
#Level
Gem2=Terror of Telthel
#Level
Gem3=Insidious Deflection Vii
#Level
#Gem4=blood of Lherre
#Level Rending of Ulnaa (If you crave more HP's)
Gem4=blood of Lherre
#Level
Gem5=Spear of Wremm
#Level
Gem6=Dire Implication X
#Level
Gem7=touch of Bonesplinter
#Level
Gem8=Bond of the Devourer
#Level
Gem9=Reciprocal Fang
#Level
Gem10=Wremm's Bite
#Level
Gem11=Duel for Power
#Level
Gem12=paradoxical Disruption
#Level
Gem13=Unyielding Stance
#Level
Gem14=Spitetangle's Skin


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


