; KAHybrid Source: 125 Healing Shaman for LS | https://www.redguides.com/community/resources/125-healing-shaman-for-ls.2952/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L80_SHM.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=0
CastRetries=3
CharInfo=Shaman|80|GOLD
ChaseAssist=1
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=0
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=6
SwitchWithMA=FALSE
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0


[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist


[Buffs]
BuffsOn=1
BuffsSize=12
Buffs1=Talisman of the Heroic|Dual|Heroic Focusing
Buffs2=Pact of the Wolf|Aura
Buffs3=Visionary's Unity|Dual|Pack of Ancestral Beasts|Me
Buffs4=Lupine Spirit|dual|Spirit of Tala'Tak|Me
Buffs5=Cannibalization|mana|65|65
Buffs6=Preincarnation|Me
Buffs7=Moroseness|MA
Buffs8=Reverie of Renewal|MA
;Buffs9=Hoary Agreement|Cond3
Buffs9=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs10=Summon Familiar: Striped Badger|Remove
Buffs11=Spirit Guardian|MA
Buffs12=Perfected Levitation|Dual|Group Perfected Levitation
;Buffs11=Ancient Coalition|MA
;Buffs12=Overwhelming Growth|MA
;Buffs13=Jann's Veil|dual|Illusion Benefit Greater Jann|Cond10
;Buffs14=Illusion: Efreeti|remove
RebuffOn=1
CheckBuffsTimer=20
PowerSource=NULL
Buffs12=NULL
Buffs13=NULL
Buffs14=NULL
Buffs11=NULL
BuffsCOn=1

[Melee]
AssistAt=99
MeleeOn=0
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
PetTauntOverride=0


[GoM]
GoMOn=0
GoMCOn=0
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMSize=0


[GMail]
GMailOn=0
GMailSize=0
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell


[AE]
AEOn=1
AESize=2
AERadius=100
AE1=Wind of Malaise|3
AE2=Turgur's Virulent Swarm|3


[DPS]
DPSOn=1
DPSSize=9
DPSSkip=1
DPSInterval=1
;DPS1=Malaise|99|debuffall|malo
DPS1=Blessed Spiritstaff of the Heyokah|99|Weave
;DPS3=Effervescent Counterbias|99|debuffall|slow|Cond1
DPS2=Turgur's Swarm|99|debuffall|slow|always|cond1
DPS3=Ecliptic Roar|99|MA
DPS4=Gelid Gift|99|MA
;DPS6=Spiritual Shower|99|MA|Cond16
DPS5=Cannibalization|99|Cond2
DPS6=Reverie of Renewal|100|Me|Cond14
DPS7=Command:/pet swarm|85|cond17
DPS8=Spire of Ancestors|95|weave
DPS9=Command:/pet attack|99
DebuffAllOn=1

DPSCOn=1

[Bandolier]
BandolierOn=0
BandolierCOn=0
BandolierPull=Blunt
BandolierSize=0


[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=2

# Class AA | 3min duration, 15min refresh
OhShit1=Ancestral Guard|
OhShitCond1=${Me.PctHPs} < 50

# Class AA | 5min duration, 24min refresh
OhShit2=Rabid Bear|
OhShitCond2=${Me.PctHPs} < 50


[Aggro]
AggroOn=0
AggroSize=5
Aggro1=NULL
Aggro2=NULL
Aggro3=NULL
Aggro4=NULL
Aggro5=NULL


[Heals]
HealsOn=1
HealsSize=22
Heals1=Ecliptic Roar|99|MA
Heals2=Immortal Intervention|50
Heals3=Soothsayer's Intervention|50
Heals4=Grayleaf's Recourse|90|Cond4
Heals5=Gelid Gift|95|MA
Heals6=Reckless Reinvigoration|90|MA
Heals7=Reckless Resurgence|90|MA
Heals8=Spiritual Shower|95|MA
Heals9=Reckless Renewal|90|MA
Heals10=Reckless Reinvigoration|90|Cond15
Heals11=Reckless Resurgence|90|Cond15
Heals12=Reckless Renewal|90|Cond15
Heals13=Reckless Reinvigoration|90|!MA
Heals14=Reckless Resurgence|90|!MA
Heals15=Reckless Renewal|90|!MA
Heals16=${InvSlot[Chest].Item.Name}|30
Heals17=Jeweled Apothic Dragon Spine Hammer|90|MA
Heals18=Staff of Forbidden Rites|0|rez
Heals19=Call of the Wild|0|rezcombat
Heals20=Rejuvenation of Spirit|0|rezooc
Heals21=Blessed Spiritstaff of the Heyokah|99|Weave
Heals22=Reverie of Renewal|100|MA
AutoRezOn=1
AutoRezWith=Rejuvenation of Spirit
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealInterval=0
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=1
RezMeLast=0

HealsCOn=1

[Cures]
CuresOn=1
CuresSize=3
Cures1=Radiant Cure
Cures2=Purified Spirits
Cures3=Blood of Mayong

CuresCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Suja's Faithful
PetBuffsOn=1
PetBuffsSize=2
PetBuffs1=Companion's Aegis
PetBuffs2=Companion's Fortification
;PetBuffs1=Spirit Augmentation
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0
PetFocus=NULL
PetShrinkOn=0
PetShrinkSpell=Tiny Companion
PetAssistAt=99
PetAttackDistance=115
PetToysSize=6
PetBreakMezSpell=NULL
MoveWhenHit=0
PetHoldOn=1
PetToysGave=


[Burn]
BurnSize=5
BurnAllNamed=1
Burn1=Spire of Ancestors
Burn2=Fleeting Spirit
Burn3=Spirit Call
Burn4=Blessed Spiritstaff of the Heyokah
Burn5=Rage of Rolfron|Cond8
UseTribute=0


[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[AFKTools]
AFKToolsOn=1
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


[PullAdvanced]
PullLocsOn=0


[Spells]
Gem1=Moroseness
Gem2=Reverie of Renewal
Gem3=Oka's Bite
Gem4=Gelid Gift
Gem5=Immortal Intervention
Gem6=Blood of Mayong
Gem7=Grayleaf's Recourse
Gem8=Reckless Reinvigoration
Gem9=Reckless Resurgence
Gem10=Reckless Renewal
Gem11=Spiritual Shower
Gem12=Ecliptic Roar
Gem13=Chaotic Toxin
MiscGem=6
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1


