; KAHybrid Source: 120 TOL Monk | https://www.redguides.com/community/resources/120-tol-monk.2369/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_L80_MNK.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=35
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Monk|80|GOLD
ChaseAssist=0
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=3|60|PAL,ENC,SHM,CLR
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=0
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=1
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=0
SwitchWithMA=0
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0


[SpellSet]
LoadSpellSet=0
SpellSetName=MuleAssist


[Buffs]
BuffsOn=1
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
BuffsSize=14
Buffs1=Master's Aura|aura
Buffs2=Night's Calming|End|10
Buffs3=Breath of Stillness|End|50
Buffs4=Disciplined Reflexes
Buffs5=Violet Conch of the Tempest|dual|Spinecoat
Buffs6=Orb of the Sky|dual|Call of Sky
Buffs7=${InvSlot[Charm].Item.Name}|Dual|${Me.Inventory[Charm].Spell}
Buffs8=${InvSlot[Back].Item.Name}|Dual|${Me.Inventory[Back].Spell}
Buffs9=Jann's Veil|Cond11
Buffs10=Illusion: |Remove
Buffs11=command:/alt buy 5304|Cond7
Buffs12=command:/alt buy 5104|Cond8
Buffs13=Personal Hemic Source|Dual|Familiar: Personal Hemic Source
Buffs14=Summon Familiar: Personal Hemic Source|Remove

BuffsCOn=1

[Melee]
AssistAt=99
MeleeOn=1
FaceMobOn=1
MeleeDistance=50
StickHow=snaproll rear 40%
AutoFireOn=0
UseMQ2Melee=0
TargetSwitchingOn=1


[GMail]
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0
GMailSize=0


[AE]
AEOn=0
AESize=0
AERadius=50


[DPS]
DPSOn=1
DPSSize=28
DPSSkip=1
DPSInterval=2
DebuffAllOn=0
DPS1=command:/bandolier activate 2hb|100
DPS2=Earthforce Discipline|99|cond1
DPS3=Eye of the Storm|99|cond2
DPS4=Speed Focus Discipline|99|cond3
DPS5=Ironfist Discipline|99|cond4
DPS6=Fists of Wu|99|weave
DPS7=Transcended Fistwraps of Immortality|99|weave
DPS8=Miniature Horn of Unity|99|cond9
DPS9=Zan Fi's Whistle|99|weave
DPS10=Flying Kick|99|mash
DPS11=Tiger claw|99|mash
DPS12=Disarm|99|mash
DPS13=Intimidation|99|mash
DPS14=Buffeting of Fists|99|mash
DPS15=Zlexak's Fang|99|mash
DPS16=Bloodwalker's Synergy|99|mash
DPS17=Vigorous Shuriken|99|mash
DPS18=Curse of Fifteen Strikes|99|mash
DPS19=Drunken Monkey Style|99|mash
DPS20=Phantom Fisticuffs|99
DPS21=Two-Finger Wasp Touch|99
DPS22=Icewalker's Precision Strike|99
DPS23=Necromantic Dragon Bone|99|weave
DPS24=mend|99|cond5
DPS25=command:/stand|99|cond6
DPS26=Unified Phoenix Feather|99|cond10
DPS27=Terrorpalm Discipline|99|cond13
DPS28=Five Point Palm|99|cond14

DPSCOn=1

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierPull=Blunt
BandolierSize=2
Bandolier1=Blunt
BandolierCond1=!${Target.Named} || !${Me.CombatAbilityReady[Innerflame Discipline]}
Bandolier2=Epic
BandolierCond2=${Target.Named} && ${Me.CombatAbilityReady[Innerflame Discipline]}


[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=9

# Only use if health under 50% | 3min refresh
OhShit1=Imitate Death|
OhShitCond1=${Me.PctHPs} < 35

# Only use if health under 50%
OhShit2=Feign Death|
OhShitCond2=${Me.PctHPs} < 40

# Only use if health under 50% | 12sec duration / 4min reuse
OhShit3=Impenetrable Discipline|
OhShitCond3=${Me.PctHPs} < 45

# Only use if health under 50% | 30sec duration / 10min reuse
OhShit4=Delay Death|
OhShitCond4=${Me.PctHPs} < 50

# Only use if health under 50% | 1min duration / 15min reuse
OhShit5=Counterforce Discipline|
OhShitCond5=${Me.PctHPs} < 55

# Only use if health under 50%
OhShit6=Mend|
OhShitCond6=${Me.PctHPs} < 60

# Only use if I'm feigning and my health is over 75%
OhShit7=command:/stand on|
OhShitCond7=${Me.Feigning} && (${Me.PctHPs} > 75)

# Only use if endurance under 50% | 12sec duration / 20min reuse
OhShit8=Moment of Tranquility|
OhShitCond8=${Me.PctEndurance} < 45

# Only use if endurance under 50% | 2min duration / 36min reuse
OhShit9=Third Wind Rk. II|
OhShitCond9=${Me.PctEndurance} < 50


[Aggro]
AggroOn=1
AggroSize=2
Aggro1=Imitate Death|90|>
Aggro2=Command:/stand|90|>|cond1


[Pull]
PullWith=Distant Strike
PullMeleeStick=0
MaxRadius=350
MaxZRange=20
PUllWait=5
PullPause=30|2
PullRadiusToUse=90
PullLevel=0|0
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
UseWayPointZ=0
PullArcWidth=0
PullOnReturn=1


[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=0
HealsSize=0
HealGroupPetsOn=0
XTarHeal=0
XTarHealList=NULL
AutoRezOn=0
RezMeLast=0
HealInterval=0

HealsCOn=0

[Cures]
CuresOn=1
CuresSize=1
Cures1=Purify Body

CuresCOn=1

[Pet]
PetOn=0
PetBehind=TRUE
PetBuffsSize=0


[Burn]
BurnSize=17
BurnText=KAKAROT!
BurnAllNamed=1
UseTribute=1
Burn1=Composite Form
Burn2=Rage of Rolfron|99|Cond12
Burn3=Spire of the Sensei
Burn4=Tiger's Poise
Burn5=Infusion of Thunder
Burn6=Focused Destructive Force
Burn7=Silent Strikes
Burn8=command:/stopdisc
Burn9=Ironfist Discipline
Burn10=Five Point Palm
Burn11=Swift Tails' Chant
Burn12=command:/stopdisc
Burn13=${InvSlot[Chest].Item.Name}
Burn14=Heel of Zagali
Burn15=Heron Stance
Burn16=Ton Po's Stance
Burn17=Vicious Rabbit|99|weave


[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0


[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


