; KAHybrid Source: 115 Ranger, Ranged DPS | https://www.redguides.com/community/resources/115-ranger-ranged-dps.1774/
; Preset: SOLO
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_RNG.ini
; Preset: SOLO
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=35
CampRadiusExceed=300
ReturnToCamp=1
ReturnToCampAccuracy=10
ChaseAssist=0
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=98
MeleeOn=0
FaceMobOn=1
MeleeDistance=150
StickHow=55 moveback
AutoFireOn=1
UseMQ2Melee=0
TargetSwitchingOn=0


[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Wildstalker's Enrichment|MA
Buffs2=Shout of the Arbor Stalker|MA
Buffs3=Wildstalker's Unity (Beza)|DUAL|Rimespur Coat
Buffs4=Outrider's Ever-Burning Cloak|Me
Buffs5=Eyes of the Visionary|Me
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL

BuffsCOn=1

[Heals]
HealsOn=1
HealsSize=5
Heals1=Desperate Dewcloud|50
Heals2=Wellspring|40
Heals3=Bulwark of the Brownies|45|Me
Heals4=Convergence of Spirits|30|MA
Heals5=Protection of the Spirit Wolf|70|Me
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0

HealsCOn=1

[DPS]
DPSOn=1
DPSSize=13
DPSSkip=10
DPSInterval=1
DPS1=Heartsunder|100
DPS2=command:/autofire|100|Once
DPS3=Entropy of Nature|99|Once
DPS4=Elemental Arrow|99
DPS5=Marked Shots|99
DPS6=Focused Blizzard of Arrows|99
DPS7=Dissident Fusillade|99
DPS8=Pyroclastic Ash|99
DPS9=command:/kick|99|Weave
DPS10=Jolting Axe Kicks|99|Weave
DPS11=Focused Gale of Blades|99|Weave
DPS12=Ice Burrower Swarm|99|Cond1
DPS13=Swarm of Hyperboreads|99
DebuffAllOn=0

DPSCOn=1

[Burn]
BurnSize=12
BurnAllNamed=0
Burn1=Auspice of the Hunter
Burn2=Pureshot Discipline
Burn3=Scarlet Cheetah's Fang
Burn4=${InvSlot[Chest].Item.Name}
Burn5=Group Guardian of the Forest
Burn6=Outrider's Accuracy
Burn7=Spire of the Pathfinders
Burn8=Imbued Ferocity
Burn9=Pack Hunt
Burn10=Scout's Mastery of the Elements
Burn11=Scout's Mastery of Fire
Burn12=Guardian of the Forest|Cond2
UseTribute=0


[AE]
AEOn=1
AESize=5
AERadius=50
AE1=Auspice of the Hunter|3
AE2=Outrider's Accuracy|3
AE3=Spire of the Pathfinders|3
AE4=${InvSlot[Chest].Item.Name}|3
AE5=Guardian of the Forest|3


[OhShit]
OhShitOn=0
OhShitCOn=1
OhShitBuff1=
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=0
PetCOn=1
PetBuff1=
PetBuffCond1=


[Cures]
CuresOn=1
CuresSize=1
Cures1=Wakening Balm


CuresCOn=1

[Aggro]
AggroOn=0
AggroCOn=1
AggroBuff1=
AggroBuffCond1=


[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=


