; KAHybrid Source: 125 Rogue for LS | https://www.redguides.com/community/resources/125-rogue-for-ls.2954/
; Preset: GROUP
; Generated: 2026-03-10
; Source class template: UltimateEQAssist_ROG.ini
; Preset: GROUP
; Generated: 2026-03-10

; UltimateEQAssist class template
; MQ2Mule-compatible slot/cond keys

[General]
Role=assist
CampRadius=30
CampRadiusExceed=300
ReturnToCamp=0
ReturnToCampAccuracy=10
ChaseAssist=1
ChaseDistance=25
MedOn=1
MedStart=30
LootOn=1
RezAcceptOn=1|96
AcceptInvitesOn=1
GroupWatchOn=1|20
CastingInterruptOn=1
EQBCOn=1|/bc
DanNetOn=0
DanNetDelay=20
MiscGem=8
MiscGemLW=9
MiscGemRemem=1
DPSMeter=1
BuffWhileChasing=1

CastRetries=3

[Melee]
AssistAt=99
MeleeOn=1
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll rear
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
AutoHide=1
PetTauntOverride=0

[Buffs]
BuffsOn=1
BuffsSize=8
Buffs1=Shadowscale Leggings of Steadfast Resolve|Summon|Consigned Bite of the Shissar XXII|1|Cond1
Buffs2=Consigned Bite of the Shissar XXII|Dual|Bite of the Shissar Poison XIII
Buffs3=null
;Jann's Veil|dual|Illusion Benefit Greater Jann|Cond2
Buffs4=null
;Illusion: Efreeti Amir|Remove
Buffs5=Striped Badger Whistle|Dual|Familiar: Striped Badger
Buffs6=Thief's Sight|Me|Cond11
Buffs7=Convalesce|End|20
Buffs8=Unified Phoenix Feather|Dual|Grace of Unity|Cond12
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
BuffsCOn=1

[Heals]
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
HealInterval=0
AutoRezOn=0
HealsSize=5
Heals1=NULL
Heals2=NULL
Heals3=NULL
Heals4=NULL
Heals5=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0
HealsCOn=1

[DPS]
DPSOn=1
DPSSize=35
DPSSkip=0
DPSInterval=0
DPS1=${InvSlot[Chest].Item.Name}|99
DPS2=null
;Nightshade, Blade of Entropy|99
DPS3=Pinpoint Fault|99|Mash
DPS4=Rogue's Fury|99|Cond13
DPS5=Frenzied Stabbing Discipline|99|Cond14
DPS6=Twisted Chance Discipline|99|Cond4
DPS7=Reckless Edge Discipline|99|Cond5
DPS8=Knifeplay Discipline|99|Cond8
DPS9=Crinotoxin Discipline|99|Cond7
DPS10=Executioner Discipline|99|Cond9
DPS11=Focused Rake's Rampage|99|Cond14
DPS12=null
;Ligament Slice|99
DPS13=Ecliptic Weapons|99
DPS14=Spire of the Rake|99
DPS15=Carve|99|Mash
DPS16=Shadow's Flanking|99
DPS17=Twisted Shank|99
DPS18=Veiled Blade|99
DPS19=Intimidation|99|Mash
DPS20=Unsuspecting Mark|99|Mash
DPS21=Shadow-Hunter's Dagger|99|Mash
DPS22=Disorienting Puncture|99|Mash
DPS23=Mayhem|99|Mash
DPS24=Venomous Blade|99|Mash
DPS25=Jugular Hew|99|Mash
DPS26=Bamboozle|99
DPS27=Trickery|99
DPS28=Frenzied Stabbing Discipline|99|Cond14
DPS29=Twisted Chance Discipline|99|Cond4
DPS30=Reckless Edge Discipline|99|Cond5
DPS31=Knifeplay Discipline|99|Cond8
DPS32=Crinotoxin Discipline|99|Cond7
DPS33=Executioner Discipline|99|Cond9
DPS34=Thief's Sight|99|Cond11
DPS35=command:/removebuff Convalesce|99|Cond12
DebuffAllOn=0
DPSCOn=1

[Burn]
BurnSize=1
BurnAllNamed=0
UseTribute=0
Burn1=NULL

[AE]
AEOn=0
AESize=10
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL
AE4=NULL
AE5=NULL
AE6=NULL
AE7=NULL
AE8=NULL
AE9=NULL
AE10=NULL

[OhShit]
OhShitOn=1
OhShitCOn=1
OhShitBuff1=Escape
OhShitBuffCond1=
OhShitBuff2=
OhShitBuffCond2=


[Pet]
PetOn=0
PetCOn=1
PetBuff1=
PetBuffCond1=


[Cures]
CuresOn=1
CuresSize=1
Cures1=Purge Poison
CuresCOn=1

[Aggro]
AggroOn=0
AggroSize=5
Aggro1=NULL
Aggro2=NULL
Aggro3=NULL
Aggro4=NULL
Aggro5=NULL

[GoM]
GoMOn=0
GoMCOn=1
GoMBuff1=
GoMBuffCond1=


[MySpells]
Gem1=
Gem2=
Gem3=
Gem4=
Gem5=
Gem6=
Gem7=
Gem8=
Gem9=
Gem10=
Gem11=
Gem12=
Gem13=



[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[PullAdvanced]
PullLocsOn=0

[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92


