; Source class template: UltimateEQAssist_L70_ENC.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
KissAssistVer=12.002
Role=Assist
CampRadius=30
CampRadiusExceed=400
ReturnToCamp=0
ChaseAssist=1
ChaseDistance=35
MedOn=1
MedStart=30
MedStop=100
MedCombat=0
LootOn=0
RezAcceptOn=1|90
AcceptInvitesOn=1
GroupWatchOn=0
GroupWatchCheck=FALSE
CorpseRecoveryOn=0
EQBCOn=0
DanNetOn=0
DanNetDelay=20
IRCOn=0
CampfireOn=0
CharInfo=Enchanter|70|GOLD
DefaultUI=TRUE
DPSMeter=0
ScatterOn=0
LOSBeforeCombat=0
XTSlot=1
BuffWhileChasing=1
CastRetries=3

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Voice of Clairvoyance|caster
Buffs2=Hastening of Salik|melee
Buffs3=Ethereal Rune|me
Buffs4=NULL
|Buffs5=NULL
|Buffs6=NULL
|Buffs7=NULL
Buffs8=NULL
|Buffs9=NULL
Buffs10=Mystic Shield
Buffs11=NULL
|Buffs12=NULL
RebuffOn=1
CheckBuffsTimer=10
Buffs13=NULL
Buffs14=NULL
Buffs15=NULL
Buffs16=NULL
Buffs17=NULL
Buffs18=NULL
Buffs19=NULL
Buffs20=NULL
PowerSource=NULL
Buffs5=NULL
Buffs6=NULL
Buffs7=NULL
Buffs9=NULL
Buffs12=NULL
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=10
DPSSkip=20
DPSInterval=2
DPS1=Howl of Tashan|95|debuffall|tash|always
DPS2=NULL
DPS3=Psychosis|85|once
|DPS4=Strangle|75
|DPS5=Boggle|70
|DPS6=NULL
|DPS9=NULL
|DPS10=NULL
DebuffAllOn=1
DPS7=NULL
DPS8=NULL
DPS4=NULL
DPS5=NULL
DPS6=NULL
DPS9=NULL
DPS10=NULL
DPSCOn=1

[Aggro]
AggroOn=0
AggroSize=3
Aggro1=Silent Casting|50|>
Aggro2=NULL
Aggro3=NULL

[Heals]
HealsOn=1
HealsSize=4
Heals1=Companion's Fortification|75|pet
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealInterval=0
AutoRezOn=0
Heals2=NULL
Heals3=NULL
Heals4=NULL
XTarHeal=0
XTarHealList=Xtar slots here Example: 5|6|7
HealGroupPetsOn=0
RezMeLast=0
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Aeldorb's Animation
PetBuffsOn=1
PetBuffsSize=3
PetBuffs1=Hastening of Salik
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0
PetFocus=NULL
PetShrinkOn=1
PetShrinkSpell=Tiny Companion
PetBuffs2=NULL
PetBuffs3=NULL
PetAssistAt=95
PetAttackDistance=115
PetToysSize=6
PetBreakMezSpell=NULL
MoveWhenHit=0
PetHoldOn=1
PetToysGave=

[Mez]
MezOn=1
MezRadius=50
MezMinLevel=60
MezMaxLevel=73
MezStopHPs=90
MezSpell=Euphoria
MezAESpell=Wake of Felicity|5
MezDebuffOnResist=0
MezDebuffSpell=Your Debuff Spell

[Burn]
BurnSize=4
BurnAllNamed=1
Burn1=Doppelganger
|Burn4=Self Stasis|35
UseTribute=0
Burn2=NULL
Burn3=NULL
Burn4=NULL

[GoM]
GoMSize=3
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMSpell1=NULL
GoMSpell2=NULL
GoMSpell3=NULL

[KConditions]
ConOn=1
CondSize=3
Cond1=${Target.ID} && ${Target.Type.Equal[NPC]} && ${Me.AltAbilityReady[Eldritch Rune]} && ${Me.PctHPs} < 80
Cond2=${Me.CanMount}
Cond3=TRUE

[Spells]
Gem1=Howl of Tashan
Gem2=Euphoria
Gem3=Desolate Deeds
Gem4=Ethereal Rune
Gem5=Voice of Clairvoyance
Gem6=Hastening of Salik
Gem7=Psychosis
Gem8=
Gem9=Wake of Felicity
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=KissAssist
CastingInterruptOn=1
CheckStuckGem=1

[Melee]
AssistAt=95
MeleeOn=0
FaceMobOn=1
MeleeDistance=75
StickHow=snaproll
AutoFireOn=0
UseMQ2Melee=1
TargetSwitchingOn=0
PetTauntOverride=0

[GMail]
GMailHelp=Events currently support - Dead,Drag,GM,Level,Named,Leftgroup,Tells
GMailOn=0
GMailSize=5
GMail1=NULL
GMail2=NULL
GMail3=NULL
GMail4=NULL
GMail5=NULL

[AE]
AEOn=0
AESize=10
AERadius=50
AE1=NULL
AE2=NULL
AE3=NULL
AE4=NULL
AE5=NULL
AE6=NULL
AE7=NULL
AE8=NULL
AE9=NULL
AE10=NULL

[Cures]
CuresOn=1
CuresSize=5
Cures1=NULL
Cures2=NULL
Cures3=NULL
Cures4=NULL
Cures5=NULL
CuresCOn=1

[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92

[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=350
MaxZRange=50
UseWayPointZ=0
PullWait=5
PullRadiusToUse=90
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
PullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullOnReturn=0

[PullAdvanced]
PullLocsOn=0

[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
