; Source class template: UltimateEQAssist_L70_MAG.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
KissAssistVer=11.001
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=1
ReturnToCamp=0
CampRadius=30
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Phantom Shield|Me
Buffs2=Circle of Fireskin|MA
Buffs3=Magi`Kot's Pants of Convergence|Summon|Rod of Mystical Transvergence|1
Buffs4=Rod of Mystical Transvergence|Mana|40|80
Buffs5=Elemental Form: Water
Buffs6=Elemental Aura
Buffs7=Elemental Conversion|mana|40|90
Buffs8=Summon: Molten Orb|Summon|Molten Orb|1
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[AE]
AEOn=1
AESize=10
AERadius=25
AE1=Wind of the Desert|4|Me
AE2=Scintillation|4|Me

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=10
DPSInterval=1
DPS1=Veil of Lost Hopes|99|debuffall|Malo|Once
DPS2=Fickle Fire|90|Once
DPS3=Fickle Fire|60|Once
DPS4=Dagger of Evil Summons|80|Weave
DPS5=!Bolt of Jerikor|40|Once
DPS6=!Blade Strike|98
DPS7=Mark of the Last Wing|85|Weave
DPS8=Molten Orb|85|Weave
DPS9=!Raging Servant|95
DebuffAllOn=2
DPSCOn=1

[SpellS]
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
LoadSpellSet=2
SpellSetName=KissAssist
CastingInterruptOn=1
Gem1=Veil of Lost Hopes
Gem2=Fickle Fire
Gem3=Dagger of Evil Summons
Gem4=Bolt of Jerikor
Gem5=Blade Strike
Gem6=Mark of the Last Wing
Gem7=Molten Orb
Gem8=Raging Servant

[Heals]
HealsOn=1
HealsSize=5
Heals1=Renewal of Jerikor|65|Pet
Heals2=Mend Companion|40|Pet
HealsCOn=1

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Child of Water
PetBuffsOn=1
PetBuffsSize=8
PetBuffs1=Elemental Fury
PetBuffs2=Focus of Primal Elements
PetToysOn=1
PetToysSize=6
PetToys1=Muzzle of Mardu|Summoned: Muzzle of Mardu
PetToys2=Summon Crystal Belt|Summoned: Crystal Belt
PetToys3=Summon Staff of the North Wind|Summoned: Staff of the North Wind|Summoned: Staff of the North Wind
PetToys4=!Summon Staff of the North Wind|Summoned: Staff of the North Wind
PetToysGave=Lonantik|Muzzle of Mardu:Summoned: Muzzle of Mardu1|Summon Crystal Belt:Summoned: Crystal Belt2
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=15
BurnAllNamed=0
Burn1=Host of the Elements
Burn2=Servant of Ro
Burn3=Frenzied Burnout
Burn4=Glyphwielder's Tunic of the Summoner

[GoM]
GoMSize=3
GoMSpell1=Raging Servant|Mob
GoMSpell2=Bolt of Jerikor|Mob

[KConditions]
ConOn=1
CondSize=5
Cond1=TRUE
Cond2=TRUE
Cond3=TRUE
Cond4=TRUE
Cond5=TRUE

[Cures]
CuresOn=1
CuresCOn=1
