; Source class template: UltimateEQAssist_MAG.ini
; Generated: 2026-03-10

[General]
KissAssistVer=11.005

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=5
Buffs1=Major Shielding
Buffs2=Phantom Chain
Buffs3=Elemental Shield
Buffs4=Shield of Flame|MA
RebuffOn=1
CheckBuffsTimer=10

[AE]
AEOn=1
AESize=2
AERadius=50
AE1=Rain of Fire|4

[DPS]
DPSOn=1
DPSSize=4
DPSSkip=10
DPSInterval=2
DPS1=Malaise|95
DPS2=Shock of Spikes|90|Once
DPS3=Dismiss Summoned|90|cond3
DebuffAllOn=0

[Heals]
HealsOn=1
HealsSize=2
Heals1=Renew Summoning|80|Pet

[Pet]
PetOn=1
PetCombatOn=1
PetSpell=Summoning: Earth
PetBuffsOn=1
PetBuffsSize=2
PetBuffs1=Burnout
PetToysOn=1
PetToysSize=2
PetToys1=Staff of Runes|Summoned: Staff of Runes
PetToysGave=NULL
PetRampPullWait=0
PetSuspend=0
PetForceHealOnMed=0

[Burn]
BurnSize=1
BurnAllNamed=0

[GoM]
GoMSize=1

[KConditions]
ConOn=1
CondSize=5
Cond1=TRUE
Cond2=FALSE
Cond3=${Target.Body.Name.Equal[Summoned]}
Cond4=TRUE
Cond5=TRUE

[Spells]
Gem1=Shock of Spikes
Gem2=Major Shielding
Gem3=Summoning: Earth
Gem4=Dismiss Summoned
Gem5=Shield of Flame
Gem6=Malaise
Gem7=Gate
Gem8=NULL
Gem9=NULL
Gem10=NULL
Gem11=NULL
Gem12=NULL
Gem13=NULL
