; Source class template: UltimateEQAssist_L80_PAL.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Paladin|80|GOLD
ChaseAssist=1
ChaseDistance=35
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=3|60|PAL,ENC,SHM,CLR
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=0
SwitchWithMA=0
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=0
TwistMed=0
TwistOn=0
TwistWhat=0

[SpellSet]
SpellSetName=MuleAssist
LoadSpellSet=1

[Buffs]
# Note item, AA, spell, or disc information
# Order should be permanent > instant > longest to shortest duration
# Order tiebreakers by shorted to longest cooldown if needed
# Explain conditions
BuffsOn=1
BuffsCOn=1
BegOn=0
RebuffOn=1
CheckBuffsTimer=10
BegSize=0
BuffCacheingDelay=300
BegPermissionHelp=Valid options are |raid|guild|fellowship|all|tell|group
BegHelp=Spellname|alias1,alias2,alias3 etc
PowerSource=NULL
BegPermission=NULL

BuffsSize=6

# Auras > Heals | permanent
Buffs1=Blessed Aura|aura
BuffsCond1=TRUE

# Utility Beneficial > Combat Innates | 200min duration
Buffs2=Remorse for the Fallen Rk. II
BuffsCond2=TRUE

# HP Buffs > Shielding | 144min duration
Buffs3=Armor of Inexorable Faith Rk. II
BuffsCond3=TRUE

# HP Buffs > HP type two | 80min duration
Buffs4=Brell's Earthen Aegis
BuffsCond4=TRUE

# HP Buffs > Aegolism | 60min duration
Buffs5=Oathbound Protector Rk. II
BuffsCond5=TRUE

# Utility Beneficial > Combat Innates | 60min duration
Buffs6=Silvered Fury
BuffsCond6=TRUE

[Melee]
MeleeOn=1
TargetSwitchingOn=1
BeforeCombat=Cast Before Melee Disc
MeleeDistance=75
StickHow=front 10
Autohide=0
DismountDuringFights=0
MeleeTwistOn=0
TankAllMobs=1
AssistAt=100
FaceMobOn=1
AutoFireOn=0
UseMQ2Melee=0

[GoM]
GoMOn=1
GoMCOn=0
GoMSize=0
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob

[GMail]
GMailSize=0
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0

[AE]
AEOn=0
AESize=0
AERadius=50
AE6=NULL

[DPS]
DPSOn=1
DPSCOn=1
DebuffAllOn=0
DPSSkip=1
StayAwayToCast=0
DPSInterval=0

DPSSize=8

# Utility Detrimental > Jolt | 30s duration, 3.5s recast
DPS1=Trial for Honor Rk. II|100
DPSCond1=!${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Class AA | instant, 9s refresh
DPS2=Force of Disruption|99
DPSCond2=!${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Direct Damage > Stun | instant, 12s recast
DPS3=Force of Timorous|98
DPSCond3=!${Me.TargetOfTarget.CleanName.Equal[${Me}]}

# Direct Damage > Stun | instant, 12s recast
DPS4=Solemn Force|97
DPSCond4=!${Me.TargetOfTarget.CleanName.Equal[${Me}]}

DPS5=Yaulp IV|96
DPSCond5=TRUE

DPS6=Holyforge Discipline|95
DPSCond6=${Target.Named} && ${Target.Body.Name.Equal[Undead]}

DPS7=Bash|94|mash
DPSCond7=TRUE

DPS8=Shackles of Tunare|93
DPSCond8=${Target.Moving} && ${Target.PctHPs} < 20

[Bandolier]
BandolierOn=0
BandolierCOn=0
BandolierSize=2
BandolierPull=1HS
Bandolier1=NULL
BandolierCond1=FALSE
Bandolier2=NULL
BandolierCond2=FALSE

[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=7

# Class AA | 24m refresh (instant)
# Only use in combat
# Only use under 50% health
OhShit1=Hand of Piety|
OhShitCond1=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 40

# Class AA | 24m refresh (35s duration)
# Only use in combat
# Only use under 50% health
OhShit2=Lay on Hands|Me
OhShitCond2=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 40

# SOD Group BP | 10m recast
# Only use in combat
# Only use under 50% health
OhShit3=Purified Chromasteel Breastplate|
OhShitCond3=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# Class AA | 15m recast, 78s duration
# Only use in combat
# Only use under 50% health
OhShit4=Armor of the Inquisitor|
OhShitCond4=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# TSS Group BP | 15m recast, 60s duration
# Only use in combat
# Only use under 50% health
OhShit5=Silver-Scribed Plate Breastplate|
OhShitCond5=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# Discipline | 15m recast, 60s duration
# Only use in combat
# Only use under 50% health
OhShit6=Armor of Decorum Rk. II|
OhShitCond6=${Me.CombatState.Equal[Combat]} && ${Me.PctHPs} < 50

# Class Skill
# Use if target is aggressive
# Use if my target's target isn't me
# Use if within 30 range
OhShit7=Taunt|Mob
OhShitCond7=${Target.Aggressive} && !${Me.TargetOfTarget.CleanName.Equal[${Me}]} && ${Target.Distance} < 30

[Aggro]
AggroOn=0
AggroCOn=0
AggroSize=0

[Pull]
PullLevel=0|0
MaxZRange=500
ChainPullHP=90
ChainPull=0
PullRoleToggle=0
ChainPullPause=30|2
PullArcWidth=0
PullWait=6
PullWith=Trial for Honor Rk. II
PullMeleeStick=0
MaxRadius=400
UseCalm=0
CalmRadius=50
CalmWith=Harmony
PullCond=TRUE
CheckForMemblurredMobsInCamp=1
ActNatural=1
PullNamedsFirst=0
GrabDeadGroupMembers=1
PrePullCond=TRUE

[Heals]
# Note item, AA, spell, or disc information
# Ordered by lowest health to highest health
# Explain conditions
HealsOn=1
HealsCOn=1
AutoRezOn=2
HealGroupPetsOn=0
AutoRezWith=Gift of Resurrection
XTarHeal=0
InterruptHeals=100
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50

HealsSize=3

# Heals > Quick Heal
Heals1=Light of Piety|75
HealsCond1=TRUE

# Heals > Quick Heal
Heals2=Gleaming Light|75
HealsCond2=TRUE

# Heals > Quick Heal
Heals3=Radiant Light|75
HealsCond3=TRUE

[Cures]
CuresOn=1
CuresSize=2
Cures1=Purification
CuresCond1=${Me.CombatState.Equal[Combat]}
Cures2=Radiant Cure
CuresCond2=!${Me.CombatState.Equal[Combat]}

CuresCOn=1
[Pet]
PetOn=nil
PetBehind=TRUE

[Burn]
BurnCOn=0
BurnSize=0
BurnAllNamed=0
UseTribute=0
BurnText=Burn this

[Merc]
MercOn=0
MercAssistAt=92
Help=To use: Turn off Auto Assist in Manage Mercenary Window

[AFKTools]
AFKToolsOn=1
AFKPCRadius=500
CampOnDeath=0
BeepOnNamed=0
AFKGMAction=1
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
ClickBacktoCamp=0

