; Source class template: UltimateEQAssist_L80_SHM.ini
; Preset: RAID
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=0
CastRetries=3
CharInfo=Shaman|80|GOLD
ChaseAssist=1
ChaseDistance=35
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=0
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=10
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=6
SwitchWithMA=FALSE
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=0
TwistOn=0
TwistWhat=0

[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist

[Buffs]
# Note item, AA tab, spell category, or disc information
# Order should be permanent > instant > longest to shortest duration
# Order tiebreakers by shorted to longest cooldown if needed
# Explain conditions
BuffsOn=1
BuffsCOn=1
RebuffOn=1
CheckBuffsTimer=10
PowerSource=NULL
BuffCacheingDelay=300
BegOn=1
BegHelp=Spellname|alias1,alias 2,alias 3 etc
BegPermission=|raid|guild|tell|group
BegPermissionHelp=Valid options are |raid |guild |fellowship |all |tell |group

BegSize=6

Beg1=Talisman of the Bloodworg Rk. III|buffs,buffz,focus,wunshi
Beg2=Talisman of Foresight Rk. III|buffs,buffz,might,str,sense,agi
Beg3=Talisman of Talisman of Vehemence Rk. II|buffs,buffz,fortitude,fort,sta,stam,end
Beg4=Spirit of Bih`Li|buffs,buffz,bih'li,billy,sow,bili
Beg5=Champion|buffs,buffz,champion,champ,avatar,fa
Beg6=Talisman of the Cougar|buffs,buffz,puma,panther,cougar

BuffsSize=14

# Class AA | permanent
Buffs1=Pact of the Wolf|aura
BuffsCond1=TRUE

# Item | permanent
# Only use on group members taller than 1.91  and if in a raid
Buffs2=Umbracite Swarm Orb
BuffsCond2=${Target.Height} > 1.91 && ${Raid.Members}

# Class AA | instant / 5min refresh
Buffs3=Cannibalization|mana|60|90
BuffsCond3=TRUE

# Utility Beneficial > Conversions | instant / 18sec recast
Buffs4=Ancestral Hearkening Rk. II|mana|70|90
BuffsCond4=TRUE

# HP Buffs > Shielding | 72min duration
Buffs5=Talisman of the Bloodworg Rk. III
BuffsCond5=TRUE

# Statistic Buffs > Agility | 63min duration
Buffs6=Talisman of Foresight Rk. III|dual|Mammoth's Strength Rk. III
BuffsCond6=TRUE

# Statistic Buffs > Stamina | 63min duration
Buffs7=Talisman of Vehemence Rk. II
BuffsCond7=TRUE

# Utility Beneficial > Movement | 36min duration
Buffs8=Spirit of Bih`Li
BuffsCond8=TRUE

# Utility Beneficial > Misc | 30min duration
Buffs9=Preincarnation Rk. II
BuffsCond9=TRUE

# Utility Beneficial > Damage Shield | 21min duration
Buffs10=Thorn Wilting Rk. II|melee
BuffsCond10=TRUE

# Regen > Health | 20min duration
Buffs11=Talisman of the Stalwart Rk. III
BuffsCond11=TRUE

# Statistic Buffs > Attack | 6min duration
Buffs12=Champion
BuffsCond12=TRUE

# Utility Beneficial > Combat Innates | 4min duration
Buffs13=Languor Rk. II|melee
BuffsCond13=TRUE

# Utility Beneficial > Combat Innates | 30sec duration
Buffs14=Talisman of the Cougar Rk. II|melee
BuffsCond14=TRUE

[Melee]
AssistAt=100
MeleeOn=0
FaceMobOn=1
MeleeDistance=75
StickHow=behind 10
AutoFireOn=0
UseMQ2Melee=0
DismountDuringFights=0
BeforeCombat=Cast Before Melee Disc
TankAllMobs=FALSE

[GoM]
GoMOn=0
GoMCOn=0
GoMSHelp=Format - Spell|Target, MA Me or Mob, i.e. Rampaging Servant Rk. II|Mob
GoMSize=0

[GMail]
GMailOn=0
GMailSize=0
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell

[AE]
AEOn=0
AERadius=100
AESize=0

[DPS]
DPSOn=1
DPSCOn=1
DebuffAllOn=0
DPSInterval=0
DPSSkip=0
StayAwayToCast=FALSE

DPSSize=11

DPS1=Ritualchanter's Tunic of the Ancestors|100
DPSCond1=${Target.Named}

# Only use if fighting a named and don't have the Prophet's Channeling buff
DPS2=Mystical Energeiac Chain Coat|100
DPSCond2=${Target.Named} && !${Me.Buff[Prophet's Channeling].ID}

DPS3=Malosinatia|99|malo
DPSCond3=${Target.Named} || ${Raid.Members}

DPS4=Rolist's Drowse|98|slow
DPSCond4=TRUE

DPS5=Turgur's Virulent Swarm|97|slow
DPSCond5=!${Target.Buff[Turgur's Insects].ID}

DPS6=Turgur's Swarm|96|slow
DPSCond6=!${Target.Buff[Turgur's Insects].ID}

DPS7=Time's Antithesis|95|slow
DPSCond7=!${Target.Buff[Turgur's Insects].ID}

# Only use if fighting a named or have the Bard 2.0 buff
DPS8=Blessed Spiritstaff of the Heyokah|94
DPSCond8=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID}

# Only use if fighting a named or have the Bard 2.0 buff or have the Shaman 2.0 buff
DPS9=Call of the Ancients|93
DPSCond9=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named or have the Bard 2.0 buff or have the Shaman 2.0 buff
DPS10=Ancestral Aid|92
DPSCond10=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named or have the Bard 2.0 buff or have the Shaman 2.0 buff
DPS11=Spirit Call|91
DPSCond11=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

[Bandolier]
BandolierOn=0
BandolierCOn=0
BandolierPull=Blunt
BandolierSize=0

[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=2

# Class AA | 3min duration, 15min refresh
OhShit1=Ancestral Guard|
OhShitCond1=${Me.PctHPs} < 50

# Class AA | 5min duration, 24min refresh
OhShit2=Rabid Bear|
OhShitCond2=${Me.PctHPs} < 50

[Aggro]
AggroOn=0
AggroCOn=0
AggroSize=0

[Heals]
# Note item, AA, spell, or disc information
# Ordered by highest to lowest health
# Explain conditions if more than one condition
HealsOn=1
HealsCOn=1
HealGroupPetsOn=0
AutoRezOn=2

Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
InterruptHeals=100
XTarHeal=11|12|13|14|15|16|17|18|19|20

AutoRezWith=Incarnate Anew

HealsSize=4

# Heals > Heals
Heals1=Gemmi's Mending Rk. III|80|!pet
HealsCond1=TRUE

# Class AA
Heals2=Union of Spirits|50|!pet
HealsCond2=${Me.CombatState.Equal[Combat]}

# Heals > Heals | 3min recast
Heals3=Ancestral Intervention Rk. II|50|!pet
HealsCond3=${Me.CombatState.Equal[Combat]}

# Class AA | 5min refresh
Heals4=Soothsayer's Intervention|50|!pet
HealsCond4=${Me.CombatState.Equal[Combat]}

[Cures]
CuresOn=1

CuresSize=1

# Archetype AA
Cures1=Radiant Cure
CuresCond1=!${Me.CombatState.Equal[Combat]}

CuresCOn=1
[Pet]
PetOn=1
PetBuffsOn=0
PetShrinkOn=1
PetCombatOn=1
PetHoldOn=1
MoveWhenHit=0
PetAssistAt=80
PetBehind=TRUE
PetForceHealOnMed=0
PetRampPullWait=0
PetShrinkSpell=Tiny Companion
PetSpell=Vegu's Faithful Rk. III
PetSuspend=0
PetToysGave=
PetToysSize=0
PetBreakMezSpell=NULL
PetBuffsSize=0

[Burn]
BurnCOn=0
BurnText=Burn this
BurnAllNamed=0
UseTribute=0
BurnSize=0

[Pull]
PullWith=Melee
PullMeleeStick=0
MaxRadius=1350
MaxZRange=50
CheckForMemblurredMobsInCamp=0
PullWait=5
PullCond=TRUE
PrePullCond=TRUE
PullRoleToggle=0
ChainPull=0
ChainPullHP=90
ChainPullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullNamedsFirst=0
ActNatural=1
UseCalm=0
CalmWith=Harmony
CalmRadius=50
GrabDeadGroupMembers=1

[AFKTools]
AFKToolsOn=1
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0

[Merc]
MercOn=0
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercAssistAt=92

