; Source class template: UltimateEQAssist_L80_BRD.ini
; Preset: GROUP
; Generated: 2026-03-10

[General]
# Ordered alphabetically to make entries easier to find
AcceptInvitesOn=1
BuffWhileChasing=1
CampfireOn=0
CampRadius=30
CampRadiusExceed=400
CastingInterruptOn=1
CastRetries=3
CharInfo=Bard|80|GOLD
ChaseAssist=1
ChaseDistance=25
CheerPeople=0
DanNetDelay=20
DanNetOn=1
DefaultUI=TRUE
DPSMeter=0
EQBCOn=0
GemStuckAbility=Origin
GemStuckHelp=Sometimes the spellgems get stuck in a foreverloop, casting an altability that has a cast time will unstick it, this is an eq bug.
GroupEscapeOn=0
GroupWatchOn=3|60|PAL,ENC,SHM,CLR
HoTTOn=0
IRCOn=0
LootOn=0
MedOn=1
MedStart=30
MiscGem=0
MiscGemLW=0
MiscGemRemem=0
MoveCloserIfNoLOS=1
MuleAssistVer=15.3.2
OnStart=NULL
ReturnToCamp=0
ReturnToCampAccuracy=10
RezAcceptOn=1|90
Role=Assist
Scatter=0
SitToMed=1
SwitchWithMA=0
TheWinTitle=${Me.Class.ShortName} - ${Me.PctExp}% - ${Me.AAPoints}
TravelOnHorse=FALSE
TwistMed=1 2 3 4 5 6
TwistOn=1
TwistWhat=1 2 3 4 5 6

[SpellSet]
LoadSpellSet=1
SpellSetName=MuleAssist

[Buffs]
# Note item, AA, spell, or disc information
# Order should be permanent > instant > longest to shortest duration
# Order tiebreakers by shorted to longest cooldown if needed
# Explain conditions
BegHelp=Spellname|alias1,alias 2,alias 3 etc
BegPermissionHelp=Valid options are |raid |guild |fellowship |all |tell |group
BuffsOn=1
BuffsCOn=1
BegOn=0
RebuffOn=0
CheckBuffsTimer=10
PowerSource=NULL
BuffCacheingDelay=300
BegPermission=NULL
BegSize=0

BuffsSize=4

# https://everquest.allakhazam.com/db/item.html?item=32404 | permanent
Buffs1=Lute of the Mischiefmaker
BuffsCond1=TRUE

# Auras > Haste/Spell Focus | permanent
Buffs2=Aura of the Artist Rk. II|aura
BuffsCond2=TRUE

# https://everquest.allakhazam.com/db/item.html?item=30274 | 15min duration
Buffs3=Rapier of Somber Notes
BuffsCond3=TRUE

# Class AA | 5min duration
Buffs4=Selo's Sonata
BuffsCond4=!${Me.Buff[Selo's Accelerando].ID}

[Melee]
MeleeOn=1
MeleeTwistOn=1
FaceMobOn=1
AutoFireOn=0
AssistAt=100
MeleeDistance=75
StickHow=behind 10
UseMQ2Melee=0
DismountDuringFights=0
BeforeCombat=Cast Before Melee Disc
TankAllMobs=FALSE
MeleeTwistWhat=1 2 3 4 5 6

[GMail]
GMailHelp=Events currently support - Dead,GM,Level,Named,Leftgroup,Say,Tell
GMailOn=0
GMailSize=0

[AE]
AEOn=0
AERadius=50
AESize=0

[DPS]
DPSOn=1
DPSCOn=1
DebuffAllOn=0
DPSSkip=0
StayAwayToCast=FALSE
DPSInterval=0

DPSSize=13

DPS1=Blade of Vesagran|100|mash
DPSCond1=${Target.Named} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

DPS2=Kick|99|mash
DPSCond2=TRUE

DPS3=Bladed Song|98
DPSCond3=TRUE

# Only use if fighting a named and mana level is higher that target's health level
DPS4=Boastful Bellow|97|mash
DPSCond4=(${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}) && (${Me.PctEndurance} > ${Target.PctHPs})

# Only use if fighting a named | 4min duration
DPS5=Puretone Discipline|96
DPSCond5=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 2min duration
DPS6=Quick Time|95
DPSCond6=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 1min duration
DPS7=Fierce Eye|94
DPSCond7=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 42sec duration
DPS8=Funeral Dirge|93
DPSCond8=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 18sec duration
DPS9=Deftdance Discipline|92
DPSCond9=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 30sec duration
DPS10=Dance of Blades|91
DPSCond10=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 30sec duration
DPS11=Song of Stone|90
DPSCond11=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 12sec duration
DPS12=Whisper-Wrought Plate Breastplate|89
DPSCond12=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

# Only use if fighting a named | 12sec duration
DPS13=Chromasteel Breastplate of the Dream|88
DPSCond13=${Target.Named} || ${Me.Song[Spirit of Vesagran].ID} || ${Me.Song[Prophet's Gift of the Ruchu].ID}

[Bandolier]
BandolierOn=0
BandolierCOn=1
BandolierPull=DPS
BandolierSize=0

[OhShit]
OhShitOn=1
OhShitCOn=1

OhShitSize=3

# Only use if my health is less than 50% | 1.5min duration
OhShit1=Hymn of the Last Stand|
OhShitCond1=${Me.PctHPs} < 50

# Only use if my health is less than 50% | 1min duration
OhShit2=Shield of Notes|
OhShitCond2=${Me.PctHPs} < 45

# Only use if my health is less than my mana
OhShit3=Fading Memories|
OhShitCond3=${Me.PctHPs} < ${Me.PctMana} && ${Me.PctHPs} < 40

[Aggro]
AggroOn=0
AggroCOn=0
AggroSize=0

[Pull]
PullTwistOn=1
PullMeleeStick=0
MaxRadius=1000
MaxZRange=300
CheckForMemblurredMobsInCamp=1
PullWait=6
PullCond=TRUE
PrePullCond=TRUE
PullRoleToggle=0
ChainPull=0
ChainPullHP=20
ChainPullPause=30|2
PullLevel=0|0
PullArcWidth=0
PullNamedsFirst=0
ActNatural=1
UseCalm=0

CalmRadius=50
GrabDeadGroupMembers=1
UseWayPointZ=0

PullWith=Sonic Disturbance
CalmWith=NULL

[Heals]
# Note item, AA, spell, or disc information
# Ordered by lowest health to highest health
# Explain conditions
Help=Format Spell|% to heal at i.e. Devout Light Rk. II|50
HealsOn=1
HealsCOn=1
HealGroupPetsOn=0
InterruptHeals=100
XTarHeal=0
HealsSize=0

[Cures]
CuresOn=1
CuresSize=0

CuresCOn=1
[Pet]
PetOn=0
PetBehind=TRUE
PetBuffsSize=0

[Mez]
MezOn=2
MezRadius=200
MezMinLevel=1
MezMaxLevel=83
MezStopHPs=1
MezSpell=Command of Queen Veneneu Rk. II
MezAESpell=Your AE Mez Spell|0

[Burn]
BurnCOn=0
BurnAllNamed=0
BurnText=Burn this
UseTribute=0
BurnSize=0

[AFKTools]
AFKHelp=AFKGMAction=0 Off, 1 Pause Macro, 2 End Macro, 3 Unload MQ2, 4 Quit Game
AFKToolsOn=1
AFKGMAction=1
AFKPCRadius=500
CampOnDeath=0
ClickBacktoCamp=0
BeepOnNamed=0

[Merc]
Help=To use: Turn off Auto Assist in Manage Mercenary Window
MercOn=0
MercAssistAt=92

