; Source class template: UltimateEQAssist_L75_CLR.ini
; Preset: SOLO
; Generated: 2026-03-10

[General]
KissAssistVer=11.005
AcceptInvitesOn=1
BuffWhileChasing=1
MedOn=1
MedStart=30
CastRetries=3
ChaseAssist=0
ReturnToCamp=1
CampRadius=35
ReturnToCampAccuracy=10
ChaseDistance=25

[SpellSet]
LoadSpellSet=2

[Buffs]
BuffsOn=1
BuffsSize=20
Buffs1=Aura of Purpose|me
Buffs2=Armor of the Sacred
Buffs3=Rallied Aegis of Vie
Buffs4=Ward of Reprisal
Buffs5=Death Pact|!ma
Buffs6=Aura of the Pious|Aura
Buffs7=Rod of Mystical Transvergence|Mana|30|60
Buffs8=Wand of Elemental Transvergence|Mana|30|60
Buffs9=Tenacity|Cond2
Buffs10=Grassland Tiger Saddle|Mount
Buffs11=Divine Intervention|ma
RebuffOn=1
CheckBuffsTimer=10
BuffsCOn=1

[DPS]
DPSOn=1
DPSSize=20
DPSSkip=20
DPSInterval=2
DPS1=Blood of the Martyr|99|Cond3
DPS2=Unflinching Hammer of Zeal|95
DPS3=Silent Casting|93|Cond1
DPS4=Divine Avatar|85|Cond1
DPS5=Divine Retribution|80|Cond1
DebuffAllOn=0
DPSCOn=1

[Heals]
HealsOn=1
HealsSize=15
Heals1=Sacred Light|85
Heals2=Sacred Elixir|80
Heals3=Word of Vivification|75
Heals4=Complete Heal|70|ma
Heals5=Sanctuary|25|Me|Cond1
Heals6=Promised Renewal|45
Heals7=Divine Arbitration|50|ma
Heals8=Bestow Divine Aura Azia|25|!ma
Heals9=Divine Custody|20|Me
Heals10=Water Sprinkler of Nem Ankh|0|rez
Heals11=Harmony of the Soul|80|Cond5
Heals12=Ward of Purity|99|Cond1
Heals13=Exquisite Benediction|99|Cond1
Heals14=Celestial Regeneration|85|MA|Cond4
Heals15=Weighted Hammer of Conviction|50|MA|Cond6
AutoRezOn=1
AutoRezWith=Water Sprinkler of Nem Ankh
HealsCOn=1

[Cures]
CuresOn=1
CuresSize=5
Cures1=Remove Greater Curse|Curse
Cures2=Radiant Cure
Cures3=Puratus|Poison
Cures4=Eradicate Disease|Disease
CuresCOn=1

[Burn]
BurnSize=15
BurnAllNamed=0

[GoM]
GoMSize=3

[KConditions]
ConOn=1
CondSize=6
Cond1=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-4]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+4]}
Cond2=${Spell[Tenacity].Stacks} || !${Target.Buff[Blessing of the Direwild].ID}
Cond3=${Target.Named} && ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}-7]} || ${Me.XTarget[1].Level}>=${Math.Calc[${Me.Level}+1]}
Cond4=${Me.PctMana} > 20 && ${Target.PctHPs} > 20 && ${Group.MainTank.PctHPs} > 80
Cond5=(${Group.Injured[80]} >= 3)
Cond6=${Me.PctMana} < 20 && ${Target.PctHPs} > 20 && ${Group.MainTank.PctHPs} < 50
Gem1=Sacred Elixir
Gem2=Complete Heal
Gem3=Sacred Light
Gem4=Word of Vivification
Gem5=Promised Renewal
Gem6=Unflinching Hammer of Zeal
Gem7=Divine Custody
Gem8=Rallied Aegis of Vie
Gem9=Mark of Kings

[Spells]
MiscGem=8
MiscGemLW=0
MiscGemRemem=1
CastingInterruptOn=1
LoadSpellSet=1
SpellSetName=KissAssist
